#!/usr/bin/env python3
"""
Property Monitor Static Site Builder
Usage: python build.py
"""
import json, os, sys
from pathlib import Path
from datetime import datetime

try:
    from jinja2 import Environment, FileSystemLoader, select_autoescape
except ImportError:
    os.system("pip install jinja2")
    from jinja2 import Environment, FileSystemLoader, select_autoescape

ROOT = Path(__file__).parent
DATA_DIR = ROOT / "market_data"
TEMPLATE_DIR = ROOT / "templates"

ALL_MARKETS = [
    {"id":"my",  "flag":"🇲🇾","name_en":"Malaysia",   "name_zh":"馬來西亞","path":"index.html"},
    {"id":"tw",  "flag":"🇹🇼","name_en":"Taiwan",     "name_zh":"台灣",    "path":"tw/index.html"},
    {"id":"jp",  "flag":"🇯🇵","name_en":"Japan",      "name_zh":"日本",    "path":"jp/index.html"},
    {"id":"au",  "flag":"🇦🇺","name_en":"Australia",  "name_zh":"澳洲",    "path":"au/index.html"},
    {"id":"nz",  "flag":"🇳🇿","name_en":"New Zealand","name_zh":"紐西蘭",  "path":"nz/index.html"},
    {"id":"uk",  "flag":"🇬🇧","name_en":"United Kingdom","name_zh":"英國","path":"uk/index.html"},
]

PAGES = [
    ("dashboard.html","index.html","index"),
    ("supply.html","supply.html","supply"),
    ("demand.html","demand.html","demand"),
    ("valuation.html","valuation.html","valuation"),
    ("risk.html","risk.html","risk"),
    ("report.html","report.html","report"),
]

def load_market(name):
    with open(DATA_DIR / f"{name}.json", encoding="utf-8") as f:
        return json.load(f)

def build_market(env, market_name):
    data = load_market(market_name)
    meta = data["meta"]
    market_dir = meta["dir"]
    depth = "../" if market_dir else ""
    out_dir = ROOT / market_dir if market_dir else ROOT
    out_dir.mkdir(exist_ok=True)
    print(f"\n📦 Building {meta['market_en']}...")

    for tmpl_name, out_name, page_id in PAGES:
        try:
            tmpl = env.get_template(tmpl_name)
        except Exception:
            print(f"  ⚠️  {tmpl_name} not found, skipping")
            continue
        html = tmpl.render(
            meta=meta, data=data,
            kpis=data.get("kpis",{}),
            charts=data.get("charts",{}),
            report=data.get("report",{}),
            supply_pipeline_flow=data.get("supply_pipeline_flow"),
            page_data=data.get("page_data",{}).get(page_id,{}),
            source_footer=data.get("source_footer",{}).get(page_id,{}),
            current_page=page_id,
            depth=depth,
            all_markets=ALL_MARKETS,
        )
        (out_dir / out_name).write_text(html, encoding="utf-8")
        print(f"  ✅  {out_name}")

    for city in data.get("cities", {}).values():
        try:
            tmpl = env.get_template("city.html")
        except Exception:
            print(f"  ⚠️  city.html not found, skipping cities")
            break
        html = tmpl.render(
            meta=meta, data=data, city=city,
            current_page=city["id"],
            depth=depth,
            all_markets=ALL_MARKETS,
        )
        (out_dir / city["file"]).write_text(html, encoding="utf-8")
        print(f"  ✅  {city['file']}")

    return data

def generate_context_md(all_data, now):
    lines = [
        "# Property Monitor — AI Context File",
        f"# Auto-generated by build.py · Last updated: {now}",
        "# DO NOT EDIT MANUALLY — changes will be overwritten on next build",
        "",
        "## 專案說明",
        "靜態房地產分析網站，覆蓋亞太多個市場。",
        "部署於 GitHub Pages (myproperty.investmquest.com via Cloudflare Pages)",
        "",
        "## 技術棧",
        "- Build: Python 3 + Jinja2",
        "- Frontend: Vanilla HTML/CSS/JS + ECharts 5.4.3",
        "- Deploy: Cloudflare Pages (auto-deploy from GitHub main)",
        "- Repo: github.com/keigoks-ivan/malaysia-property",
        "",
        "## 目錄結構",
        "```",
        "market_data/   ← JSON 數據（唯一需要手動更新的地方）",
        "templates/     ← Jinja2 HTML 模板",
        "build.py       ← 執行產生所有 HTML + md 文件",
        "css/style.css  ← 主樣式",
        "tw/tw.css      ← 子目錄共用補丁（所有市場都引用）",
        "CONTEXT.md     ← 本文件（自動生成）",
        "MAINTENANCE.md ← 維護手冊（自動生成）",
        "```",
        "",
        "## 現有市場",
        "| ID | 市場 | 目錄 | 利率標籤 | 利率值 | 城市頁 |",
        "|----|------|------|----------|--------|--------|",
    ]
    for d in all_data:
        m = d["meta"]
        cities = ", ".join(d.get("cities", {}).keys())
        dir_str = f"/{m['dir']}" if m['dir'] else "/"
        lines.append(f"| {m['dir'] or 'my'} | {m['market_en']} | {dir_str} | {m['badge_label']} | {m['badge_value']} | {cities} |")

    lines += [
        "",
        "## 核心工作流程",
        "```bash",
        "# 更新數據",
        "nano market_data/taiwan.json   # 改數據",
        "python build.py                # 重新產生所有 HTML + md",
        "git add . && git commit -m 'data: Q2 2026 update' && git push",
        "",
        "# 新增市場",
        "cp market_data/taiwan.json market_data/uk.json",
        "# 編輯 uk.json，在 build.py ALL_MARKETS 加一行",
        "python build.py",
        "```",
        "",
        "## JSON 結構",
        "```json",
        "{",
        '  "meta": { market_en, market_zh, flag, dir, badge_label, badge_value, badge_trend, nav_pages },',
        '  "kpis": { "dashboard": [...], "supply": [...], "demand": [...], "valuation": [...], "risk": [...] },',
        '  "charts": { chart_id: { title_en, title_zh, labels, data, ... } },',
        '  "cities": { city_id: { id, name_en, name_zh, file, kpis, charts } }',
        "}",
        "```",
        "",
        "## 模板變數",
        "| 變數 | 說明 |",
        "|------|------|",
        "| meta | market_data 的 meta 區塊 |",
        "| kpis | 當前頁的 KPI 列表（來自 kpis.[page_id]）|",
        "| charts | 當前頁的圖表數據 |",
        "| current_page | 當前頁面 id（用於 active nav）|",
        "| depth | 路徑深度（'' 根目錄 或 '../' 子目錄）|",
        "| all_markets | 所有市場清單（用於下拉選單）|",
        "| city | 城市頁專用，city.html 模板的城市數據 |",
        "",
        "## 顏色系統",
        "```javascript",
        "var C = {",
        "  navy:'#1e3a5f', green:'#16a34a', orange:'#d97706',",
        "  red:'#dc2626', blue:'#2563eb', muted:'#5a7a9a', grid:'#e8f0f9'",
        "}",
        "// 軸標籤統一用 #5a7a9a（C.muted）",
        "```",
        "",
        "## 重要注意事項",
        "- ECharts grid 必須加 containLabel:true，否則標籤被截斷",
        "- canvas{background:transparent} 會破壞圖表，禁止加入",
        "- 語言切換後必須 dispose + reinit 所有圖表",
        "- tw/tw.css 定義 kpi-row, chart-row, chart-card half/full 等",
        "- 雷達圖 legend 放 bottom:0，避免與 indicator 標籤重疊",
        "- report.html 三欄圖表用 .report-chart-grid（含 mobile 斷點）",
        "- 價格格式：fmtPrice(v,lang) 中文萬，英文 K/M",
    ]
    return "\n".join(lines)

def generate_maintenance_md(all_data, now):
    lines = [
        "# Property Monitor — 維護手冊",
        f"# Auto-generated by build.py · Last updated: {now}",
        "# DO NOT EDIT MANUALLY",
        "",
        "## 每季更新數據",
        "```bash",
        "# 1. 搜尋最新數據（或請 Claude 搜尋）",
        "# 2. 改對應的 JSON",
        "nano market_data/taiwan.json",
        "# 3. Rebuild",
        "python build.py",
        "# 4. 確認本地 HTML 正確後推上去",
        "git add . && git commit -m 'data: Q2 2026 update' && git push",
        "# 5. 等 1-2 分鐘 Cloudflare 自動部署",
        "```",
        "",
        "## 新增市場",
        "```bash",
        "cp market_data/australia.json market_data/uk.json",
        "# 改 uk.json 所有數據",
        "# 在 build.py ALL_MARKETS 加：",
        '# {"id":"uk","flag":"🇬🇧","name_en":"UK","name_zh":"英國","path":"uk/index.html"}',
        "python build.py && git add . && git commit -m 'feat: add UK market' && git push",
        "```",
        "",
        "## 改導航欄或共用樣式",
        "```bash",
        "nano templates/_base.html   # 改導航欄",
        "nano css/style.css          # 改主樣式",
        "nano tw/tw.css              # 改子目錄補丁",
        "python build.py && git push",
        "```",
        "",
        "## 兩台電腦同步",
        "```bash",
        "# 每次開始工作前",
        "git pull origin main",
        "# build.py 不需要重跑，HTML 已在 repo 裡",
        "```",
        "",
        "## 部署資訊",
        "- GitHub: github.com/keigoks-ivan/malaysia-property",
        "- 網站: myproperty.investmquest.com",
        "- 部署: push 到 main 後 Cloudflare 自動部署，約 1-2 分鐘",
        "",
        "## 市場數據狀態",
        f"（最後 build: {now}）",
        "",
        "| 市場 | 數據截至 | 利率 |",
        "|------|----------|------|",
    ]
    for d in all_data:
        m = d["meta"]
        lines.append(f"| {m['market_en']} | {m['data_asof_en']} | {m['badge_label']}: {m['badge_value']} |")

    lines += [
        "",
        "## 常見問題",
        "",
        "**圖表不顯示**",
        "→ 打開 DevTools (F12) 看 Console 錯誤",
        "→ 確認 ECharts CDN 載入（網路問題？）",
        "→ 確認 containLabel:true",
        "",
        "**語言切換後圖表沒更新**",
        "→ 確認 setLang() 有呼叫 initCharts(lang)",
        "→ 確認 allCharts.forEach dispose 在 reinit 之前",
        "",
        "**Cloudflare 沒更新**",
        "→ 確認有 push 到 main branch",
        "→ Cloudflare Dashboard 看 deployment log",
        "→ 強制清除快取: Cmd+Shift+R",
        "",
        "**build.py 跑出錯誤**",
        "→ 確認 jinja2 已安裝: pip install jinja2",
        "→ 確認 JSON 格式正確: python -c \"import json; json.load(open('market_data/taiwan.json'))\"",
    ]
    return "\n".join(lines)

def main():
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    market_files = sorted(DATA_DIR.glob("*.json"))

    if not market_files:
        print("❌ No JSON files found in market_data/")
        sys.exit(1)

    print(f"🏗️  Building {len(market_files)} markets...")
    all_data = []

    for f in market_files:
        data = build_market(env, f.stem)
        all_data.append(data)

    # 產生 md 文件
    print("\n📄 Generating documentation...")
    Path("CONTEXT.md").write_text(generate_context_md(all_data, now), encoding="utf-8")
    print("  ✅  CONTEXT.md")
    Path("MAINTENANCE.md").write_text(generate_maintenance_md(all_data, now), encoding="utf-8")
    print("  ✅  MAINTENANCE.md")

    print(f"\n🎉 Build complete! {len(market_files)} markets, {now}")
    print("\n📋 Next steps:")
    print("   git add . && git commit -m 'build: regenerate all pages' && git push")

if __name__ == "__main__":
    main()
