// 同一份結案內容供遊戲畫面與可下載 HTML 使用。
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const num = (n) => Math.round(n || 0).toLocaleString('zh-TW');
const money = (n) => `${n < 0 ? '−' : ''}$${num(Math.abs(n || 0))}`;
const status = { won: '市占目標達成', lost: '期限到期', bankrupt: '資金用盡', playing: '經營中快照' };
export function caseReportHtml(r) {
  const t = r.totals, costs = [['原料與包材', t.cogs + t.pack], ['原料報廢與庫存損失', t.waste + t.stockWriteOff], ['平台佣金', t.commission], ['人事', t.wage], ['租金', t.rent], ['水電、POS 與支付', t.util + t.pos + t.cardFee], ['廣告與事件', t.adCost + t.extraExpense], ['連鎖管理', t.chainCost], ['後勤固定費', t.facilityCost], ['研發專案', t.researchExpense], ['貸款利息', t.loanInterest], ['營業稅與營所稅', t.bizTax + t.incomeTax]];
  const tr = (name, value) => `<tr><td>${esc(name)}</td><td class="num">${money(value)}</td></tr>`;
  const table = (headers, body) => `<div class="tbl-scroll"><table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;
  return `<article class="case-report"><div class="card"><h2>${esc(r.company)}・結案分析</h2><p>${esc(status[r.status])}｜${esc(r.startDate)} 至 ${esc(r.endDate)}</p><p>${esc(r.reason || '截至目前的實際紀錄')}</p><div class="diagnosis-stats"><span>累計營收<b>${money(t.turnover)}</b></span><span>累計總成本<b>${money(t.totalCost)}</b></span><span>累計營運淨利<b>${money(t.netProfit)}</b></span><span>期末現金／貸款<b>${money(r.cash)}／${money(r.debt)}</b></span></div><p>扣除剩餘貸款後，現金相較開局資金增減 ${money(r.cash - r.debt - r.initialCash)}。這是現金與負債的比較，尚未計剩餘設備、押金及庫存價值。</p>${r.incomplete ? '<p class="note warn">此局含舊版帳目，部分品牌費用未記錄；受影響月份及累計數僅供參考。</p>' : ''}</div>
<div class="card"><h3>結果分析</h3>${r.findings.map((f) => `<p>${esc(f)}</p>`).join('')}<p>以下判斷依帳目與經營結果產生，沒有用未實際發生的情境判定單一決策造成多少獲利。</p></div>
<div class="card"><h3>成本花在哪裡</h3>${table(['成本項目', '整局累計'], costs.map(([k, v]) => tr(k, v)).join('') + tr('總成本', t.totalCost) + tr('營運淨利', t.netProfit))}</div>
<div class="card"><h3>投資與資金</h3>${table(['項目', '金額'], tr('開局自有資金', r.initialCash) + (r.borrowed == null ? '<tr><td>借入資金</td><td>舊存檔未完整記錄</td></tr>' : tr('整局借入資金', r.borrowed)) + tr(r.capitalIncomplete ? '開店投入（更新後已記錄的部分）' : '開店投入（裝潢、設備、首批庫存、押金）', t.shopInvestment) + tr('後勤建置投入', t.facilityCapex) + tr('開店與後勤投入合計', t.shopInvestment + t.facilityCapex) + tr('中央原料進貨付款', t.stockPurchases) + tr('償還本金（含提前還款）', t.loanPrincipal) + tr('關店與設施回收現金', t.assetRecoveries) + tr('期末現金', r.cash) + tr('未還本金', r.debt))}<p class="note">投資、進貨和本金會改變現金；建置費未計折舊，原料耗用才列成本。本表的付款與損益成本會重疊，不能再次相加。老闆自己顧店未另計薪資。提前還款未收手續費。</p></div>
<div class="card"><h3>各店表現（含已關閉門店）</h3>${table(['門店', '狀態', '累計杯數', '平均日銷', '營收', '門店淨利', '流失訂單', '星等'], r.shops.map((s) => `<tr><td>${esc(s.name)}</td><td>${esc({ open: '營業', closed: '已關閉', renovating: '裝修' }[s.status])}</td><td>${num(s.cups)}</td><td>${num(s.daily)}</td><td>${money(s.revenue)}</td><td>${money(s.profit)}</td><td>${num(s.lost)}</td><td>${s.star.toFixed(1)}</td></tr>`).join(''))}<p class="note">門店淨利尚未分攤品牌費用；日銷以實際營業天數計算。流失包含放棄排隊與打烊未完成訂單。</p></div>
<div class="card"><h3>連鎖的效益與代價</h3>${table(['項目', '整局累計'], tr('中央採購已實現節省', t.warehouseSavings) + tr('中央備料已實現節省', t.factorySavings) + tr('後勤固定費', t.facilityCost) + tr('連鎖管理費', t.chainCost) + tr('研發支出', t.researchExpense) + tr('原料節省扣後勤固定費', t.warehouseSavings + t.factorySavings - t.facilityCost))}<p>完成研發：${r.projects.length ? r.projects.map(esc).join('、') : '尚無'}。品質與產能改善未換算為保證收益。</p><p>期末全城有 ${r.market.openShops} 家營業店，${r.market.freeLots} 個空店面；典型日潛在需求約 ${num(r.market.potentialDaily)} 杯，全城產能約 ${num(r.market.capacityDaily)} 杯。市場需求有限，擴張仍需考慮分店互搶客源、固定費與品牌口碑連動。</p></div>
<div class="card"><h3>每月損益</h3>${table(['月份', '營收', '總成本', '淨利'], r.months.map((m) => `<tr><td>${esc(m.ym)}${m.incomplete ? '＊' : ''}</td><td>${money(m.turnover)}</td><td>${money(m.totalCost)}</td><td>${money(m.netProfit)}</td></tr>`).join(''))}</div>
<div class="card"><h3>經營紀錄</h3>${r.events.length ? r.events.map((e) => `<p><time>${esc(e.date)}</time>　${esc(e.text)}</p>`).join('') : '<p>尚無經營紀錄。</p>'}<p class="note">事件保留最近 800 筆記錄中的開關店、後勤、研發、貸款與批次異常，月帳為整局累計。舊存檔更新前的開店投入可能未記錄。所有數字反映遊戲模型，後勤參數為遊戲設計值。</p></div></article>`;
}
export function caseReportDocument(r) {
  return `<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(r.company)}・結案分析</title><style>body{font:16px/1.7 system-ui,sans-serif;background:#f3f5f7;color:#202b35;margin:0;padding:24px}article{max-width:1100px;margin:auto}.card{background:white;padding:24px;border-radius:12px;margin-bottom:18px}h2,h3{margin-top:0}.diagnosis-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.diagnosis-stats span{color:#56606c}.diagnosis-stats b{display:block;font-size:22px;color:#202b35}.tbl-scroll{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{text-align:right;padding:8px;border-bottom:1px solid #e2e5e9}th:first-child,td:first-child{text-align:left}.note{color:#626d79;font-size:14px}time{font-variant-numeric:tabular-nums}@media(max-width:600px){body{padding:10px}.card{padding:16px}.diagnosis-stats{grid-template-columns:1fr}}@media print{body{background:white;padding:0}.card{break-inside:avoid;padding:12px}}</style>${caseReportHtml(r)}</html>`;
}
