const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const number = n => Number(n).toLocaleString('zh-TW', { maximumFractionDigits: 1 });
export const driverValue = (n, unit) => n == null || !Number.isFinite(n) ? '待累積資料' : unit.startsWith('$') ? '$' + number(n) + unit.slice(1) : number(n) + (unit === '%' ? '%' : ' ' + unit);
export function coachHtml(c, { compact = false } = {}) {
  if (!c) return '';
  const b = c.bottleneck, d = c.decision;
  const driver = x => `<article><span>${esc(x.label)} <i>${x.type === 'observed' ? '實績' : x.type === 'state' ? '目前狀態' : '估算'}</i></span><strong>${esc(x.value == null && x.unavailable ? x.unavailable : driverValue(x.value, x.unit))}</strong><small>${esc(x.basis)}</small><p>${esc(x.detail)}</p></article>`;
  const shown = compact ? c.drivers.slice(0, 3) : c.drivers;
  return `<section class="business-coach" aria-label="業態關鍵因子"><div class="coach-head"><span>BUSINESS DRIVERS</span><h3>${esc(c.title || c.name)} · 經營關鍵</h3></div><div class="coach-formula"><b>${esc(c.formula.text)}</b><p>${esc(c.formula.detail)}</p></div><div class="coach-drivers">${shown.map(driver).join('')}</div><div class="coach-bottleneck ${esc(b.severity)}"><span>目前先處理</span><h4>${esc(b.title)}</h4><p>${esc(b.reason)}</p><h4>${esc(d.title)}</h4><p>${esc(d.action)}</p><p class="coach-tradeoff">代價與風險：${esc(d.tradeoff)}</p></div>${compact && c.drivers.length > 3 ? `<details><summary>更多關鍵因子（${c.drivers.length-3} 項）</summary><div class="coach-drivers">${c.drivers.slice(3).map(driver).join('')}</div></details>` : ''}<details><summary>指標與模型的範圍</summary>${c.assumptions.map(x => `<p>${esc(x)}</p>`).join('')}</details></section>`;
}
export function decisionReviewsHtml(reviews, { compact = false } = {}) {
  if (!reviews.length) return '<section class="decision-review"><h3>決策與結果</h3><p>調整經營後，這裡會留下設定、即時估算和七個完整營業日的結果。一次聚焦一個問題，再看成交、流失與成本是否改善。</p></section>';
  const html = `<section class="decision-review"><h3>決策與結果 <small>最近三次 · 隨存檔保留</small></h3>${reviews.map(r => `<article><h4>第 ${r.day + 1} 天 · ${esc(r.title)}</h4>${r.beforeSettings !== r.afterSettings ? `<details><summary>當次設定變更</summary><p>之前：${esc(r.beforeSettings)}</p><p>之後：${esc(r.afterSettings)}</p></details>` : ''}<p>操作當下現金變動：${esc(driverValue(r.cashChange, '$'))}</p>${r.changes.length ? `<div class="coach-change">${r.changes.slice(0, 4).map(x => `<span>${esc(x.label)}<b>${esc(driverValue(x.before, x.unit))} → ${esc(driverValue(x.after, x.unit))}</b></span>`).join('')}</div><p class="coach-note">以上是目前設定的狀態／估算變化，尚不是新增收入或利潤。</p>` : '<p class="coach-note">此決策的效果需等營業、生產或研發完成後觀察。</p>'}<h4>${r.after.days === 7 ? '七日觀察完成' : `觀察中 · ${r.after.days}／7 個完整營業日`}</h4>${r.after.days ? `<div class="coach-change">${r.after.metrics.map(x => { const old = r.baseline.metrics.find(b => b.id === x.id); return `<span>${esc(x.label)}<b>${old ? esc(driverValue(old.value, old.unit)) : '無之前樣本'} → ${esc(driverValue(x.value, x.unit))}</b></span>`; }).join('')}</div>` : '<p>從決策後的完整營業日開始累積，當天已有的成交不混入。</p>'}<p class="coach-note">之前 ${r.baseline.days} 天／之後 ${r.after.days} 天。${r.baseline.days < 7 ? '之前樣本不足七天，先觀察方向。' : ''}${r.overlap ? '期間也有其他決策。' : ''}客群、競爭、事件、訂單與季節也會改變結果；這是前後觀察，不能單獨證明因果。觀察期仍需用月報確認總成本與淨利。</p></article>`).join('')}</section>`;
  return compact ? `<details class="decision-archive"><summary>查看決策與七日觀察 · 最近 ${reviews.length} 次</summary>${html}</details>` : html;
}
