// Parallel, independently selectable Greyline stories. Radio follows real mission events.
const b=(zh,en)=>({zh,en});
const r=(speaker,zh,en)=>({speaker,text:b(zh,en)});

export const INFRASTRUCTURE_STORIES={
  dam:{
    title:b('留給下游的光','Light for the Lower Valley'),
    deck:b('機甲撤離後，水壩成了下游醫院最後的電力來源。舊命令仍優先供電給空倉庫，灰線必須守住道路，也讓責任回到真正等待的人身上。','After the mechs withdraw, the dam becomes the lower valley hospital’s last power source. Old orders still prioritize an empty depot. Greyline must hold the access road and redirect responsibility toward the people actually waiting.'),
    timeLabel:b('撤離第六日・08:20','EVACUATION DAY SIX · 08:20'),
    location:b('青沅水壩・下游供電走廊','Qingyuan Dam · Lower Valley Power Corridor'),
    background:[
      {
        title:b('一、機甲留下的空位','I. The Space the Mechs Left'),
        paragraphs:[
          b('機甲最後一次經過青沅水壩時，履帶在維修公路留下兩條深痕。駕駛員沒有停車，只透過外放喇叭告訴留守的人，重型單位必須撤往北面的集結區。林岳收到的新命令只有守住入口四個字，附圖卻還標著三個早已撤空的哨位。灰線抵達時，值班室的電話一直響，沒有一通是在詢問敵軍。','The last mech convoy through Qingyuan Dam left two deep track marks on the maintenance road. Its pilots did not stop; a loudspeaker told those staying behind that the heavy units had to regroup in the north. Lin Yue’s new orders simply said to hold the entrance, although the attached map still showed three abandoned posts. When Greyline arrived, the duty-room telephone kept ringing. None of the callers was asking about the enemy.'),
          b('下游醫院把病床搬到低樓層，為的是停電時不必等電梯。沈禾在電話另一端聽見推車碰門框的聲音，知道那些人已經搬了整夜。院方還有柴油，但能撐多久沒有人敢保證。陳隼把每次來電的時間抄在地圖邊上，提醒小隊這座水壩的任務不是守住一塊水泥，而是替看不見的人保留時間。','The hospital downstream had moved its beds to the lower floors so a power failure would not leave patients waiting for elevators. Over the telephone, Shen He heard trolley wheels striking doorframes and understood that the staff had been moving people all night. The hospital still had diesel, but nobody could guarantee how long it would last. Chen Sun wrote each call’s time in the map margin, reminding the squad that the dam’s purpose was to preserve time for people they could not see.'),
        ],
      },
      {
        title:b('二、沒有被修改的順位','II. An Order Nobody Revised'),
        paragraphs:[
          b('值班工程師羅沛已經兩天沒有離開控制區。他告訴林岳，供電順位不能隨口調換，舊命令要求先維持北側軍用倉庫的輸出。那座倉庫本來存放撤離車隊的燃料，因此誰也不願承擔停電責任。直到陳隼收到倉庫最後一份撤空回報，眾人才發現優先供電的對象早已沒有車輛，也沒有留守人員。','Duty engineer Luo Pei had not left the control area for two days. He warned Lin Yue that supply priorities could not be changed casually: an older order required the northern military depot to remain powered first. The depot had once held fuel for evacuation convoys, so nobody wanted responsibility for cutting its power. Then Chen Sun received the depot’s final evacuation report. The supposedly vital destination had neither vehicles nor personnel left inside.'),
          b('羅沛第一次承認，自己並非不知道醫院的處境，只是不敢在沒有簽名的情況下動那張順位表。沈禾沒有責怪他，她把院方記錄裡需要穩定供電的區域逐項讀給他聽。林岳則在命令副本上寫下自己的姓名，要求指揮部確認新的負載安排。敵軍正在接近，他們卻先花了幾分鐘，讓守線的理由變得清楚。','Luo Pei finally admitted that he knew the hospital’s situation; he simply feared altering the priority sheet without a signature. Shen He did not blame him. She read out the hospital’s list of areas requiring stable power. Lin Yue signed his own name on a copy of the order and asked command to confirm the revised allocation. With hostile troops approaching, the squad still spent a few minutes making the reason for holding the line clear.'),
        ],
      },
      {
        title:b('三、光不能只留給防線','III. Light Must Reach Beyond the Line'),
        paragraphs:[
          b('改變電力安排不是按下一個開關就能完成。留守技師仍要核對線路，沿遠端維修區完成必要的交接；灰線的工作是守住他們進出的道路，或奪回被敵軍占住的據點。羅沛將醫院來電轉接進小隊頻道，於是每次槍聲的間隙，都可能聽見另一端的人問今天能不能維持照明。那不是催促，而是他們的日常。','Reallocating power took more than pressing a switch. The remaining technicians still needed to verify circuits and complete handovers in the remote service area. Greyline’s task was to hold their access route or recover the positions occupied by hostile troops. Luo Pei patched hospital calls into the squad channel. Between gunshots, they could hear someone asking whether the lights would stay on today. It was not an attempt to hurry the soldiers; it was ordinary life continuing elsewhere.'),
          b('林岳把兩套作戰方案攤在同一張桌上。守衛戰要撐過四波攻勢，確保發電站入口不被切斷；衝鋒戰則依序確認維修閘口、壩頂平台與控制室。兩套任務都不要求灰線破壞壩體，也不把下游的人當作換取戰果的代價。沈禾收起那份有舊簽名的順位表，說等事情結束，應該把新名單交給真正用電的人看。','Lin Yue spread two operation plans across the same table. Defense meant surviving four attacks without losing access to the power station. Assault meant securing the maintenance gate, dam platform and control room in sequence. Neither plan called for damaging the dam or treating downstream civilians as an acceptable price for a tactical result. Shen He folded the old signed priority sheet and said the people actually using the electricity should eventually see its replacement.'),
        ],
      },
    ],
    cast:[
      {id:'lin',name:b('林岳','Lin Yue'),role:b('班長・防線指揮','Squad Leader · Line Commander'),detail:b('他習慣把命令縮成最短的句子，這次卻主動留下完整簽名。林岳明白撤退後的混亂不能全由值班工程師承擔，因此把供電責任與小隊的防守責任一起接了過來。','He usually reduces orders to the fewest possible words, but this time he leaves a full signature. Lin Yue refuses to make one duty engineer bear all the confusion of the withdrawal and accepts responsibility for both the distribution decision and the squad’s defense.')},
      {id:'shen',name:b('沈禾','Shen He'),role:b('軍醫・下游聯絡','Medic · Hospital Liaison'),detail:b('她沒有見過下游醫院的病人，卻能從一段短促回話判斷對方是否已經忙了一整夜。沈禾不許任何人把醫療需求寫成籠統數字，堅持逐項確認哪些地方真的需要電力。','She has never met the hospital’s patients, yet a brief reply can tell her that a staff member has worked through the night. Shen He refuses to reduce medical needs to a vague total and insists on confirming which areas actually need power.')},
      {id:'chen',name:b('陳隼','Chen Sun'),role:b('通訊兵・命令核對','Signal Operator · Order Verification'),detail:b('他把撤空回報、舊命令與醫院來電排在一起，找出了沒有人更新的供電順位。陳隼相信通訊不只是傳遞口令，也包括指出兩份看似正確的文件何時已經互相矛盾。','By comparing evacuation reports, old orders and hospital calls, he discovers the unchanged supply priorities. Chen Sun believes communications work includes recognizing when two apparently correct documents have become contradictory, not merely passing orders along.')},
      {id:'local',name:b('羅沛','Luo Pei'),role:b('值班工程師・電力交接','Duty Engineer · Power Handover'),detail:b('在這座水壩工作十五年，他知道每一條供電線的名字，卻一直不敢改掉命令上的第一順位。羅沛的轉變不是變得無所畏懼，而是願意把自己的判斷說清楚，交給別人一起承擔。','After fifteen years at the dam, he knows every feeder by name but has been afraid to change the order’s first priority. His change is not sudden fearlessness: he finally explains his judgment openly and lets others share responsibility for it.')},
    ],
    stakes:[
      b('發電站入口連著遠端技師的進出路線。失去這條防線，醫院即使知道該接哪一條電力線，也不能立即完成交接。','The power station entrance provides access for the remote technical crews. If it falls, knowing which feeder the hospital needs will not be enough to complete the handover.'),
      b('壩頂高低落差讓敵軍能分開施壓。灰線必須照顧側翼與隊友，不能只盯著公路上最容易看見的那一批步兵。','The height changes along the dam let hostile units apply pressure from separate directions. Greyline must watch the flanks and squadmates instead of focusing only on the infantry most visible on the road.'),
      b('舊命令曾有合理的理由，卻不再符合現場。小隊要留下能核對的回報，讓下一班留守者不用再次猜測誰該先得到電力。','The old order once had a valid purpose, but it no longer matches the situation. The squad must leave a verifiable report so the next shift does not have to guess who should receive power first.'),
    ],
    defend:{
      brief:[
        b('灰線小隊在發電站入口建立防線，四波敵軍將沿公路、坡道與側翼接近。林岳要求每次整備都先確認人員與火力，再確認防線還剩多少餘裕。羅沛帶領遠端技師核對醫院的供電安排，沈禾負責保持兩端通話。你們不用看見病床，也知道這條路一旦被截斷，誰會先被迫等待。','Greyline establishes a line at the power station entrance. Four hostile waves will approach by road, ramps and flanks. Lin Yue orders the squad to check personnel and weapons during each regroup before assessing the line’s remaining margin. Luo Pei leads remote technicians through the hospital power handover while Shen He keeps both ends connected. You do not need to see the beds to know who will be forced to wait if this road is cut.'),
        b('敵軍越接近入口，下游交接就越難維持。守住掩體不是為了拖到某個看不見的奇蹟，而是把每一波攻勢確實擋下。陳隼會在最後殘敵時回報即時位置，讓小隊把有限時間用在完成清場。只要四波全部解除，技師便能收到安全交接的確認；在那之前，任何過早的平安回報都沒有意義。','The closer the attackers get to the entrance, the harder the handover becomes to sustain. Holding cover is not about waiting for an unseen miracle; it means stopping each attack properly. Chen Sun reports the final enemies’ live positions so the squad can spend its limited time finishing the clearance. Only after all four waves are cleared can the technicians receive confirmation that the handover route is secure. An early claim of safety would mean nothing.'),
      ],
      deploy:[
        r('lin','灰線，守住發電站入口。四波攻勢解除之前，下游交接不能算安全。','Greyline, hold the power station entrance. The downstream handover is not secure until all four attacks are cleared.'),
        r('local','醫院那條線已經列入交接，遠端技師正在核對。入口的安全就拜託你們。','The hospital feeder is on the handover list. The remote crew is checking it now. We are relying on you to keep the entrance secure.'),
      ],
      stages:[
        [r('chen','第一波沿公路接近，側邊也有動靜。別讓入口的視線把整支小隊綁住。','First wave approaching along the road; movement on the sides too. Do not let the entrance lane pin the whole squad in place.'),r('shen','醫院回報已經換班，新來的人還不知道電力順位改了。我會再講一次。','The hospital shift has changed. The new staff have not heard about the revised power priority. I will explain it again.'),r('lin','先把這一波擋乾淨，再談下一步。掩護換彈的人，別讓側翼出現空隙。','Clear this wave before thinking about the next. Cover anyone reloading and do not leave a gap on the flanks.')],
        [r('lin','第二波開始，維修坡道的火力會牽制入口。灰線，讓小隊保持互相掩護。','Second wave starting. Fire from the maintenance ramp can pin the entrance. Greyline, keep the squad covering one another.'),r('local','倉庫最後的撤空回報已核對，裡面確實沒有人。我把這句寫進交接紀錄。','The depot’s final evacuation report is verified. There really is nobody left inside. I am putting that in the handover record.'),r('chen','北側回報與舊命令終於對上了。現在記錄的是現場，不是昨天的安排。','The northern report and old order have finally been reconciled. Our record now reflects the situation here, not yesterday’s plan.')],
        [r('shen','第三波來了，醫院仍在用備援供電。別因為聽見有電，就以為他們能久等。','Third wave incoming. The hospital is still using backup power. Having electricity now does not mean they can wait indefinitely.'),r('lin','注意高處與中央通路，重裝火力會逼人離開掩體。不要把換位變成分散。','Watch the high ground and central approach. Heavy fire may force you out of cover. Reposition without scattering.'),r('local','我以前只怕順位改錯，現在更怕大家明知需要改，卻還把表留在原地。','I used to fear changing the priority incorrectly. Now I fear leaving the sheet untouched when we know it has to change.')],
        [r('chen','最後一波正在接近，醫院值班室保持在線。你們的確認會直接送到那邊。','The final wave is approaching. The hospital duty room is staying on the channel. Your confirmation will go straight to them.'),r('lin','灰線，入口還在我們手裡。清掉最後的攻勢，別把完成回報留給猜測。','Greyline, the entrance is still ours. Clear the last attack and make the completion report certain.'),r('shen','我會等全部敵軍解除再說安全。現在只要守住身邊的人，還有這條道路。','I will not call it secure until every attacker is cleared. For now, protect the people beside you and this access road.')],
      ],
      regroup:[
        [r('lin','第一波解除，先清點小隊與彈匣。防線還沒有結束，別急著把掩體讓出去。','First wave cleared. Count the squad and check magazines. The defense is not over; do not give up your cover.'),r('shen','下游聽見你們的回報了。他們沒有要求更快，只請我們把下一波也守住。','They heard your report downstream. They did not ask you to hurry, only to hold through the next wave too.')],
        [r('local','第二波解除，醫院的負載清單已經確認。這次沒有哪一間空倉庫排在前面。','Second wave cleared. The hospital load list is confirmed. No empty depot is ahead of it this time.'),r('chen','我把新順位傳給下一班留守者。等他們接手，不必再靠一張過期命令猜測。','I sent the revised priorities to the next shift. They will not have to guess from an outdated order when they take over.')],
        [r('lin','第三波解除，剩最後一次交戰。把補給留給真正需要的人，別離開掩護太遠。','Third wave cleared; one fight remains. Leave supplies for those who need them and stay within supporting distance.'),r('shen','醫院說走廊還亮著，工作還在繼續。那就是我們應該帶進最後一波的消息。','The hospital says the corridors are still lit and work is continuing. Carry that news into the final wave.')],
      ],
      win:[
        b('第四波解除後，羅沛先確認入口，再確認遠端交接紀錄。他的聲音不像一開始那樣急，卻在讀到醫院的名字時停了一下。指揮部回報必要供電已經轉入新的安排，下游值班室則只傳來一句收到。沒有誰在頻道裡慶祝太久，因為那邊的人還要繼續工作，而這正是灰線守到現在的理由。','After the fourth wave, Luo Pei verifies the entrance and then the remote handover log. He sounds less hurried than before, but pauses when he reads the hospital’s name. Command confirms that essential power has entered the revised allocation. The downstream duty room simply acknowledges it. Nobody celebrates for long on the channel: the staff there still have work to do, and that is precisely why Greyline held this line.'),
        b('林岳把新的順位表壓在舊命令上，要求接班人同時保留兩份文件。錯誤不能因為結局還算好就被擦掉，改正也不能只留在某一個人的記憶裡。沈禾最後問了一次醫院是否需要補充回報，對方說目前不用。灰線終於能把無線電音量調低一點，讓耳朵重新聽見水沿著壩體流動的聲音。','Lin Yue places the revised priority sheet over the old order and instructs the next shift to keep both. A tolerable outcome must not erase the mistake, and its correction must not survive only in one person’s memory. Shen He asks the hospital once more whether it needs another report. For now, it does not. Greyline can finally lower the radio volume and hear water moving along the dam again.'),
      ],
      costly:[
        b('入口守住了，交接也得到確認，但防線留下的損傷沒有隨回報消失。醫療組把人員狀況與尚待補充的物資列成清單，請接班者逐項確認。醫院收到電力消息後沒有要求小隊立刻撤走，而是請他們先把自己的狀況說清楚。灰線這才明白，幫助不是只有從這邊送往下游的一個方向。','The entrance holds and the handover is confirmed, but the damage to the line does not vanish with the report. The medical team lists personnel conditions and supplies still needed, asking the incoming shift to verify each item. After receiving the power update, the hospital does not ask the squad to leave immediately; it asks them to report their own condition first. Greyline realizes that help does not travel in only one direction, from the dam to the valley.'),
        b('羅沛在交接簿上留下空白，等那些尚未完成的核對。他沒有再用已恢復供電把所有事情概括成順利，也沒有把沉重的代價推給一個好看的結局。受損防線與後續需求被一併送回指揮部，沒有任何一項因此省略。這場守衛讓下游繼續亮著，卻也提醒下一班人，維持那道光需要有人持續照顧留下來的人。','Luo Pei leaves space in the handover book for the checks still outstanding. He no longer treats restored power as proof that everything went smoothly, or lets a reassuring ending conceal the cost. The damaged line and follow-up needs go to command together, with nothing omitted. This defense keeps the valley lit, but it also reminds the next shift that preserving that light requires continued care for the people who remain behind.'),
      ],
      loss:[
        b('發電站入口的安全回報中斷，指揮部不得不讓遠端技師暫停交接。下游醫院轉回原先的備援安排，沈禾在最後的通話裡聽見有人重新確認推車路線。事情沒有因為防線失守立刻結束，但每一項原本快能完成的工作都被迫退回等待。羅沛把停下來的時間寫進紀錄，沒有替它找一個比較好聽的名字。','The power station entrance can no longer be confirmed secure, and command has to suspend the remote handover. The hospital returns to its backup arrangements. In the final call, Shen He hears staff checking trolley routes again. Losing the line does not end everything instantly, but work that was almost ready to proceed is forced back into waiting. Luo Pei records the time of the interruption without giving it a gentler name.'),
        b('林岳最後留下的命令是保留已核對的順位與線路資料，不能讓下一支小隊重新從錯誤開始。灰線的回報停在尚未完成，醫院的名字卻仍排在新的清單上。若有下一次部署，他們需要重新守住入口，也需要記得這次拖延落在誰身上。戰場可以再來一次，那些等待的人卻已經用掉了更多時間。','Lin Yue’s final instruction is to preserve the verified priorities and circuit records so the next squad does not begin with the same mistake. Greyline’s report remains incomplete, but the hospital’s name stays on the revised list. Another deployment will have to secure the entrance again and remember who carried the delay this time. The battle can be attempted again; the people waiting downstream have already spent more of their time.'),
      ],
    },
    assault:{
      brief:[
        b('敵軍占住維修閘口、壩頂平台與閘門控制室，羅沛的遠端技師無法完成必要交接。灰線將沿既有坡道依序奪回三座據點，確認周邊威脅解除後保持佔領。陳隼會把每次完成回報傳給電力組，讓他們知道哪一段工作已經能繼續。小隊奪回的是一條責任鏈，沒有任何一個據點能替另外兩個草率簽名。','Hostile troops occupy the maintenance gate, dam platform and gate control room, preventing Luo Pei’s remote crew from completing the handover. Greyline will follow the existing ramps and secure the three positions in sequence, holding each only after the nearby threat is cleared. Chen Sun sends every completion report to the power team so it knows which work can resume. The squad is recovering a chain of responsibility; no one position can certify the other two.'),
        b('林岳不要求小隊為了速度越過還沒有處理的火力。佔領受到干擾時，先處理威脅，離開後也要重新確認進度；沈禾會利用整備間隙照顧仍能跟上的人。羅沛已承認舊供電順位不再適用，但只有控制室的安全得到確認，他才能讓新的安排成為正式交接。灰線要把那份決定送到能執行它的地方。','Lin Yue does not ask the squad to bypass unresolved fire merely for speed. When capture is interrupted, address the threat; when returning after leaving, check the progress again. Shen He uses regrouping pauses to care for those still advancing. Luo Pei has acknowledged that the old priorities no longer apply, but the control room must be confirmed secure before the new allocation can become a formal handover. Greyline must carry that decision to the place where it can be enacted.'),
      ],
      deploy:[
        r('lin','灰線，按順序奪回三座據點。閘口、壩頂、控制室，每一處都要確認清楚。','Greyline, secure the three positions in order: gate, crest, control room. Confirm each one properly.'),
        r('local','遠端技師等你們的據點回報，再接續交接。不要替還有敵軍的地方報平安。','The remote crew will continue the handover after your position reports. Do not certify an area that still has a hostile threat.'),
      ],
      stages:[
        [r('chen','第一座是維修閘口，交接路線從這裡開始。附近敵軍沒解除，進度就不可靠。','The first position is the maintenance gate, where the handover route begins. Progress is not reliable until nearby threats are cleared.'),r('shen','醫院仍在等確認，不必替他們承諾時間。先把眼前這一段安全地拿回來。','The hospital is still waiting for confirmation. Do not promise a time on its behalf; recover this section safely first.'),r('lin','注意閘口兩側，讓小隊互相掩護。佔領受到干擾，就先處理威脅再回來。','Watch both sides of the gate and keep the squad mutually supported. If capture is interrupted, deal with the threat before resuming.')],
        [r('lin','第二座是壩頂平台，高低差會分開火力。不要讓走在前面的人獨自承擔。','The second position is the dam platform. Height changes can separate your firing lanes. Do not leave the lead soldier alone.'),r('local','北側空倉庫已從優先名單移開，技師正在核對。今天的電力終於有新去處。','The empty northern depot is off the priority list. The technicians are verifying the change. Today’s power finally has a new destination.'),r('chen','新順位已收到指揮部確認，我保留了整段回報。這次不是誰私下改過一張表。','Command has confirmed the revised priorities. I kept the entire transmission. This is not a sheet someone quietly altered on their own.')],
        [r('shen','最後是閘門控制室，醫院也聽見你們正在接近。越到這裡，越要把人帶齊。','The final position is the gate control room. The hospital has heard you are approaching. This is where keeping the squad together matters most.'),r('lin','灰線，清除控制室附近的威脅後再確認佔領。最後一步也不能靠猜測完成。','Greyline, clear the threats around the control room before confirming capture. The final step must not be completed on a guess.'),r('local','我會等你們完整回報，再讓技師接續工作。醫院的名字已經寫在第一行。','I will wait for your complete report before the crew resumes work. The hospital’s name is already on the first line.')],
      ],
      regroup:[
        [r('lin','維修閘口已確認，先整備再向壩頂推進。別把第一個成功當成整條路都安全。','The maintenance gate is confirmed. Regroup before advancing to the crest. One success does not make the whole route secure.'),r('chen','電力組收到第一段回報了，我正在交給下一班。你們奪回的地方有人接手。','The power team received the first report. I am passing it to the next shift. Someone is taking responsibility for what you recovered.')],
        [r('shen','壩頂平台已確認，傷勢與彈匣現在處理。控制室還在前面，不要省下該用的時間。','The dam platform is confirmed. Treat injuries and check magazines now. The control room is ahead; take the time you need.'),r('local','下游值班室問是不是快完成了，我回答還有最後一座。這次不提前說一切正常。','The downstream duty room asked if we were nearly finished. I told them one position remained. This time I will not claim everything is normal too early.')],
      ],
      win:[
        b('控制室的佔領確認送出後，羅沛才把最後一份交接記錄簽完。他讀出的不是設備編號，而是醫院、泵站與留守區的名字。陳隼將這段回報保留下來，沈禾則等待院方確認收到新的供電安排。三座據點讓同一份決定終於有了完整路徑，灰線不必再替文件上互相矛盾的箭頭尋找解釋。','Only after the control room’s capture is confirmed does Luo Pei sign the final handover record. He reads the names of the hospital, pumping station and remaining civilian district rather than equipment numbers. Chen Sun saves the report while Shen He waits for the hospital to acknowledge the revised allocation. The three recovered positions give one decision a complete route into action. Greyline no longer has to explain contradictory arrows on the paperwork.'),
        b('林岳沒有把新順位表帶走當成紀念，而是留給接班的技師。真正需要保存的不是一張有小隊簽名的紙，是往後的人能清楚知道電力為誰保留。下游最後一次來電時，背景的聲音已變成正常交班的對話。灰線離開這條供電走廊前，終於收到一句不用急著回答的話：我們接下來可以繼續了。','Lin Yue does not take the revised sheet away as a souvenir; he leaves it for the technicians taking over. What matters is not a paper bearing the squad’s signatures but future staff knowing whom the power is reserved for. In the last downstream call, the background noise has become an ordinary shift handover. Before Greyline leaves the power corridor, it hears a sentence that needs no hurried reply: we can continue from here.'),
      ],
      costly:[
        b('三座據點都得到確認，電力組也開始接續交接，但這條坡道沒有因為任務完成就變得輕鬆。留守醫療組把小隊目前的狀況逐一傳回，要求後續接班同時帶來工具與必要醫療物資。羅沛第一次主動詢問灰線還需要什麼。他已經不再把技師的工作與士兵的代價分成兩張毫不相干的表。','All three positions are confirmed and the power team resumes the handover, but completing the mission does not make the ramps an easy road. The remaining medical team reports the squad’s condition and asks the next shift to bring both tools and necessary medical supplies. Luo Pei takes the initiative to ask what Greyline still needs. He no longer records the technicians’ work and the soldiers’ cost on two unrelated sheets.'),
        b('下游的必要供電得到安排，戰場留下的問題卻仍要有人接著處理。完成回報後仍附著尚未結束的核對，通訊中繼把每一項需求交給能回覆的人。灰線並沒有因為奪下控制室就替所有代價找到答案，但至少不再讓那些代價隱藏在一個完成標記後面。這是一場成功，也是下一班人的責任起點。','Essential power is allocated downstream, but someone must still address the problems left on the battlefield. Unfinished checks remain attached to the completion report, and the communications relay routes each need to someone able to respond. Capturing the control room does not answer every cost Greyline has incurred. It does prevent those costs from disappearing behind a completion mark. This is a success and the beginning of the next shift’s responsibilities.'),
      ],
      loss:[
        b('最後一份安全確認沒有送到電力組，三座據點之間的交接再次停下。醫院保留新的優先順位，卻只能繼續依賴備援安排。羅沛不再把原因說成單純的設備問題，他把敵軍壓力、失去的路段與尚未完成的工作分別記下。失敗的回報終於準確，代價則是下游的人還得繼續等待。','The final security confirmation never reaches the power team, and the handover between the three positions stops again. The hospital retains its new priority but still has to rely on backup arrangements. Luo Pei no longer describes the cause as a simple equipment problem; he separately records hostile pressure, the lost route and the unfinished work. The failure report is finally accurate. Its cost is that people downstream must keep waiting.'),
        b('指揮部要求保留已確認的路線資料，供下一次部署重新規劃。林岳與陳隼最後留下的紀錄沒有許諾一個完成時間，只有需要處理的據點與還在等回報的名字。灰線未能把這條責任鏈接到最後，沈禾卻仍讓醫院知道，新的順位沒有被取消。下一支小隊必須把剩下的路走完，而不是再從那張舊命令開始。','Command orders the verified route records preserved for another deployment. The final notes from Lin Yue and Chen Sun promise no completion time; they list the positions that still need securing and the names awaiting a report. Greyline has not joined the full chain of responsibility, but Shen He makes sure the hospital knows its new priority has not been revoked. The next squad must finish the route instead of beginning with the old order again.'),
      ],
    },
    cleanup:[
      r('chen','最後殘敵的即時位置已確認，距離與高低都在標記上。不要再把整座壩繞一遍。','The final enemies’ live positions are confirmed. Their markers show distance and elevation. You do not need to search the whole dam again.'),
      r('lin','灰線，按定位清除最後威脅，掩護換位的隊友。入口與據點都要留完整回報。','Greyline, follow the tracking to clear the remaining threat and cover squadmates repositioning. Leave a complete report for the entrance and each position.'),
    ],
    operationNotes:[
      b('壩頂封鎖讓敵軍分批施壓，遠處火力與後續重裝兵需要耐心處理；沈禾提醒灰線，準確射擊比急著交差更可靠。','Crest blockade brings attacks in spaced groups, with distant fire and later heavy infantry requiring patience. Shen He reminds Greyline that accurate shooting is more reliable than rushing the report.'),
      b('維修坡道爭奪讓兩翼與中央交替接近，小隊要持續互相照應；林岳要求回報據點時，也確認跟在身後的人。','Maintenance ramp contest alternates pressure between the flanks and center, demanding continuous squad support. Lin Yue wants each position report to include a check on the people following behind.'),
      b('緊急啟閘方案給技師更窄的交接時程，中央火力也更密；羅沛不要求灰線操作設備，只等待迅速而完整的安全確認。','Emergency gate release gives the technical crew a tighter handover schedule and brings denser central fire. Luo Pei asks Greyline for a prompt, complete security confirmation; the crew handles the equipment.'),
    ],
    afterword:[
      b('後來的交接簿沒有替這一天取一個響亮名字。上面只有四波攻勢或三座據點的時間，醫院收到回報的時間，以及需要下一班接續的項目。羅沛把新順位表留在每個值班者都看得到的地方，陳隼則保留舊命令作為對照。灰線留下的成果不是讓人不再犯錯，而是讓下一個人有機會看出錯誤。','The later handover book gives this day no grand name. It records the times of four attacks or three recovered positions, the hospital’s acknowledgments and the tasks for the next shift. Luo Pei puts the revised priorities where every duty worker can see them, while Chen Sun retains the old order for comparison. Greyline’s legacy is not that people will never make mistakes again, but that the next person has a chance to recognize one.'),
      b('沈禾記得的則是一段很普通的聲音：有人在電話那端交代下一班，走廊的燈今天可以照常留著。機甲離開後，沒有任何一支小隊能守住整片土地，灰線也沒有那樣的承諾。他們只是把一段道路、一份命令和幾個人的判斷接在一起，讓遙遠地方的一個日常，不必在這一天被迫中止。','Shen He remembers an ordinary sound: someone on the telephone telling the next shift that the corridor lights could stay on as usual today. After the mechs leave, no squad can hold every stretch of ground, and Greyline makes no such promise. They connect one access road, one order and several people’s judgments so that an ordinary routine somewhere far away does not have to stop on this day.'),
    ],
  },
  airfield:{
    title:b('最後一份載重表','The Last Load Sheet'),
    deck:b('最後班機在遠端跑道等待名冊，載重卻沿用舊帳。灰線守住地面，貨運監督則必須決定哪些東西留下，才能讓必要的人與器材一起離開。','The final flight waits on the remote runway, but its payload uses outdated figures. Greyline holds the ground while the cargo supervisor decides what stays so the people and equipment that need to travel can leave together.'),
    timeLabel:b('撤離第七日・16:40','EVACUATION DAY SEVEN · 16:40'),
    location:b('白石機場・西側停機坪與航管中繼區','Baishi Airfield · Western Apron and Control Relay'),
    background:[
      {
        title:b('一、只剩一個班次','I. One Flight Remaining'),
        paragraphs:[
          b('白石機場的出發看板早已停用，貨運監督周岑把最後的班次寫在紙上，貼在值班桌前。真正承接撤離的班機位於視線之外的東側跑道，西側停機坪只剩待整理的物資與留守人員。機甲撤往北方後，這段地面防線交給灰線。林岳收到的要求很簡單：讓最後一份名冊與地面確認能夠安全送出去。','Baishi Airfield’s departure board no longer works. Cargo supervisor Zhou Cen writes the last flight on paper and tapes it in front of the duty desk. The aircraft carrying evacuees waits on the eastern runway, out of sight; the western apron holds supplies still being sorted and the personnel left behind. After the mechs withdraw north, Greyline takes over this ground perimeter. Lin Yue’s instructions are simple: get the final manifest and ground confirmation out safely.'),
          b('周岑不准任何人用還有幾個座位回答撤離問題。載重表必須算進人員、行李與必要醫療物資，航務已核定的燃料也不能拿來換空間。沈禾聽完後，把醫療清單重新拿出來核對；陳隼則發現，名冊上的人數雖然正確，先前傳來的貨物重量卻仍是第一批撤離時的舊數字。最後一班從一開始就背著錯帳。','Zhou Cen will not let anyone answer evacuation questions by quoting the number of empty seats. The load sheet must include people, baggage and essential medical supplies, and the flight’s approved fuel cannot be traded for space. Shen He rechecks the medical list. Chen Sun discovers that although the passenger count is correct, the reported cargo weight still comes from the first evacuation group. The last flight has been carrying an outdated calculation from the start.'),
        ],
      },
      {
        title:b('二、不能刪掉的重量','II. Weight That Cannot Be Removed'),
        paragraphs:[
          b('一份補報讓問題變得具體：遠端撤離點還有需要隨身醫療器材的人，器材從未列入普通行李。周岑沒有說把誰留下比較容易，他先要求把每一箱物資的去向重新標清楚。沈禾指出哪些東西確實必須隨人同行，其他人則核對能留給後續地面接收的器材。這不會讓載重限制消失，只會讓選擇終於有正確的名字。','A supplementary report makes the problem concrete: people at the remote evacuation point require medical equipment that was never counted as ordinary baggage. Zhou Cen does not ask who would be easiest to leave behind. He asks for every supply crate’s destination to be relabeled. Shen He identifies what must travel with its users while others check which equipment can remain for later ground collection. The payload limit does not disappear; the choices finally acquire accurate names.'),
          b('周岑自己的行李是一箱多年保存的工具與工作紀錄，他原先把它填在必要器材那一欄。當陳隼問這一箱是否也不能留下時，他沒有立刻回答。那是他在機場度過大半人生的證明，也是表上最容易被一個熟人略過的重量。周岑最後把箱子移到地面接收清單，要求同事記下位置，不要替它換成另一個名稱。','Zhou Cen’s own baggage is a box of tools and work records saved over many years. He originally listed it as essential equipment. When Chen Sun asks whether this box also cannot remain, he does not answer immediately. It is evidence of a life largely spent at the airfield—and the weight a familiar colleague could most easily overlook. Zhou Cen finally transfers it to the ground-collection list and asks a coworker to record its location without relabeling it as something else.'),
        ],
      },
      {
        title:b('三、留下的人也需要回報','III. Those Staying Need a Report Too'),
        paragraphs:[
          b('工具箱被留下後，其他可延後運送的物資才陸續找到真正的接收去處。這份名冊仍有等待核對的欄位，因為最後班機不能只照顧登機的人，也要讓留守者知道哪些工作還由自己接續。林岳拒絕用一句全部撤離概括機場的狀況，他要求陳隼把遠端旅客、地面物資與留下的人員分成三份清楚的回報。','Once the toolbox is left behind, other supplies that can travel later begin finding real recipients on the ground. The manifest still has fields awaiting verification. The final flight must account for those boarding and tell the people staying which work remains theirs. Lin Yue refuses to summarize the airfield’s situation as everyone evacuated. He asks Chen Sun for three clear reports: remote passengers, ground supplies and the personnel remaining here.'),
          b('灰線可以守住停機坪，抵擋四波敵軍，替地面整備留下完整時段；也可以依序奪回停機坪防線、維修機庫與航管通訊台，讓中斷的回報重新接通。小隊的任務始終在這片地面上，班機的進度由遠端頻道確認。周岑把最後一份載重表交給通訊兵時，另外附上一張清單，寫著班機離開以後仍需要有人回應的名字。','Greyline can hold the apron through four attacks, giving the ground crew an uninterrupted working window. Or it can recover the apron line, service hangar and air traffic relay in sequence to reconnect the interrupted reports. The squad’s task remains on this ground; flight progress is confirmed over the remote channel. When Zhou Cen hands the final load sheet to the signal operator, he attaches another list: names that will still need an answer after the aircraft has left.'),
        ],
      },
    ],
    cast:[
      {id:'lin',name:b('林岳','Lin Yue'),role:b('班長・地面防線','Squad Leader · Ground Perimeter'),detail:b('他知道最後班機是一句容易讓人只顧往前衝的話，因此反覆要求完整回報。林岳在這裡的責任不只替離開的人守路，也要確保留下的人不會被一份完成紀錄從名冊上抹掉。','He knows that the words final flight can make people rush ahead without looking back, so he repeatedly insists on complete reports. Lin Yue must keep the route open for those leaving and ensure that a completion entry does not erase those staying from the manifest.')},
      {id:'shen',name:b('沈禾','Shen He'),role:b('軍醫・必要器材核對','Medic · Essential Equipment Check'),detail:b('她把醫療器材寫成與使用者相連的項目，而不是能任意刪掉的行李。沈禾清楚有限載重意味著什麼，但不接受把一個仍有需要的人，簡化成表格上比較難處理的那一列。','She lists medical equipment together with its users instead of treating it as baggage that can simply be deleted. Shen He understands limited payload, but refuses to reduce a person who still needs help to the troublesome row on a spreadsheet.')},
      {id:'chen',name:b('陳隼','Chen Sun'),role:b('通訊兵・最後名冊','Signal Operator · Final Manifest'),detail:b('他發現沿用舊重量的錯誤，也問出了周岑一直避開的問題。陳隼不把完整回報當作形式，因為班機一旦收到名冊，遠方的人就會依照那份資料決定誰與什麼能夠一起離開。','He discovers the reused weight figures and asks the question Zhou Cen has avoided. Chen Sun does not see a complete report as a formality: once the aircraft receives the manifest, people far away will use it to decide who and what can travel together.')},
      {id:'local',name:b('周岑','Zhou Cen'),role:b('貨運監督・載重簽核','Cargo Supervisor · Load Approval'),detail:b('他在機場工作半生，原先以為只要把數字簽對，就算完成最後一次值班。留下自己的工具箱後，周岑才真正接受公平也會碰到自己的東西，而留在地面的物資仍需要有人負責接收。','He has worked at the airfield for half his life and thought signing the correct figures would finish his last shift. After leaving his own toolbox, Zhou Cen accepts that fairness reaches his belongings too—and that supplies remaining on the ground still need someone responsible for them.')},
    ],
    stakes:[
      b('最後班機的載重有明確邊界。灰線不能增加那條邊界，只能讓正確名冊與地面確認及時送達，避免別人依據舊帳做決定。','The last flight has a firm payload limit. Greyline cannot increase it; it can get the correct manifest and ground confirmation through in time so nobody makes the decision using outdated figures.'),
      b('停機坪缺少連續掩體，機庫兩側又可能出現交叉火力。小隊要輪流推進與掩護，不能把遠方的撤離時程當成暴露自己的理由。','The apron lacks continuous cover, while both sides of the hangars can produce crossfire. The squad must alternate movement and support instead of treating a distant evacuation schedule as a reason to expose itself.'),
      b('班機離開以後，地面仍有工作與人員需要交接。成功的回報必須說清楚誰已經離開、哪些物資留下，以及誰仍在等接班。','After the flight leaves, personnel and work still need handing over on the ground. A successful report must identify who departed, which supplies remain and who is waiting to be relieved.'),
    ],
    defend:{
      brief:[
        b('灰線在運輸機整備區維持停機坪防線，四波敵軍會試著迫使小隊失去掩護。周岑與遠端地勤正在重算最後班機的載重，沈禾協助確認必須隨人同行的器材，陳隼保持兩邊通話。你們要在這片地面完成守衛，讓遠端工作能在可信的安全回報下繼續。','Greyline holds the apron line around the transport staging area through four attacks intended to force the squad out of cover. Zhou Cen and the remote ground crew are recalculating the last flight’s payload. Shen He verifies equipment that must accompany its users, and Chen Sun keeps the two sides connected. Complete the defense here so work elsewhere can continue on the strength of a reliable security report.'),
        b('林岳要求每波結束後先核對人員，再利用有限補給整備。離開的班機沒有辦法替小隊清除停機坪上的最後威脅，名冊也不能代替防線。四波全部解除後，地面完成回報才會送往遠端跑道；在那之前，周岑仍要替每一件留下的物資找到接收者，而灰線仍要照顧站在自己身邊的人。','Lin Yue orders personnel checked after each wave, followed by regrouping with the supplies available. The departing flight cannot clear the apron’s remaining threats for the squad, and a manifest cannot hold a perimeter. The ground completion report goes to the remote runway only after all four waves are cleared. Until then, Zhou Cen must find recipients for the supplies left behind, and Greyline must look after the people standing beside it.'),
      ],
      deploy:[
        r('lin','灰線，守住停機坪的四波攻勢。遠端班機等的是可靠回報，不是一句快好了。','Greyline, hold the apron through four attacks. The remote flight needs a reliable report, not a promise that we are nearly done.'),
        r('local','最後的載重表還在核對，我會把人與器材算清楚。請替地面留守者守住時間。','The final load sheet is still being checked. I will account for people and equipment properly. Keep time available for the ground staff staying behind.'),
      ],
      stages:[
        [r('chen','第一波正在接近停機坪，遠處也有火力。讓小隊保持掩護，不要全擠同一處。','First wave approaching the apron, with fire from farther out too. Keep the squad supported instead of crowding everyone into one position.'),r('shen','名冊的人數沒有錯，醫療器材卻還沒算進去。那一欄不能只寫成普通行李。','The passenger count is correct, but medical equipment has not been included. That entry cannot simply be called ordinary baggage.'),r('lin','先守住這一波，再讓通訊繼續核對。灰線，掩護正在換彈與換位的隊友。','Hold this attack so communications can finish the checks. Greyline, cover squadmates reloading and repositioning.')],
        [r('local','第二波開始前我核對了舊表，重量確實沿用第一批。不能讓錯帳跟著最後班機。','Before the second wave, I checked the old sheet. The weight really came from the first group. The last flight must not carry that error.'),r('chen','新表正在傳給遠端地勤，必要器材會和使用者一起列。沒有哪一行能隨手刪掉。','The new sheet is going to the remote ground crew. Essential equipment is listed with its users. No row can be casually erased.'),r('lin','注意機庫兩側的交叉火力，補給路線也要有掩護。別因為趕時間就分散小隊。','Watch the crossfire from both sides of the hangars, and cover access to supplies. Do not scatter the squad because time is short.')],
        [r('shen','第三波來了，還有器材需要重新安排接收。把不能省掉的需求說清楚，才有選擇。','Third wave incoming. Some equipment still needs a new recipient. Clear accounts of essential needs are what make choices possible.'),r('local','我的工具箱留在地面接收清單了，位置已經記下。這次我也照同一份規則簽名。','My toolbox is on the ground-collection list, and its location is recorded. This time I am signing under the same rules as everyone else.'),r('chen','載重表終於對上實際內容，遠端仍在等待地面確認。灰線，還有最後的防守。','The load sheet finally matches what is actually there. The remote crew still awaits ground confirmation. Greyline, we have one more defense to complete.')],
        [r('lin','最後一波，停機坪仍是我們的責任。不要只看遠方的班機，先顧好身邊的火力。','Final wave. This apron is still our responsibility. Keep your attention on the fire around you, not just the distant flight.'),r('local','留下的物資都有接收名冊了，人員也逐一確認。我不會再把地面寫成空白。','Every item remaining has a receiving list, and the personnel are checked individually. I will not leave the ground side blank again.'),r('chen','最後名冊已送達，遠端頻道等四波解除的回報。讓完成這兩個字真正有內容。','The final manifest is delivered. The remote channel awaits confirmation that all four waves are cleared. Make the word complete mean something.')],
      ],
      regroup:[
        [r('lin','第一波解除，先確認每個人的位置與彈匣。名冊能繼續整理，防線也還要有人守。','First wave cleared. Check everyone’s position and magazines. The manifest can continue, but someone still has to hold this line.'),r('shen','醫療清單已重新核對，沒有把人的需要刪掉。現在把有限補給用在真正需要的地方。','The medical list has been checked again without deleting anyone’s needs. Use our limited supplies where they are actually needed.')],
        [r('chen','第二波解除，舊重量已經從最後名冊撤下。這份回報可以交給遠端的人重新計算。','Second wave cleared. The outdated weight figures are off the final manifest. The remote crew can recalculate from this report.'),r('local','我正在替留下的器材找接收者，不再只寫延後。留在地面，也要有清楚的去處。','I am finding recipients for equipment staying here, not merely labeling it delayed. Remaining on the ground still requires a clear destination.')],
        [r('lin','第三波解除，最後一次攻勢還沒來完。整備好了再回到掩體，別先替任務畫句點。','Third wave cleared, but the last attack is still ahead. Regroup and return to cover; do not finish the mission in your head yet.'),r('chen','遠端地勤收到完整名冊，現在等最後防守確認。灰線，這一段回報還在你們手裡。','The remote ground crew has the complete manifest and is waiting for final defense confirmation. Greyline, that report is still ours to make.')],
      ],
      win:[
        b('第四波解除後，陳隼送出停機坪安全回報，遠端跑道隨後確認最後名冊已完成簽核。稍晚傳回的撤離消息來自地圖之外，小隊把留下的地面與留守工作一併交給接班人員。林岳、沈禾與陳隼的呼號都回應了清點，周岑則逐一念出仍需要接班的人。兩份名單在同一段通訊裡得到承認。','After the fourth wave, Chen Sun sends the apron’s security report. The remote runway confirms that the final manifest has been approved. The later evacuation update comes from beyond this battlefield; the squad hands the remaining ground and continuing work over to the next shift. Lin Yue, Shen He and Chen Sun all answer the personnel check while Zhou Cen reads the names still awaiting relief. Both lists are acknowledged in the same transmission.'),
        b('周岑沒有再詢問自己的工具箱能不能補上班機。他把接收位置和紀錄副本交給下一班，最後才承認放下那一箱比核對數字更難。沈禾說，留下的東西有了名字與去處，就不等於被丟棄。灰線在停機坪完成的守衛沒有消除所有取捨，卻讓這次取捨不必依靠一個人的物品比較容易被忽略來完成。','Zhou Cen does not ask whether his toolbox can still be added to the flight. He gives its receiving location and a copy of the records to the next shift, then admits that setting it down was harder than checking the figures. Shen He tells him that something with a name and destination is not simply discarded. Greyline’s defense has not removed every difficult choice. It has made the choice possible without relying on one person’s belongings being easier to overlook.'),
      ],
      costly:[
        b('停機坪最終守住了，遠端也確認收到完整名冊，但地面完成回報旁還附著人員狀況、受損掩體與待補物資的紀錄。那些項目不能因為撤離消息傳來就被刪去。周岑沒有立刻收起值班表，他把下一班需要接續的事情重新列在第一頁。最後班機的工作已經完成，灰線這一側的善後卻仍要有人承擔。','The apron ultimately holds and the remote crew acknowledges the complete manifest, but the ground report also records personnel conditions, damaged cover and supplies still needed. The evacuation update is no reason to erase those entries. Zhou Cen does not immediately put away the duty sheet; he moves the next shift’s tasks onto its first page. The final flight’s work is complete, but someone still has to take responsibility for the aftermath on Greyline’s side.'),
        b('這次守衛讓名冊上的人得到機會，卻消耗了地面防線原本有限的餘裕。通訊記錄要求後續接班同時帶來醫療與整備物資，而不是只派人來收工具箱。周岑終於懂得，公平不只是在最後載重表上簽得一致，也包括事情結束後仍願意看見留下的困難。完成與代價並排，才是這一天能留下的真實回報。','The defense gives the people on the manifest their chance, but consumes the ground perimeter’s limited margin. The communications log asks the incoming shift to bring medical and regrouping supplies, not merely someone to collect a toolbox. Zhou Cen finally understands that fairness means more than signing the last load sheet consistently: it also means continuing to see the difficulties left afterward. Completion and cost belong side by side in this day’s truthful report.'),
      ],
      loss:[
        b('停機坪未能完成四波守衛，最後的地面安全確認停在等待。遠端地勤只收到已核對的名冊，指揮部必須依照仍未解決的威脅重新安排撤離時程。沒有誰在頻道裡替那些等待的人保證結果，周岑也不再用座位還有空來安慰自己。數字已經修正，能讓數字變成實際機會的防線卻沒有守到最後。','The apron does not survive all four attacks, and the final ground security confirmation remains pending. The remote ground crew has the checked manifest, but command must revise the evacuation schedule around the unresolved threat. Nobody on the channel guarantees an outcome to those waiting. Zhou Cen no longer reassures himself that empty seats are enough. The figures are corrected; the line needed to turn those figures into an actual chance has not held to the end.'),
        b('後續回報把未完成的守衛、留下的器材與等待接班的人分開記錄，沒有用一個失敗標記把它們全部蓋過。灰線這次未能替最後班機送出完整確認，至少不能讓下一支小隊再次拿著舊重量開始。周岑保留兩份載重表，也保留那張地面接收清單。若有新的機會，起點必須是已經看清楚的現場。','The follow-up report separately records the unfinished defense, equipment remaining and personnel awaiting relief, rather than covering them with one failure mark. Greyline has not provided the final flight’s complete confirmation this time. At minimum, the next squad must not begin with the outdated weight figures again. Zhou Cen keeps both load sheets and the ground-collection list. Any new chance must begin with an accurate understanding of the situation.'),
      ],
    },
    assault:{
      brief:[
        b('停機坪防線、維修機庫與航管通訊台先後被敵軍占住，完整載重表無法穩定送往遠端地勤。灰線需要依序奪回三座據點，在附近威脅解除後保持佔領，讓每一段地面確認重新連起來。林岳不把班機的時間當作冒進的理由；周岑也知道，只要回報還有缺口，自己在載重表上的簽名就不能代替前線的確認。','Hostile troops occupy the apron line, service hangar and air traffic relay, preventing the complete load sheet from reliably reaching the remote crew. Greyline must recover the three positions in sequence and hold each once nearby threats are cleared, reconnecting every part of the ground confirmation. Lin Yue will not use the flight schedule to justify reckless advances. Zhou Cen knows his signature on the load sheet cannot replace a front-line report while gaps remain.'),
        b('沈禾已把必要醫療器材與使用者重新列在同一份資料，陳隼則保存舊重量與修正版本，等通訊台恢復確認後一併送出。小隊推進時要利用掩體、照顧側翼，並在有限整備中維持火力。三座據點不是三張互不相關的旗幟，它們連著一份足以讓遠方做決定的回報，也連著班機離開後還需要接班的人。','Shen He has relisted essential medical equipment together with its users. Chen Sun keeps both the old weights and corrected version, ready to send them once the relay can confirm receipt. As the squad advances, it must use cover, watch the flanks and preserve its firepower through limited regrouping. These are not three unrelated flags: they connect one report that people far away can use to make a decision, and the personnel still needing relief after the flight leaves.'),
      ],
      deploy:[
        r('lin','灰線，按順序奪回停機坪、機庫與通訊台。最後名冊需要一條能確認的回報線。','Greyline, recover the apron, hangar and relay in order. The final manifest needs a reporting line that can confirm receipt.'),
        r('chen','修正重量與地面接收清單都在我這裡。每座據點完成後，先確認消息確實送達。','I have the corrected weights and ground-collection list. After each position is secured, verify that its report actually arrives.'),
      ],
      stages:[
        [r('lin','第一座是停機坪防線，空地上的火力別硬穿。讓掩護的人看得見你的下一步。','The first position is the apron line. Do not push straight through fire on open ground. Let your cover team see where you are going.'),r('local','最後名冊的人數沒錯，重量還需要修正。遠端知道我們正在處理，不要催出假確認。','The final passenger count is correct, but the weights need correction. The remote crew knows we are working; do not rush out a false confirmation.'),r('shen','必要器材不能和普通行李混在一起刪掉。你們先奪回據點，我繼續核對需求。','Essential equipment must not disappear with ordinary baggage. Recover the position while I continue checking the needs.')],
        [r('chen','第二座是維修機庫，兩側可能有交叉火力。載重表已修正，還差完整的地面確認。','The second position is the service hangar, with possible crossfire from both sides. The load sheet is corrected; full ground confirmation is still missing.'),r('local','我的工具箱轉進地面接收清單，留下的位置已記好。誰的東西都用同一份標準。','My toolbox is transferred to the ground-collection list, with its location recorded. Everyone’s belongings use the same standard.'),r('lin','機庫附近的威脅解除才保持佔領，別把進度當成掩體。先讓小隊能穩定站住。','Hold capture only after threats around the hangar are cleared. Progress is not cover. First give the squad a position it can sustain.')],
        [r('chen','最後是航管通訊台，遠端頻道正在等完整確認。這次送出去的會是同一份新資料。','The final position is the air traffic relay. The remote channel awaits full confirmation. This time every recipient will receive the same corrected data.'),r('shen','留下的人員也列在交接清單，不會因為班機離開就消失。先把最後據點完成。','The people staying are on the handover list too. They will not disappear when the flight leaves. Complete this last position first.'),r('lin','灰線，最後一段路也要彼此掩護。清除附近威脅，再把完成回報確實送出去。','Greyline, cover one another along this final stretch. Clear the nearby threat, then send a completion report you can stand behind.')],
      ],
      regroup:[
        [r('lin','停機坪防線已確認，先整備再向機庫前進。完整回報比搶先一步更能幫到遠端。','The apron line is confirmed. Regroup before moving to the hangar. A complete report helps the remote crew more than being one step ahead.'),r('local','第一段確認收到了，我開始安排地面接收。留下的物資不會再只有一個延後字樣。','The first confirmation is received. I am arranging ground recipients. Supplies remaining here will have more than a delayed label.')],
        [r('chen','維修機庫已確認，最後名冊沒有再分成兩個版本。現在只等通訊台接續回報。','The service hangar is confirmed. The final manifest no longer has two conflicting versions. We need the relay to complete the reporting line.'),r('shen','現在處理傷勢與彈匣，最後據點還需要穩定火力。遠方的等待不能靠透支小隊解決。','Treat injuries and check magazines now. The last position still needs steady firepower. Exhausting the squad will not solve the waiting elsewhere.')],
      ],
      win:[
        b('航管通訊台得到佔領確認，陳隼將修正名冊與地面回報一併傳往遠端。最後班機的簽核消息隨後送回，稍晚的撤離進度則從另一條跑道回報。灰線小隊仍站在自己完成的三座據點之間，接班人依照清楚的紀錄，逐一接手已奪回的路段。林岳清點到三個完整回應，沈禾才把那份反覆核對的醫療清單收起。','Once the air traffic relay is confirmed captured, Chen Sun sends the revised manifest and ground report together. Approval for the final flight comes back, followed later by an evacuation update from another runway. Greyline remains among the three positions it secured; the next shift takes responsibility for the recovered sections one by one, guided by clear records. Lin Yue receives three complete answers to the personnel check before Shen He puts away the medical list she has checked so many times.'),
        b('周岑把工具箱接收單交給留守同事，沒有再讓熟人的物品躲進必要器材那一欄。陳隼留下兩份表格的差異紀錄，讓下一班知道為什麼這次必須重算。這場衝鋒奪回的除了地面據點，還有一份能被信任的決定。機場沒有因此變得空無一人，但誰離開、誰留下，以及誰要接續工作，終於都有清楚的名字。','Zhou Cen gives a staying coworker the toolbox’s receiving slip, without letting a familiar person’s possessions hide in the essential-equipment column again. Chen Sun leaves a record of the differences between the sheets so the next shift knows why the load had to be recalculated. This assault recovers ground positions and a decision others can trust. The airfield does not become empty, but who leaves, who stays and who must continue the work finally have clear names.'),
      ],
      costly:[
        b('三座據點全部確認，修正名冊也順利送達，地面回報卻無法只寫完成。整備與醫療需求，還有尚待核對的物資一併進入後續交接，提醒遠端這條通訊線是靠有限資源重新接起的。周岑沒有替工具箱安排優先接收，而是先要求下一班回覆前線仍需要的項目。公平在簽核之後，仍有一次真正的考驗。','All three positions are confirmed and the revised manifest gets through, but the ground report cannot simply say complete. Regrouping and medical needs, together with supplies awaiting verification enter the handover too, reminding the remote crew that this reporting line was restored with limited resources. Zhou Cen does not arrange priority collection for his toolbox; he first asks the next shift to respond to the front line’s outstanding needs. Fairness faces another real test after the signature.'),
        b('遠端的撤離回報帶來一段短暫安靜，停機坪與機庫的善後卻還沒有結束。通訊記錄把留下的人員與需要補充的物資繼續列著，不讓一架班機的成功遮住整片地面的代價。灰線把最後名冊送到了能做決定的人手裡，也留下了一份不能草草結案的紀錄。接班者需要接住兩者，才能真正延續這場勝利。','The remote evacuation report brings a brief quiet, but the work after the fighting on the apron and in the hangar is unfinished. The communications log continues to list remaining personnel and supplies needed, keeping one aircraft’s success from concealing the cost on the ground. Greyline delivered the final manifest to those able to decide and left a record that cannot be closed casually. The incoming shift must take responsibility for both to carry this victory forward.'),
      ],
      loss:[
        b('三座據點的確認沒有連成完整回報，遠端地勤只能繼續等待可靠的地面消息。最後名冊的重量已經修正，但它尚未得到所需的安全確認；指揮部因此重新評估時程，而不是把空出的座位當成撤離已完成的證明。周岑在值班表上標明哪些資料已核對，哪些路段仍未安全，沒有把兩種狀態混成一句差不多了。','The three position confirmations never become a complete report, leaving the remote ground crew waiting for reliable news. The final manifest’s weights are corrected, but the necessary security confirmation is still missing. Command therefore reassesses the schedule instead of treating empty seats as proof that evacuation is complete. Zhou Cen marks which data is verified and which route sections remain unsecured, without combining the two into a claim that things are nearly done.'),
        b('灰線的任務未能完成，修正後的清單卻仍被保存，留待下一次部署接續。地面接收者、必要醫療器材與還在等待的名字沒有隨戰場回報中斷而消失。這一次失去的是把資料送成完整確認的機會，不是把責任重新藏回舊帳的理由。若防線再被奪回，後來的人至少知道自己究竟還欠哪些人一段可靠回覆。','Greyline’s mission is incomplete, but the corrected lists remain available for another deployment. Ground recipients, essential medical equipment and the names still waiting do not vanish when the battlefield report breaks off. This time, the chance to turn the data into a complete confirmation is lost. That is no reason to hide the responsibility in the old figures again. If the line is recovered, the next people will know exactly whom they still owe a reliable reply.'),
      ],
    },
    cleanup:[
      r('chen','最後殘敵的即時位置已標記，距離與高低都可核對。別讓最後確認變成漫無目的搜尋。','The last enemies’ live positions are marked, with distance and elevation available. Do not turn the final confirmation into an aimless search.'),
      r('lin','灰線，按定位解除最後威脅，繼續掩護隊友。名冊已經準備好，就差完整地面回報。','Greyline, follow the tracking to clear the last threat and keep covering your squadmates. The manifest is ready; it needs a complete ground report.'),
    ],
    operationNotes:[
      b('停機坪壓制讓遠方火力輪流施壓，進場較慢卻更考驗準確射擊；陳隼提醒灰線，清楚辨認目標再回報命中。','Apron suppression alternates pressure from distant fire. Slower arrivals test accurate shooting; Chen Sun reminds Greyline to identify targets clearly before confirming hits.'),
      b('機庫突破讓成組敵軍從兩側逼近，後續重裝兵更需要集中處理；沈禾提醒小隊用掩護與手榴彈打開交戰空間。','Hangar breach sends grouped attackers from both sides, with later heavy troops requiring focused attention. Shen He reminds the squad to create room with cover and grenades.'),
      b('最後班機方案的攻勢切換最快，地面確認時程也更緊；林岳要求迅速推進或守住防線，但不省略最後威脅的核對。','Last flight switches attack lanes fastest and leaves a tighter ground-confirmation schedule. Lin Yue wants quick advances or a firm defense without skipping the final threat check.'),
    ],
    afterword:[
      b('機場後來的紀錄沒有只留下最後班機的時刻，還保留兩份載重表、地面接收單與小隊完成或未完成的回報。周岑的工具箱不再被列成必須同行的器材，也沒有因此失去主人。它留在一個能被找到的位置，旁邊寫著接收者的名字。對這一天而言，願意把留下的東西清楚交出去，已經是一種改變。','The airfield’s later record preserves more than the final flight’s time: both load sheets, the ground receiving slips and the squad’s complete or incomplete report remain. Zhou Cen’s toolbox is no longer classified as equipment that must travel, but that does not make it ownerless. It stays in a place where it can be found, beside its recipient’s name. For this day, being willing to hand over what remains clearly is already a change.'),
      b('灰線沒有替所有人的過去找到足夠大的行李艙。機甲離開以後，他們能做的是守住一段地面、奪回幾座據點，讓遠方收到可以信任的消息。最後班機讓一份名冊上的人繼續向前，留守清單則提醒接班者還有人需要回應。真正完整的撤離故事，應該同時記得這兩邊，而不是在一架班機離開時就把頁面合上。','Greyline never finds a baggage hold large enough for everyone’s past. After the mechs leave, it can hold a stretch of ground, recover a few positions and get trustworthy news to people far away. The final flight lets those on one manifest move onward; the staying list reminds the next shift that others still need an answer. A complete evacuation story remembers both sides instead of closing the page when one aircraft leaves.'),
    ],
  },
};
