// Independent northern-sector operations; neither mode requires another battlefield clear.
const B=(zh,en)=>({zh,en});
const R=(speaker,zh,en)=>({speaker,text:B(zh,en)});

export const NORTHERN_STORIES={
  pass:{
    title:B('山隘：最後一班車的燈','Mountain Pass: The Lights of the Last Convoy'),
    deck:B('機甲的履帶印還留在路面，最後的引擎聲卻已遠去。灰線小隊接下沒有鋼鐵巨人的山隘，替仍在隧道裡的人守住出口的路。','The mechs have gone, leaving track marks across the road. Greyline takes over the pass without their steel giants, keeping a route to the exit open for the people still inside the tunnel.'),
    timeLabel:B('撤離第六日・05:40','Evacuation Day Six · 05:40'),
    location:B('北嶺公路・鹿脊關隘與雙線隧道','North Ridge Road · Deerback Pass and the twin road tunnels'),
    background:[
      {title:B('一、巨人的尾燈','I. The Giants’ Rear Lights'),paragraphs:[
        B('凌晨三點，最後兩部機甲離開鹿脊關隘。它們的散熱器在霧裡像兩扇發紅的窗，山路上留下深而整齊的履帶印。撤離指揮部沒有把守軍撤走，只把任務改成步兵接替。林岳站在空下來的路肩，等引擎聲完全消失才看向灰線。他說，車走了，路還在；我們得讓後面的人也能走。','At three in the morning, the last two mechs left Deerback Pass. Their radiators glowed through the fog like red windows, their tracks cutting deep, orderly marks into the mountain road. Evacuation command kept the defenders in place and reassigned the sector to infantry. Lin Yue waited on the empty shoulder until the engines had faded before turning to Greyline. The machines had gone, he said, but the road remained. The people behind them still needed a way out.'),
        B('這條公路原本運送木材、郵件與週末旅客，現在每輛車都貼著手寫的目的地。車隊裡有病床改成的擔架、有塞在貨物之間的家犬，也有不肯離開學校名冊的老師。陳隼收到的清單比實際車輛少了七輛。沒有人知道是回報延誤，還是有人仍困在支路；在確認以前，隧道口不能被放棄。','The road once carried timber, post and weekend visitors. Now every vehicle bore a handwritten destination. The convoy carried hospital beds converted into stretchers, family dogs tucked between bundles, and a teacher who refused to leave without the school register. Chen Sun’s manifest listed seven fewer vehicles than the people at the tunnel had counted. Nobody knew whether the reports were late or families were still trapped on side roads. Until they knew, abandoning the tunnel entrance was out of the question.'),
      ]},
      {title:B('二、不能倒車的隧道','II. A Tunnel with No Room to Reverse'),paragraphs:[
        B('公路技師馬伯守著一本油污斑駁的維修簿。他知道哪段坡面排水最差，也知道隧道裡那輛過熱的巴士為何不能靠邊：另一線正在接收對向撤離的人流。引擎冷卻需要時間，時間卻不在任何倉庫裡。沈禾聽完他的說明，把原本留給自己的飲水交給後方醫療組，讓他們先照顧車廂裡的老人。','Road engineer Ma Bo kept an oil-stained maintenance ledger. He knew which stretches drained badly and why an overheated bus inside the tunnel could not pull aside: the second bore was taking evacuees coming from the opposite direction. Its engine needed time to cool, and time was the one thing no depot could supply. After hearing him out, Shen He handed the water she had kept for herself to the rear medical team. The elderly passengers needed it first.'),
        B('敵軍先遣隊在天亮前摸到山口，沒有鋼鐵機體替他們遮住身影。觀測記錄顯示，主路與兩側林徑都有人移動，後續部隊仍在向關隘靠攏。灰線可以選擇守住撤離口，讓車隊逐段通過；也可以沿公路路障、山腰哨站與通訊台推進，重建一條可用的補給線。兩種命令都只為同一群等待的人。','Enemy advance parties reached the pass before daylight, without armored machines to hide their movement. Observers reported activity on the road and both wooded trails, with more units approaching from behind. Greyline could hold the evacuation entrance while the convoy cleared the tunnel in sections, or push through the roadblock, hillside post and relay to restore a supply route. The two orders served the same people waiting on the other side.'),
      ]},
      {title:B('三、紙上沒有的重量','III. Weight Missing from the Manifest'),paragraphs:[
        B('陳隼終於查到多出的七輛車。那是一群自行併入車隊的居民，沒有通訊器，沿著路牌一路找到這裡。名冊上的空白因此變成了具體的名字。林岳聽到消息沒有笑，只把小隊間距再看了一次。他曾在另一條山路失去同袍，最怕的不是槍聲，而是有人以為自己已經替最後一批人守完了最後一班。','Chen Sun finally accounted for the seven unlisted vehicles. Their occupants had joined the convoy on their own, following road signs without radios until they reached the pass. Blanks on the manifest became names. Lin Yue did not smile at the news; he checked the squad’s spacing once more. He had lost comrades on another mountain road. What frightened him was the moment someone believed they had finished the final watch for the final group, when another family was still coming.'),
        B('馬伯說，等道路恢復，他想把那本維修簿留在收費亭，誰接班都能看懂。沈禾沒有回答道路何時會恢復，只問他的手為什麼一直抖。他說是冷，大家便讓這個答案暫時成立。灰線的命令不再是一條地圖上的灰線，而是一項很窄的承諾：今天經過這裡的人，至少不能因為守軍先放手而停下。','Ma Bo said that once the road reopened, he wanted to leave the ledger in the toll booth so whoever relieved him could understand it. Shen He did not promise when that would happen. She asked why his hands were shaking. He said it was the cold, and everyone let that answer stand for the moment. Greyline’s order had become a narrow promise rather than a mark on a map: those passing through today must not be stopped because the defenders let go first.'),
      ]},
    ],
    cast:[
      {id:'lin',name:B('林岳','Lin Yue'),role:B('班長・火線與隊形','Squad leader · fire lanes and formation'),detail:B('曾在公路撤退中失去同袍，說話總比別人慢半拍。他反覆確認掩體與小隊位置，並非不信任灰線，而是不願再把「應該安全」當成安全的證據。','He lost comrades during a retreat along a mountain road and speaks a beat slower than most. His repeated checks of cover and squad positions are not distrust of Greyline. He refuses to accept “probably safe” as evidence of safety again.')},
      {id:'shen',name:B('沈禾','Shen He'),role:B('軍醫・傷勢與生還者','Medic · casualties and survivors'),detail:B('她記得每個車廂裡需要藥物的人，也記得隊友有多久沒喝水。面對撤離清單，她先問誰還沒有被記下，而不是誰的名字已經可以劃掉。','She remembers who needs medicine in each vehicle and how long her teammates have gone without water. Faced with an evacuation list, she asks who has not yet been entered before asking whose name can be crossed off.')},
      {id:'chen',name:B('陳隼','Chen Sun'),role:B('通訊兵・車隊回報','Signals operator · convoy reports'),detail:B('第一次獨自整理前線頻道，習慣把每個數字重複念兩遍。他怕漏接車隊的回報，更怕錯誤的沉默被寫成「全數通過」，因此一直保留未確認的空格。','This is his first time managing the front-line net alone. He repeats every number twice, fearing a missed convoy report and the possibility that silence will be recorded as “all clear.” He keeps every unconfirmed entry visibly blank.')},
      {id:'local',name:B('馬伯','Ma Bo'),role:B('公路技師・後方聯絡','Road engineer · rear liaison'),detail:B('在這條路工作了三十年，熟悉每一處積水與坡度。他從後方回報車流與隧道狀況，手上的維修簿已經發黃，卻比許多新地圖更能說明這條路為何值得守。','He has worked this road for thirty years and knows every flooded bend and gradient. Reporting traffic and tunnel conditions from the rear, he carries a yellowing ledger that explains the road’s value better than many new maps.')},
    ],
    stakes:[
      B('隧道口一旦失守，過熱車輛與對向人流將無法按原定節奏撤離，後方必須重排整支車隊。','If the entrance falls, stalled vehicles and opposing evacuation traffic will lose their scheduled passage, forcing the rear to reorganize the entire convoy.'),
      B('三處據點連成可用公路後，藥品、燃料與確認名冊的消息才有穩定通道向後方傳遞。','Securing all three positions provides a reliable route for medicine, fuel and the reports needed to complete the evacuation manifest.'),
      B('小隊不是道路上最後需要被計入的人；每一名守軍生還，都能把這一天的真實經過帶回去。','The squad are also people who must be accounted for. Every surviving defender can carry an honest account of this day back to the rear.'),
    ],
    defend:{
      brief:[
        B('守衛命令要求灰線留在隧道撤離口一帶，抵擋四波敵軍，直到後方確認車流通過。敵人會沿主路與兩翼靠攏，不能只看正前方的柏油。林岳負責整理火線，陳隼持續接收後方回報；你們守住的是一段時間，不是一張永遠不會改變的地圖。','Greyline is ordered to hold around the evacuation entrance through four enemy waves, until the rear confirms the convoy’s passage. Attackers will use the road and both flanks; watching the asphalt ahead is not enough. Lin Yue organizes the squad’s fire lanes while Chen Sun stays on the rear net. You are holding a window of time, not an unchanging patch of ground.'),
        B('補給站就在撤離線旁，卻不是交火中的避難所。每次離開掩體前，先確認隊友是否仍能互相照應。波與波之間，車隊會得到短暫前進的空間，守軍也有整備機會；如果防線被突破，車輛不會因為清單上的字仍然完整就繼續前進。','The supply point stands beside the evacuation line, but it offers no refuge under fire. Before leaving cover, check that your teammates can still support one another. The pauses between waves give the convoy room to move and the squad a chance to regroup. If the line breaks, neat entries on a manifest will not keep the vehicles moving.'),
      ],
      deploy:[R('command','灰線，隧道車隊尚未通過。守住撤離口，四波攻勢結束前都算你們的班。','Greyline, the convoy is still in the tunnel. Hold the entrance. This remains your watch through all four waves.'),R('lin','機甲留下的掩體還能用。先看彼此的位置，再看遠處那條公路。','The cover left by the mechs is still useful. Check one another’s positions before watching the distant road.')],
      stages:[
        [R('chen','第一波進入公路，兩側也有移動回報。車隊仍在隧道裡，別讓人穿過防線。','The first wave is on the road; movement reported on both sides. The convoy is still inside. Keep the line closed.'),R('lin','主路交給正面火線，側翼有人就報位置。不要四個人一起轉向同一棵樹。','Keep a firing lane on the road and call flank positions. All four of us must not turn toward the same tree.'),R('shen','後方說巴士已經降溫，但還不能出發。每守住一分鐘，他們就少等一分鐘。','The bus has cooled, but the rear cannot move it yet. Every minute we hold is one less minute they must wait.')],
        [R('lin','第二波會找上一波沒走通的路。看看護欄之外，小徑不是空白地帶。','The second wave will seek a route the first failed to use. Watch beyond the guardrails; the trails are not empty.'),R('chen','後車回報已經靠近隧道中段，前車仍在等待。這一波過後才有新的通行空間。','The last vehicles are nearing the middle of the tunnel; the front still waits. Clearing this wave will give them room.'),R('shen','我聽見你們的呼吸都變重了。留意護盾和傷勢，別把還能站著當成沒有受傷。','All of you are breathing harder. Watch shields and injuries; still standing does not mean you are unhurt.')],
        [R('chen','第三波接近，後方名冊已核對完七輛增列車。現在沒有人能被當成漏報的數字。','Third wave approaching. The seven added vehicles are accounted for. Nobody can be dismissed as a missing number now.'),R('lin','他們還在試探我們的間隙。守好通往撤離口的路，遠處的動靜交給交叉掩護。','They are still probing our gaps. Guard the approaches to the entrance and cover distant movement with crossing lanes.'),R('local','車隊頭車看見出口了，我正在後方核對間距。你們那邊再撐住這一段。','The leading vehicle can see the exit. I am checking spacing from the rear. Hold your stretch a little longer.')],
        [R('command','第四波是本次守衛的最後攻勢。清除已進場敵軍前，隧道撤離口仍不能交出去。','The fourth wave is the final attack of this defense. Until its deployed troops are cleared, the entrance remains yours.'),R('chen','後車已到出口前的彎道。我不會先報全數通過，等最後一輛真的過線再說。','The last vehicles are at the bend before the exit. I will report everyone through only when the last one crosses.'),R('lin','最後一波也照規矩打。留住隊形，留住耐心，別在快結束時把彼此丟下。','Fight the final wave with the same discipline. Keep formation and patience; do not leave one another behind at the end.')],
      ],
      regroup:[
        [R('chen','第一波清了，車隊開始分段前進。我會盯著回報，下一波來之前先整理你們的狀態。','First wave cleared; the convoy is moving in sections. I will watch the reports. Check your condition before the next attack.'),R('lin','有人替你看路，才輪得到你整理裝備。分開整備，不要讓整條火線同時安靜。','Only service your gear when someone covers your lane. Take turns; the whole line must not go quiet together.')],
        [R('shen','第二波結束。後方仍有車輛等待，現在能處理的小傷，就不要留到下一次交火。','Second wave cleared. Vehicles still wait behind us. Deal with minor injuries now instead of carrying them into the next fight.'),R('local','隧道裡的車燈又動起來了。不是都走完了，但每輛車現在都知道該往哪裡去。','The lights inside the tunnel are moving again. They are not all through, but every driver now knows where to go.')],
        [R('chen','第三波清除，名冊上的最後一組正在移動。還有一波，別讓回報比現實先結束。','Third wave cleared; the final group on the manifest is moving. One wave remains. Our report must not finish before reality does.'),R('lin','把能用的掩體再看一次。我們離收班很近，也正是最容易忽略側翼的時候。','Check the usable cover again. We are close to the end of our watch, and that is when a flank is easiest to miss.')],
      ],
      win:[B('最後一輛巴士的尾燈在隧道另一端縮成兩個小點，馬伯才在維修簿旁寫下通行時間。陳隼逐一讀完名冊，第一次沒有把數字重複第二遍。七輛曾經漏列的車也有了去處，後方逐車確認接收，這一次回報和現實終於重合，沒有誰被留在表格之外。','Only when the final bus’s lights dwindled into two distant points did Ma Bo record its passage beside his maintenance notes. Chen Sun read every name once and, for the first time, did not repeat the numbers. The seven vehicles omitted from the earlier list now had destinations too. The rear confirmed each arrival. This time the report and the world finally matched, with nobody left outside the columns.'),B('林岳沒有宣佈英雄式的勝利，只說可以收班了。沈禾把剩下的飲水放回背包，再確認灰線和另外兩人的狀況。路面上的機甲履帶印仍然清楚，但今日讓車輛穿過山口的，是一群能彼此叫出名字的人；他們帶著完整的回報離開，也把下一班需要的路況留下。','Lin Yue offered no heroic declaration, only that their watch was over. Shen He put the remaining water back in her pack and checked Greyline and the other two again. The mech tracks were still clear on the road, but today the convoy had crossed because of people who knew one another’s names. They left with a complete account of the watch and left the next squad the road conditions it would need.')],
      costly:[B('車隊通過了，後方接收的回報卻不能只填上任務完成。交戰期間留下的醫療紀錄、守軍狀態與受損工事都要逐項核對，通行名冊後還有一份需要繼續追查的回程表。車流獲得了時間，支撐這段時間的人與物資也必須得到完整交代，不能被成功兩字蓋住。','The convoy passed, but the rear could not enter only mission complete on the report. Medical notes made during the fighting, defender status, and damaged positions all needed checking. Behind the passenger manifest lay a return sheet that still required follow-up. Traffic had gained time; the people and supplies that had bought it deserved a full accounting rather than being hidden beneath the word success.'),B('林岳在交戰前留下的值勤筆記寫著，公路不會記得守軍，所以人得記得。馬伯把那句話抄在維修簿旁，另列出補修、接收和重新點名所需的時間。灰線的防線完成了守衛，後方卻還有漫長的善後；每個名字都依確認的狀態登記，沒有被當成可以省略的代價。','In a duty note written before the fighting, Lin Yue had said that roads would not remember their defenders, so people must. Ma Bo copied the sentence beside his maintenance ledger and listed the time needed for repairs, reception, and another roll call. Greyline’s line had completed its watch, but the rear still faced a long aftermath. Every name was entered according to its confirmed status, never treated as an expendable cost.')],
      loss:[B('撤離口下一次安全確認沒有依計畫抵達，後方暫停原定通行，重新核對還在等待的車輛。馬伯把發車時刻一筆筆劃掉，卻沒有把人名劃掉。守衛任務沒能完成，那些乘客仍然需要可靠的去處；值勤表上的空白因此成了必須重新處理的危險，不能用一句撤退帶過。','The next safety confirmation from the entrance did not arrive as planned. The rear suspended the scheduled passage and checked the vehicles still waiting. Ma Bo crossed out departure times but left every name intact. The defense had not been completed, and those passengers still needed a reliable destination. The blanks in the duty sheet now represented dangers to be dealt with again, not something a single word such as withdrawal could resolve.'),B('後方收到的交戰紀錄裡，林岳曾要求接班的人先核對隧道名冊，沈禾則將當時能確認的傷情記得很清楚。這些文字只證明那一刻的狀況，不能代替現在的點名。新的接收人員把尚未確認的項目保留，繼續追查守軍與乘客，讓這次失敗不再多吞掉一個名字。','The combat record received at the rear contained Lin Yue’s earlier instruction to check the tunnel manifest first, and Shen He’s careful notes on injuries confirmed at that moment. Those words established only the conditions then; they could not replace a roll call now. The receiving staff kept uncertain entries open and continued tracing defenders and passengers, so this failure would not swallow another name.')],
    },
    assault:{
      brief:[B('推進命令讓灰線從關隘後側進場，依序奪下公路路障、山腰哨站與關隘通訊台。三處位置各自控制一段路，任何一處仍受威脅，車隊與補給就無法把零碎的安全連成通道。這是另一種守路的方法：把敵軍從道路前方逼退，而不是留在出口等待。','The advance order brings Greyline in from the rear of the pass to secure the roadblock, hillside post and relay in sequence. Each position governs a separate stretch; while one remains threatened, isolated safe patches cannot become a route for the convoy and supplies. This is another way of holding the road: pushing attackers back from what lies ahead instead of waiting at the exit.'),B('到達目標不等於拿下目標。先處理附近的敵軍與預定進場部隊，再於目標區按住佔領，讓後方有可信的據點回報。林岳會跟上灰線的推進節奏，沈禾盯著傷勢，陳隼將每次確認送出；沒有人需要為了趕時間，假裝眼前的危險已經結束。','Reaching a position is not the same as securing it. Deal with nearby hostiles and scheduled arrivals, then hold capture in the objective area so the rear receives a report it can trust. Lin Yue matches Greyline’s pace, Shen He watches the squad’s injuries, and Chen Sun transmits each confirmation. Speed does not require anyone to pretend the danger has ended.')],
      deploy:[R('command','灰線，這次採用關隘推進線。先奪公路路障，再往山腰哨站與通訊台前進。','Greyline, take the advance route through the pass: roadblock first, then the hillside post and relay.'),R('local','我從後方回報道路狀況。你們拿下的是路段，不是帳本上可以先填好的空格。','I will report road conditions from the rear. You are securing real stretches, not blanks we can fill in early.')],
      stages:[
        [R('lin','第一個目標是公路路障。先留意兩側能接近目標的地方，再找適合停留的掩體。','First objective: the roadblock. Watch both side approaches before choosing cover from which to hold.'),R('shen','這裡離後方近，也最容易讓人急著往前。別把第一處傷勢帶成後面兩處的負擔。','This position is close to the rear, which makes haste tempting. Do not let an early injury burden the next two sectors.'),R('chen','我已標出路障位置。附近敵軍還在時，後方不會把靠近目標當成安全回報。','Roadblock marked. While hostiles remain nearby, the rear will not treat reaching it as an all-clear report.')],
        [R('chen','第二個目標在山腰哨站，路線轉向側翼。前一處安全，不代表前面這一段也安全。','Second objective: the hillside post, off to the flank. The road behind us is secure; that says nothing about this stretch.'),R('lin','上坡時別只望著通訊台。哨站兩邊都能出現敵人，先把眼前的交叉火線整理好。','Do not stare at the relay while climbing. Either side of the post may hold attackers. Establish our crossing fire lanes first.'),R('local','後方已把下一批車流列入準備。哨站的確認回報，會決定他們能否繼續靠前。','The next vehicles are being readied at the rear. Confirmation from the post will decide whether they can move closer.')],
        [R('lin','最後目標是關隘通訊台。還沒有拿下以前，我們就沒有完整的一條補給路。','Final objective: the pass relay. Until it is secured, we still do not have a continuous supply route.'),R('chen','我能聽見後方頻道了，但收到聲音不等於位置安全。先清除威脅，再確認據點。','I can hear the rear net, but a working signal does not make the position secure. Clear the threat, then confirm the sector.'),R('shen','最後一段也把彼此帶上。後方需要道路，但我還得把你們的名字一起交回去。','Bring one another through the final stretch. The rear needs the road, and I still need to return all your names.')],
      ],
      regroup:[
        [R('chen','公路路障已確認，第一段回報送出。下一處是山腰哨站，我會繼續盯著兩翼消息。','Roadblock confirmed; first report sent. The hillside post is next. I will keep listening for movement on both flanks.'),R('lin','先把隊形整理好再上坡。下一個目標不會因為我們剛拿下一個就變得容易。','Re-form before climbing. The next objective does not become easier just because we secured the first.')],
        [R('local','山腰哨站的消息收到，車隊可以再往前等。剩下通訊台，整條路才算真正接上。','Hillside post confirmation received. The convoy can wait farther forward. The relay will complete the route.'),R('shen','兩處目標已經拿下，還有一處。檢查傷勢與裝備，現在仍然是作戰，不是返程。','Two positions secured, one left. Check injuries and equipment. We are still fighting; we are not on the way home yet.')],
      ],
      win:[B('三處據點的確認按順序抵達後方，馬伯終於把分成數段的路況表放在一起。新的車隊時刻沒有誰先被劃掉，只有哪些車可以先動。陳隼看著完整的通道回報，知道那不是一條憑空畫出的線；每段都寫明確認時間，也讓等待的司機第一次能把引擎聲當成出發的訊號。','The three confirmations reached the rear in order, and Ma Bo laid the separate road reports together. The new timetable listed who could move first rather than who had to be crossed out. Chen Sun looked at the continuous route and knew it was more than a line drawn on a map. Every stretch carried its confirmation time, and the waiting drivers could finally hear their engines as a signal to depart.'),B('林岳在通訊台附近停下來，讓每個人有時間聽見後方的回覆。沈禾把灰線的狀況補進紀錄，然後才收起筆。這段公路重新成為一條能用的路，而小隊不必靠忘記剛才發生的事才能離開；四個呼號都得到回答，接班紀錄也保留了每一處需要留意的轉彎與視線。','Lin Yue halted near the relay long enough for everyone to hear the rear’s reply. Shen He entered Greyline’s condition before putting away her pen. The pass had become a usable road again, and the squad did not need to forget what had happened in order to leave it. All four callsigns answered. The handover also preserved every bend and line of sight that the next watch would need to treat carefully.')],
      costly:[B('公路被奪回，戰後回報卻不是一列整齊的勾號。交戰中留下的守軍狀態與醫療紀錄，和三處據點的確認一起送到後方，接收人員另列需要追查的項目。馬伯依據實際通行條件安排車流，也替善後留下空間，沒有把守軍和耗盡的物資算進可以省略的部分。','The road was retaken, but the report was not a tidy column of ticks. Defender status and medical notes recorded during combat reached the rear alongside the three sector confirmations, and the receiving staff listed matters requiring further checks. Ma Bo organized traffic according to the actual passage conditions and left room for the aftermath, without treating the defenders or depleted supplies as details that could be omitted.'),B('戰前的通訊備忘曾列出兩個時間：下一班車何時抵達，以及守軍何時能獲得接替。後方現在把第二項重新核對，讓道路開通之後的人員狀態也有去處。灰線完成了命令，任務的句號卻沒有讓傷情、裝備損失和未完的名冊自行消失，這些仍要由接收單位一項項承擔。','The prebattle communications note had listed two times: when the next convoy would arrive, and when the defenders could receive relief. The rear now checked the second again, giving the squad’s status a destination after the road opened. Greyline had completed the order, but the mission’s final full stop did not make injuries, equipment losses, or unfinished lists disappear. The receiving units still had to take responsibility for each.')],
      loss:[B('尚未完成的據點確認留在頻道上，補給路沒有連成可以信任的完整通道。馬伯取消原定發車時刻，讓車隊留在後方重新等待路況。人們還看得見公路，卻不能因為看得見就相信自己能通過；已經確認的路段也保留時間標記，免得一份過期消息把下一班帶進同樣的危險。','The unfinished sector confirmations remained on the net, and the supply road had not become a complete route that could be trusted. Ma Bo cancelled the departure time and kept the convoy at the rear awaiting new conditions. People could still see the road, but sight alone could not promise passage. Even the confirmed stretches retained their timestamps, so an outdated report would not lead the next watch into the same danger.'),B('交戰期間陳隼留下的通訊紀錄，把當時已核對與尚未安全的位置分得很清楚，沒有用含糊的成功替誰遮掩。後方依據這份有限的證據安排下一次確認，也重新追查所有守軍的狀態。灰線沒能完成推進，真實紀錄仍然有用，因為接班的人需要知道空白在哪裡，而非聽見漂亮的回報。','The communications record Chen Sun made during the fighting clearly separated positions checked at that time from those still unsafe, without hiding anyone’s failure behind vague success. The rear used that limited evidence to plan another confirmation and trace every defender’s status again. Greyline had not completed the advance, but the honest record still mattered: the next watch needed to know where the blanks were, rather than hear an attractive report.')],
    },
    cleanup:[R('chen','最後少數敵軍已定位，紅色標記會繼續更新。沿能通行的路接近，別為找人散掉隊形。','The final hostiles are located; red markers will keep updating. Use passable routes and keep the squad together.'),R('lin','我們不用再猜他們去了哪裡。看定位、看掩體，清完這幾個人再向後方報結束。','We no longer have to guess where they went. Check markers and cover; report the end only after these hostiles are cleared.')],
    operationNotes:[
      B('隧道封鎖把主要壓力放在公路。較快補給不代表能放任突破，林岳要的是一條始終有人照看的撤離線。','Tunnel Blockade concentrates pressure on the road. Faster resupply does not excuse breaches; Lin Yue needs the evacuation line watched throughout.'),
      B('山徑包抄讓較少敵軍從兩翼反覆接近。陳隼提醒，總數下降不代表危險下降，側翼回報仍要逐次確認。','Mountain Pincer sends fewer troops repeatedly down both flanks. Chen Sun warns that lower numbers do not mean lower danger; every flank report still needs confirmation.'),
      B('車隊急行留給敵我雙方的間隔都更短。沈禾不要求灰線追逐漂亮時刻，只要求速度不能把同袍留在路邊。','Convoy Sprint shortens everyone’s intervals. Shen He asks Greyline to keep pace without leaving comrades at the roadside for the sake of an impressive time.'),
    ],
    afterword:[
      B('戰後檔案裡，鹿脊關隘只佔了很短一頁：部隊、時刻、道路狀態與傷情。馬伯在另一張紙背面畫了一輛巴士，窗裡的人沒有臉，只有座位上的小小圓點。他說這樣才畫得下。陳隼把那張紙和名冊放在一起，沒有替它補上任何戰果。','In the after-action archive, Deerback Pass occupied a short page: units, times, road status and injuries. On the back of another sheet Ma Bo drew a bus. Its passengers had no faces, only small dots in their seats; he said that was the only way they would all fit. Chen Sun filed the drawing with the manifest without adding a combat claim.'),
      B('機甲離開後，山口沒有立刻恢復安靜。風仍會穿過護欄，輪胎仍會壓過碎石。灰線小隊知道自己沒有結束整場戰爭，只曾在一段公路上把等待變成通行。日後有人問鋼鐵的黃昏裡還剩什麼，他們可以回答：剩下守完一班的人，和終於走完那一段的人。','The pass did not become quiet after the mechs left. Wind still crossed the rails and tires still ground the gravel. Greyline knew they had not ended the war. On one road, they had turned waiting into passage. If someone later asked what remained in iron’s twilight, they could answer: the people who completed their watch, and the people who finally completed that stretch of road.'),
    ],
  },
  city:{
    title:B('山城：廣場上的空床','Hillside District: The Empty Beds in the Square'),
    deck:B('山城醫療站的床位清單每天都在變長。當機甲撤出街區，灰線接下狹窄街口與開闊廣場，替一座還有人生活的城保住出口。','The clinic’s bed list grows each day. With the mechs gone, Greyline takes over the narrow intersections and open square, preserving an exit from a city where people are still trying to live.'),
    timeLabel:B('撤離第六日・07:15','Evacuation Day Six · 07:15'),
    location:B('霧川山城・舊街區與廣場醫療站','Mistwater Hillside City · Old Quarter and the square clinic'),
    background:[
      {title:B('一、鐘樓沒有報時','I. A Clock Tower That No Longer Tells Time'),paragraphs:[
        B('霧川山城的鐘樓在第三次停電後停在七點十四分，居民仍照著它約定集合位置。機甲撤離時，巨大的腳步震落老屋窗框上的灰，卻沒有帶走門口晾著的衣服。林岳把街區圖攤在一張廢桌上，發現標成空屋的地方仍有炊煙。地圖畫出了道路，沒有畫出人為何仍不肯離開。','After the third power cut, Mistwater’s tower clock stopped at fourteen minutes past seven. Residents still used it to arrange meeting places. When the mechs withdrew, their heavy steps shook dust from old window frames but left the washing hanging outside. Lin Yue spread the district map on a discarded table and found smoke rising from buildings marked empty. The map showed roads, but not why people still refused to leave.'),
        B('廣場醫療站原本只是市場旁的社區診所。廖婉和幾位居民把課桌、門板與倉庫貨架排成床位，接住來不及送往後方的人。她的名冊分成能坐車、需要平躺與尚待評估三欄，三欄都比昨天更長。沈禾看到其中一張空床上留著一雙鞋，才知道有人已被送走，家屬卻還沒有回來取。','The square clinic had once been a community practice beside the market. Liao Wan and several residents turned school desks, doors and storage shelves into beds for people who could not reach the rear in time. Her list had three columns: able to sit, needing a stretcher, and awaiting assessment. All three were longer than yesterday. Shen He found shoes beside an empty bed and learned the patient had left, while their family had not yet returned to collect them.'),
      ]},
      {title:B('二、每條巷子的另一端','II. The Other End of Every Alley'),paragraphs:[
        B('敵軍進入外圍街道後，撤離車流改用狹窄的舊城巷道。巷子可以擋住遠處的火線，也可能把車輛與人潮一起卡在轉角。陳隼收到不同街口的回報，有人說已經清空，有人說還有住戶躲在樓內。廖婉要求先把兩份消息分開寫：清空道路不是清空房子，更不能把還沒聯絡上的人當成已經離開。','As enemy troops entered the outer streets, evacuation traffic shifted into the narrow old-quarter alleys. An alley could block distant fire, or trap vehicles and pedestrians at a bend. Chen Sun received conflicting reports: one intersection was clear, yet residents remained inside nearby buildings. Liao Wan asked him to record these separately. A clear road did not mean empty homes, and people who had not answered could not simply be counted as having left.'),
        B('灰線接到兩份可選命令。一份守住廣場醫療站周邊的撤離線，抵擋四波攻勢；另一份沿街口路障、中央廣場與街區指揮所推進，替後方重新整理通道。這不是兩個互相等待的戰役階段，而是同一個上午能採取的不同辦法。小隊選哪一條，廖婉都得繼續把傷員名字寫清楚。','Greyline received two alternative orders: defend the evacuation line around the square clinic through four waves, or push through the street barricade, central square and district command to reopen a route for the rear. These were different approaches available that morning, not campaign stages dependent on one another. Whichever the squad chose, Liao Wan still had to keep an accurate list of the wounded.'),
      ]},
      {title:B('三、留給回來的人','III. Something for Those Who Come Back'),paragraphs:[
        B('沈禾問廖婉，為什麼還把空床上的鞋留著。她說，醫療站收走一個人以後，街區會有很多人以為那個人就不見了；留一件東西，回來尋找的家屬才知道這裡曾接住他。林岳把一張歪斜的椅子推回桌旁，沒有參與談話。陳隼後來發現，他也把自己的姓名牌重新擦乾淨了。','Shen He asked why Liao Wan kept the shoes beside the empty bed. Once a patient left a clinic, Liao said, neighbors often assumed that person had vanished. Leaving something behind told a returning family that someone here had cared for them. Lin Yue straightened a chair without joining the conversation. Later, Chen Sun noticed he had cleaned his own identification tag as well.'),
        B('街區的危險不是只有哪扇窗後可能出現敵人。前方的每次失守，都會把後方已排好的等待重新推倒。廖婉沒有請灰線保證整座城一定得救，只請他們把真正安全的地方說清楚，把仍有危險的地方也說清楚。她說醫療站最不能接受的不是壞消息，而是來得太晚的壞消息。','Danger in the district was not merely a possible enemy behind a window. Every position lost ahead overturned the arrangements already made behind it. Liao Wan did not ask Greyline to guarantee the whole city’s rescue. She asked them to be precise about what was safe and what was not. The clinic could cope with bad news, she said; what it could not cope with was bad news arriving too late.'),
      ]},
    ],
    cast:[
      {id:'lin',name:B('林岳','Lin Yue'),role:B('班長・街口交叉掩護','Squad leader · intersection cover'),detail:B('他不喜歡在看不清的轉角許下保證，卻會把每個能照看隊友的位置記住。看見醫療站的空床後，他開始在回報安全之前，多問一次還有沒有被忽略的人。','He will not promise safety around an unseen corner, but remembers every position from which a teammate can be covered. After seeing the clinic’s empty beds, he begins asking who might have been missed before reporting an area safe.')},
      {id:'shen',name:B('沈禾','Shen He'),role:B('軍醫・醫療站聯絡','Medic · clinic liaison'),detail:B('熟悉後方醫療流程，也知道流程遇到太多傷員時會變得多脆弱。她與廖婉交換傷情回報，把守軍的疲勞與居民的等待放進同一份現實，而不是互相競爭的數字。','She knows rear medical procedures and how fragile they become under too many casualties. Exchanging reports with Liao Wan, she treats the defenders’ exhaustion and residents’ waiting as part of one reality, rather than competing statistics.')},
      {id:'chen',name:B('陳隼','Chen Sun'),role:B('通訊兵・街區狀態確認','Signals operator · district status'),detail:B('密集建築讓許多回報只剩片語，他學會先確認地點再確認人名。每次送出據點安全消息，都會把範圍說清楚，避免後方把一個街口的安全誤認成整座城的安全。','Dense buildings reduce many reports to fragments. He learns to confirm the location before the name, and defines the limits of every secured sector so the rear never mistakes a safe intersection for a safe city.')},
      {id:'local',name:B('廖婉','Liao Wan'),role:B('診所護理員・後方醫療組','Clinic nurse · rear medical team'),detail:B('在舊街區長大，記得病人的地址往往比病歷號碼快。她留在後方統整醫療與撤離回報，沒有要求守軍承諾奇蹟，只要求送來的消息足夠真實，讓下一個人還來得及作決定。','Raised in the old quarter, she remembers addresses faster than case numbers. She coordinates medical and evacuation reports from the rear, asking no miracles of the defenders—only information honest enough for the next person to act in time.')},
    ],
    stakes:[
      B('醫療站的撤離時間一旦被打亂，不能步行的傷員就會承受比一般車流更難挽回的延誤。','If the clinic’s evacuation window collapses, patients unable to walk will face delays far harder to recover from than ordinary traffic.'),
      B('街口、廣場與指揮所各代表一段可靠通道；據點回報的真實程度，直接決定後方如何安排下一批人。','The intersection, square and command position each represent a usable stretch. The accuracy of their reports determines how the rear schedules the next group.'),
      B('守軍也必須有人照應。讓小隊全員生還不是附帶的榮耀，而是醫療站不再多添幾張空床的可能。','The defenders need care too. Keeping the squad alive is more than an honor; it means the clinic may not have to account for more empty beds.'),
    ],
    defend:{
      brief:[B('守衛戰把灰線留在廣場醫療站的撤離線附近。四波敵軍會從街口與側巷逼近，建築遮住視線，也讓火線在轉角突然重疊。不要因為正面安靜就把小隊都拉向同一側；醫療站需要一條持續有人照看的防線，讓後方能照原定次序安排等待的人。','The defense order keeps Greyline near the clinic’s evacuation line. Four waves will approach through streets and side alleys. Buildings hide movement and bring firing lanes together abruptly at corners. Quiet ahead is no reason to pull the entire squad to one side. The clinic needs a continuously watched line so the rear can maintain the evacuation order.'),B('沈禾仍隨小隊守住火線，廖婉從後方回報傷員與車流。廣場上的等待由後方醫療組接手，灰線必須讓這些安排有可依靠的時間：守住撤離線、清除每波進場敵軍，並在下一次攻勢前整理裝備與傷勢。成功的回報不能比眼前的戰況先抵達。','Shen He stays with the squad at the firing line while Liao Wan reports patients and traffic from the rear. The rear medical team handles those waiting in the square. Greyline must give their arrangements a dependable window: hold the evacuation line, clear each deployed wave, and check equipment and injuries before the next attack. A report of success must never arrive before the fighting actually allows it.'),
      ],
      deploy:[R('command','灰線，廣場醫療站仍在等待撤離。守住街區防線，四波進場敵軍都必須清除。','Greyline, the square clinic is awaiting evacuation. Hold the district line and clear all four deployed waves.'),R('local','我會從後方回報傷員名冊。你們只要把安全的範圍說清楚，我就能接著安排。','I will report the patient list from the rear. Tell me exactly what is safe, and I can make the next arrangements.')],
      stages:[
        [R('chen','第一波已從外圍街口進場，側巷同樣有動靜。醫療站的名冊還沒有停止增加。','The first wave is entering from the outer streets, with activity in the alleys too. The clinic list is still growing.'),R('lin','先守住通向撤離線的路。轉角看不清就報位置，別讓一個街口吃掉整支小隊。','Guard the approaches to the evacuation line. Call unseen corners; one intersection must not swallow the whole squad.'),R('shen','廖婉已接上後方頻道。她那邊有人等車，我這邊要先確認你們都還跟得上。','Liao Wan is on the rear net. Her people are waiting for transport; I first need to know all of you can keep up.')],
        [R('lin','第二波會試兩翼的間隙。有人轉向側巷時，正面仍要留得住一條火線。','The second wave will test the flanks. When someone watches an alley, keep a firing lane covering the street.'),R('local','第一批平躺傷員正在後方整理上車順序。別急著報安全，我會等你們確認。','The rear is organizing the first stretcher patients for transport. Do not rush an all-clear; I will wait for confirmation.'),R('chen','我把每個回報的街口都分開記了。這裡安靜，不代表隔壁轉角也安靜。','I have separate entries for each intersection. Quiet here does not mean quiet around the next corner.')],
        [R('shen','第三波到了，大家的傷勢不會因為換了一波就消失。能用掩體就別只靠護盾。','The third wave is here. Our injuries do not disappear when the wave changes. Use cover instead of relying on shields alone.'),R('chen','後方醫療車已開始分批移動，還有一組正在等。撤離線仍然不能讓敵軍穿過。','Medical vehicles are moving out in groups; another still waits. Hostiles must not cross the evacuation line.'),R('lin','留意遠近兩層的火線。不要只追最近的人，放掉真正朝醫療站靠近的那一組。','Watch both near and distant firing lanes. Do not chase the closest attacker while another group moves toward the clinic.')],
        [R('command','第四波是本次守衛最後一波。醫療站需要可靠的結束回報，不能只說槍聲變少了。','The fourth wave is the final attack. The clinic needs a confirmed ending, not merely a report that the firing has diminished.'),R('local','最後一組的床位已核對完，我在等你們的確認。每個名字後面，都有人等著接。','The final group’s beds are accounted for. I am waiting on your confirmation. Someone is ready to receive every person listed.'),R('lin','按原來的規矩守到最後。廣場很大，但我們今天不能把彼此的照應留成空白。','Keep the same discipline to the end. The square is broad; we cannot leave gaps in how we cover one another.')],
      ],
      regroup:[
        [R('chen','第一波清除，醫療站已收到這段時間的確認。先整理狀態，下一波還會從街口來。','First wave cleared; the clinic has our confirmed window. Regroup now. Another attack will come through the streets.'),R('shen','傷勢回報給我，街口交給看守的人。現在不是誰能忍痛比較久的比賽。','Report injuries to me and leave the streets to whoever is covering them. This is not a contest in enduring pain.')],
        [R('local','第二波結束的消息收到了，前一批已經開始離開。空出的床位，還有人需要接著用。','Second-wave confirmation received; the previous group is leaving. Others still need the beds being freed.'),R('lin','輪流整理裝備，別讓所有人同時看自己的槍。巷子那一頭不會替我們看路。','Service gear in turns. We cannot all stare at our weapons; nobody beyond the alley will watch our approaches for us.')],
        [R('chen','第三波清了，還有最後一波。我保留著未完成欄位，等你們真的把它打完。','Third wave cleared; one remains. I am leaving its entry unfinished until we have actually cleared it.'),R('shen','能站著的人也檢查一次傷勢。後方還需要時間，我們不能把最後這段全押在運氣上。','Those still standing should check their injuries too. The rear needs more time; we cannot stake the final stretch on luck.')],
      ],
      win:[B('醫療站最後一組撤離名冊被後方接收時，廖婉把那雙鞋裝進寫有姓名的袋子。她沒有說整座山城已經安全，只說今天需要離開這個廣場的人，終於得到一段能通行的時間。接收單位回覆了每張病床的去處，袋上的姓名也終於有了能寄到的地址，等待不再只有一張空椅子。','When the rear accepted the final evacuation list, Liao Wan put the shoes into a bag marked with their owner’s name. She did not say the whole city was safe. She said the people who needed to leave this square had finally received a window in which to do so. The receiving unit replied with a destination for every bed. The name on the bag finally had an address too; waiting no longer meant only an empty chair.'),B('林岳從桌上收起街區圖，沈禾補完守軍的狀況，陳隼將已確認範圍念得比任何一次都清楚。鐘樓仍停在七點十四分，這座城卻有人繼續往前走。灰線替他們守住了那一段，四個呼號在交班時都有回應；街口留下的記號也讓下一班知道，這份安全究竟延伸到哪裡。','Lin Yue folded the district map, Shen He completed the defenders’ condition report, and Chen Sun defined the secured area more clearly than ever. The clock remained at fourteen minutes past seven, but people in the city were moving forward. Greyline had held that stretch for them. All four callsigns answered at handover, and the markings left at the intersections told the next watch exactly how far that safety extended.')],
      costly:[B('廣場的撤離完成了，醫療站的守軍紀錄也因此多出新頁。後方將交戰期間收到的狀態與接收名冊逐項核對，沒有把代價寫成一句整齊的口號。需要照護、重新確認與補足的項目各有欄位，廖婉戰前準備的空白紙張仍被留在桌上，提醒接班人這些名字尚不能草草收起。','The square’s evacuation was completed, and the clinic’s defender records gained new pages. The rear checked statuses received during the fighting against its reception lists, without reducing the cost to a tidy slogan. Care, further confirmation, and replenishment each had their own columns. The blank sheets Liao Wan had prepared before battle remained on the desk, reminding the next staff that these names could not yet be put away carelessly.'),B('通訊紀錄保留著防線每次回報的時間，足以看出這段安全並非自己出現。後方把受損工事、耗用物資和人員狀態另列成冊，讓完成命令之後仍有責任可以追查。灰線守住了廣場，善後卻沒有因此結束；等待家屬的回答必須來自確認，不能讓勝利兩字替任何人省略那一步。','The communications record preserved the times of the line’s reports, showing that this window of safety had not appeared by itself. The rear listed damaged positions, expended supplies, and personnel status separately, so responsibility could still be followed after the order was completed. Greyline had held the square, but the aftermath continued. Answers to waiting families had to come from confirmation; the word victory could not spare anyone that step.')],
      loss:[B('廣場醫療站下一次通行確認沒有依計畫抵達，後方只能重新核對撤離次序和仍在等待的病床。廖婉戰前留下的清單把不能自行移動的人標得很清楚，接收人員沒有因任務失敗就刪去那些註記。沒有一張病床因此變輕，也沒有一個名字因此容易放下，新的安排仍須從這些需要開始。','The clinic’s next passage confirmation did not arrive as planned. The rear had to check the evacuation order and the beds still waiting again. Liao Wan’s prebattle list clearly marked those unable to move by themselves, and receiving staff did not erase those notes because the mission had failed. No bed had become lighter and no name easier to let go. Any new arrangement still had to begin with those needs.'),B('後方保存了交戰中陳隼核對街口的紀錄，以及沈禾當時記下的傷情，卻沒有把舊回報當成現在的點名。守軍沒能完成廣場的預定守衛，尚未確認的人員狀態仍需追查。下一份命令會從這些有限而真實的資料開始，既承認危險，也不把還在等待答覆的人寫成不存在。','The rear preserved Chen Sun’s intersection checks made during combat and the injury notes Shen He recorded then, but it did not mistake those earlier reports for a roll call now. The defenders had not completed the square’s planned watch, and unconfirmed personnel statuses still required tracing. The next order would begin with this limited but truthful evidence, acknowledging danger without writing out the people still waiting for an answer.')],
    },
    assault:{
      brief:[B('衝鋒命令沿街口路障、中央廣場、街區指揮所依序建立三段安全通道。第一處控制進街的路，第二處讓後方能整理車流，第三處補上前沿狀況回報。街區裡沒有一條看起來安靜就自動安全的路，佔領前仍要確認附近威脅與預定進場敵軍已經處理。','The assault order secures three stretches through the street barricade, central square and district command. The first controls entry, the second gives the rear room to organize traffic, and the third completes front-line reporting. No quiet-looking street is automatically safe. Before capturing, deal with nearby threats and the scheduled enemy arrivals.'),B('醫療站的撤離組留在後方，依照各段安全回報安排車流。小隊的任務是奪取現有目標，按住佔領完成確認，然後推進到下一處。廖婉需要的是可以依靠的據點消息；沈禾則提醒，即使沒有時間長篇說話，也要讓隊友聽見自己仍然在隊形裡。','The clinic’s evacuation team stays at the rear, scheduling traffic from each sector’s confirmed status. Secure the objectives, hold capture for confirmation, then advance to the next. Liao Wan needs sector reports she can rely on. Shen He reminds the squad that even when there is no time for conversation, teammates must still hear that everyone remains in formation.'),
      ],
      deploy:[R('command','灰線，街區推進線已確認。依序拿下街口路障、中央廣場與街區指揮所。','Greyline, the district advance is authorized. Secure the street barricade, central square and command position in order.'),R('shen','廖婉的醫療組留在後方。我們把路打開，別把他們等待的人數當成衝動的理由。','Liao Wan’s medical team stays at the rear. We open the route; the number waiting must not become an excuse for reckless haste.')],
      stages:[
        [R('lin','第一處是街口路障，兩侧轉角先看清楚。拿下它，才有一段能向後方確認的路。','First position: the street barricade. Check both corners. Securing it gives us one stretch to confirm to the rear.'),R('chen','我把目標和後方等待區分開標了。先確認眼前的敵軍，別把兩個地方混成一處。','The objective and rear waiting area are marked separately. Confirm the hostiles ahead; do not confuse the two places.'),R('local','醫療站知道你們已經進街。這一段沒有確認前，我不會讓回報替車輛先走出去。','The clinic knows you have entered the district. Until this stretch is confirmed, the report will not send vehicles out early.')],
        [R('chen','第二處是中央廣場，視線會突然變開闊。前一條巷子的掩護，不能帶過整片空地。','Second position: the central square. Sight lines open abruptly here. Cover from the previous alley cannot protect the whole space.'),R('lin','不要四個人停在同一個出口。有人看正面，有人照看側翼，再向廣場裡靠近。','Do not stack all four of us at one exit. Cover the front and flanks separately before moving into the square.'),R('shen','廣場拿下後，後方才有餘地安排下一批。先把隊形帶過去，別只把一個人帶過去。','Securing the square gives the rear room for the next group. Bring the formation through, not just one person.')],
        [R('lin','最後目標是街區指揮所。拿下之前，前兩處通道仍缺最後一段可靠的連接。','Final objective: district command. Until it is secured, the first two stretches still lack their last reliable connection.'),R('chen','我會把最後的確認完整送出，但現在還不寫完成。先看定位，也看附近的火線。','I will send the final confirmation in full, but not mark it complete yet. Watch both the markers and nearby firing lanes.'),R('local','最後一組傷員已在後方等通知。你們把危險說清楚，我才能把路安排清楚。','The final patient group is waiting at the rear. Define the danger clearly so I can define their route clearly.')],
      ],
      regroup:[
        [R('chen','街口路障已確認，第一段通道成立。中央廣場是下一處，兩翼仍要繼續看守。','Barricade confirmed; the first stretch is established. The central square is next. Keep watching both flanks.'),R('shen','先整理傷勢再離開掩體。我們剛打開一段路，不必靠留下傷員來證明速度。','Check injuries before leaving cover. We have opened one stretch; leaving wounded behind proves nothing about our speed.')],
        [R('local','中央廣場的確認收到了，後方正在重排車流。還要等指揮所，整條通道才算可靠。','Square confirmation received; the rear is reorganizing traffic. We still need the command position for a reliable route.'),R('lin','最後一處照樣分清火線。已經拿下的兩處，是讓我們更穩，不是讓我們更急。','Separate our firing lanes at the final position too. The two secured sectors should make us steadier, not more hurried.')],
      ],
      win:[B('第三處據點的確認抵達時，廖婉把新的撤離順序貼在診所桌邊。那張紙沒有宣稱全城得救，只清楚寫出能使用的通道。人們照著通道離開，終於不必拿彼此聽來的傳聞當成方向；後方逐組回覆接收，沿路的街口名稱也與地圖對上，讓焦急的家屬知道可以在哪裡繼續等。','When the third confirmation arrived, Liao Wan posted the new evacuation order beside the clinic desk. It did not proclaim the whole city saved; it clearly described the usable route. People could leave without relying on one another’s rumors for directions. The rear confirmed reception group by group, and the intersection names now matched the map, giving anxious families a place where they could continue waiting.'),B('陳隼在回報最後補上小隊狀況，林岳也把每個人的位置點過一遍。沈禾看見桌上那袋鞋已寫好去處，才允許自己坐下。灰線打開了一條路，讓離開的人和留下的紀錄都不再無處可去；三名隊友在同一份交班表上回應，清晨那些說不準的轉角，也終於有了可以核對的名字。','Chen Sun appended the squad’s condition, and Lin Yue checked everyone’s position once more. Shen He saw that the bag of shoes finally had a destination and allowed herself to sit. Greyline had opened a route for both the departing people and the records they left behind. All three teammates answered on the same handover sheet, and the corners that had been uncertain that morning finally had names that could be checked.')],
      costly:[B('街區通道重新連起來，交戰中記下的守軍狀態也隨確認抵達後方。醫療接收單位把軍人與居民列在同一套需要追查的名冊裡，延續廖婉戰前留下的規矩。完成任務不能替任何人省去照護與確認，通道開始使用之後，醫療站仍得把有限的時間和物資安排到每個真正需要的地方。','The district route was reconnected, and defender statuses recorded during combat reached the rear with its confirmation. The medical receiving unit entered soldiers and residents into the same lists requiring follow-up, continuing the rule Liao Wan had left before battle. Completing the mission could replace neither care nor confirmation. Even after passage began, the clinic still had to allocate its limited time and supplies wherever they were actually needed.'),B('戰前街區圖上的轉角標記，和交戰紀錄裡每個據點的確認時刻，一起被後方保留下來。圖上能用的通道屬於勝利，旁邊尚待核對的人員與物資欄位屬於代價，兩者都不能從灰線的回報裡刪去。接班人得到的是一份可以繼續工作的紀錄，而非一句讓所有問題立刻結束的捷報。','The corner markings on the prebattle district map and the confirmation times for each position in the combat log were preserved together at the rear. The usable route belonged to victory; the personnel and supply entries still requiring checks belonged to its cost. Neither could be removed from Greyline’s report. The next staff received a record they could keep working from, rather than a bulletin pretending every problem had ended at once.')],
      loss:[B('街區最後沒有連成一條可靠通道，後方只能依據已確認的零碎路段重新安排等待。診所物品紀錄裡，那袋鞋仍沒有填上接收地址，正如更多家屬仍不知道下一次可以去哪裡等。沒有完成的推進留下了新的空白，每一處都必須重新確認，不能把曾經抵達某個街口當成整條路已經安全。','The district never became one reliable route, and the rear could only rearrange the waiting around the isolated stretches already confirmed. In the clinic’s belongings register, the bag of shoes still had no receiving address, just as more families still did not know where they could wait next. The unfinished advance left new blanks. Each needed another check; having reached an intersection could not establish the safety of the whole road.'),B('後方收到的通訊紀錄沒有把未完成的據點寫成安全，醫療紀錄也只保留交戰當時能確認的狀況。灰線的推進停下來，接收與追查卻沒有因此停止，守軍現況仍須重新點名。鐘樓指著同一分鐘，等待的人還要承受更多分鐘，下一班因此更需要準確的資料，而不是替失敗遮掩的字句。','The communications record received at the rear did not mark unfinished positions safe, and the medical notes retained only conditions confirmed during the fighting. Greyline’s advance stopped, but reception and tracing did not. A fresh roll call was still needed to establish the defenders’ present status. The clock pointed to the same minute while those waiting had to endure many more. The next watch needed accurate evidence, not words concealing failure.')],
    },
    cleanup:[R('chen','最後敵軍已標出即時位置，街區的牆後也會更新。沿通行路接近，不必逐屋猜人在哪。','The last hostiles have live position markers, even behind district walls. Use passable routes; there is no need to guess house by house.'),R('lin','定位已經有了，隊形不能因此散掉。清除這幾名敵人，才把最後的確認送回醫療站。','We have their positions; keep formation anyway. Clear these remaining hostiles before sending the final confirmation to the clinic.')],
    operationNotes:[
      B('街口交叉火力讓回報頻繁來自不同巷道。陳隼要把每條火線分開記，灰線也必須把掩護分配到不同方向。','Intersection Crossfire brings reports from different alleys. Chen Sun must log each firing lane separately, and Greyline must distribute cover among those directions.'),
      B('巷道清剿的敵軍貼得更近，整備雖較快也不能沖淡風險。林岳提醒，轉角最怕所有人都只看前一個轉角。','Alley Sweep brings attackers closer. Faster regrouping does not remove the risk. Lin Yue warns against watching only the corner the squad has just passed.'),
      B('醫療站撤離的敵軍較少，突破一次卻足以打亂後方。沈禾把這份命令理解為守住次序，而不是追求擊倒數字。','Clinic Evacuation has fewer attackers, but one breach can disrupt the rear. Shen He reads the order as preserving the evacuation sequence, not chasing a kill count.'),
    ],
    afterword:[
      B('很久以後，霧川的居民仍會用停在七點十四分的鐘樓約定地點。有些人忘了它何時停下，有些人每次抬頭都記得那個上午。廖婉把醫療站的名冊帶回原來的診所，沒有丟掉守軍狀況那幾頁，因為居民與守軍的名字原本就在同一天裡。','Long afterward, residents would still use the clock frozen at fourteen minutes past seven to arrange meetings. Some forgot when it stopped; others remembered that morning whenever they looked up. Liao Wan took the clinic lists back to the old practice and kept the defender pages, because residents and soldiers had belonged to the same day.'),
      B('灰線沒有把山城寫成一座因為一場作戰就獲得永遠和平的城。檔案裡保留了可通行範圍、未確認地段與人的去向。林岳說，真實地把一段路交給下一班，比替整座城說一句漂亮話更難；沈禾點頭，因為下一班接到的仍然是人。','Greyline never described Mistwater as a city granted permanent peace by one operation. The archive retained usable routes, unconfirmed areas and people’s destinations. Lin Yue said handing a real stretch of road to the next watch was harder than making a grand statement about the whole city. Shen He agreed, because the next watch would still receive people.'),
    ],
  },
  forest:{
    title:B('森林：回聲裡的名字','Forest Front: Names in the Echo'),
    deck:B('松林遮住了遠處的火光，也遮住彼此的位置。灰線沿著戰壕與通訊站守住最後一條消息通道，讓還在林外等待的人能知道該往哪裡走。','The pines hide distant fire and the squad’s own positions. Greyline holds the trenches and relay along the last reporting route, so people waiting beyond the forest can still learn which way to go.'),
    timeLabel:B('撤離第六日・06:10','Evacuation Day Six · 06:10'),
    location:B('青針林帶・前沿戰壕與林間通訊站','Greenneedle Belt · Forward trenches and the woodland relay'),
    background:[
      {title:B('一、留在樹上的記號','I. Marks Left on the Trees'),paragraphs:[
        B('機甲通過青針林帶時，在幾株松樹上留下高過人的擦痕。它們撤走後，森林很快把遠處的聲音重新吞掉，地上卻還有壓深的泥路。當地技師葉棠以前是護林員，能說出哪條路通向舊工棚，哪條只會回到自己剛走過的坡。她從後方回報林區狀況，提醒灰線不要把看不見當成沒有。','The mechs left scrape marks above head height on several pines as they crossed Greenneedle Belt. After their withdrawal, the forest quickly swallowed distant sounds again, though deep tracks remained in the mud. Local technician Ye Tang had once been a forest ranger. She knew which trails reached old sheds and which merely circled back to the same slope. Reporting from the rear, she warned Greyline not to mistake unseen ground for empty ground.'),
        B('林間通訊站在和平時傳送林火與降雨資料，現在接住撤離隊伍與補給車的片段回報。有些消息只有人數，沒有位置；有些只剩位置，說不清還有誰同行。陳隼把收到的內容分成確認與待確認，頻道越吵，他越不肯省略這個區別。沈禾聽見一份藥物需求，發現報訊的人一直沒有提自己的傷。','The woodland relay once carried fire warnings and rainfall data. Now it receives fragments from evacuation groups and supply vehicles: some reports give numbers without locations; others give a location but cannot say who remains together. Chen Sun separates the confirmed from the unconfirmed, refusing to blur that distinction as the net grows louder. Shen He hears one request for medicine and notices the caller has not mentioned their own injury.'),
      ]},
      {title:B('二、聲音不會替人帶路','II. Sound Cannot Lead the Way for You'),paragraphs:[
        B('先遣敵軍利用林徑接近戰壕，槍聲在樹幹與坡面之間反射，讓同一聲像從兩個方向傳來。林岳要求小隊回報實際位置，不用聲量大小猜距離。他在這裡格外少說話，並非沒有話可說，而是每個多出的句子都可能蓋掉一次必要的回報。森林讓他明白，安靜也需要有人負責辨認。','Enemy scouts use the trails to approach the trenches. Shots reflect between trunks and slopes until a single sound seems to come from two directions. Lin Yue asks for actual positions instead of guesses based on loudness. He speaks less here, not because he has nothing to say, but because an extra sentence can cover a necessary report. The forest has taught him that even silence needs someone to interpret it.'),
        B('灰線可以守在林間通訊站的撤離線，抵擋四波攻勢，替林外等待的人保住消息通道；也可以依序奪取前沿戰壕、林間碉堡與通訊陣地，讓這條通道重新穩定。兩份命令獨立可選，不需要別的戰場先給出勝利。需要它們的人，只知道今天的回報如果中斷，明天的路也可能找不到。','Greyline can defend the evacuation line around the woodland relay through four waves, preserving reports for people waiting beyond the trees. Alternatively, the squad can secure the forward trench, woodland bunker and relay position in sequence to stabilize that route. The orders are independent choices, not rewards for winning elsewhere. The people who need them know only that if today’s reports stop, tomorrow’s route may be lost too.'),
      ]},
      {title:B('三、回報中的空白','III. The Blanks in a Report'),paragraphs:[
        B('葉棠收到一份撤離小隊的回報，地點寫的是已拆除的舊木橋。她沒有直接把它改成新地名，而是追查他們手上的地圖版本，才知道那群人一直沿著過期標記走。陳隼將新的位置描述補進確認紀錄。錯誤沒有立刻奪走誰，卻差一點讓整群人消失在看似完整的通訊表裡。','Ye Tang receives a report from an evacuation group identifying the demolished timber bridge as its location. Rather than simply replacing the place name, she checks their map edition and discovers they have been following obsolete markers. Chen Sun adds a corrected location description to the confirmed record. The mistake has not taken a life, but it nearly erased an entire group inside a communications table that looked complete.'),
        B('沈禾說，森林裡最難處理的傷勢有時不是失血，而是相信自己已經被忘記。林岳沒回答這句話，只要求每次推進都清點小隊。葉棠把舊橋的位置也保留在備註裡，讓接班的人知道有人仍可能用那個名字。灰線要守住的因此不只是電台，而是讓不同地圖、不同步速的人仍能互相找到的耐心。','Shen He says the hardest wound in a forest is sometimes the belief that one has been forgotten. Lin Yue answers by requiring a squad count at every advance. Ye Tang keeps the old bridge name in the notes so the next watch will know someone may still use it. Greyline is holding more than a radio: the patience that lets people with different maps and different walking speeds still find one another.'),
      ]},
    ],
    cast:[
      {id:'lin',name:B('林岳','Lin Yue'),role:B('班長・林間隊形','Squad leader · woodland formation'),detail:B('他用短句維持隊形，要求位置回報比情緒更清楚。每次轉過倒木與坡邊都會重新清點，因為他知道一名同袍落在視線外，往往比所有人同時停下更危險。','He keeps formation with short statements and asks for positions clearer than emotions. After fallen timber and bends in the slope, he counts the squad again. One teammate falling out of sight can be more dangerous than everyone stopping together.')},
      {id:'shen',name:B('沈禾','Shen He'),role:B('軍醫・傷勢與疲勞辨識','Medic · injuries and fatigue'),detail:B('留意隊友是否在回報時少了一口氣，也留意後方求藥的人是否沒有提到自己。她不把逞強當成堅定，希望每個仍在森林裡的人都能在紀錄裡得到一個完整的位置。','She hears when a teammate is a breath short in a report and notices callers requesting medicine without describing their own condition. She does not mistake bravado for resolve, and wants everyone still in the forest to have a complete place in the record.')},
      {id:'chen',name:B('陳隼','Chen Sun'),role:B('通訊兵・確認與定位','Signals operator · confirmation and tracking'),detail:B('在雜訊裡學會容忍暫時不知道，卻不容忍假裝已經知道。確認、待確認與最後敵軍定位都會分開呈現，讓灰線不用把時間花在猜測某個人到底跑到哪裡。','In interference, he learns to tolerate not knowing yet, but never pretending to know. Confirmed reports, unresolved reports and final-hostile tracking remain distinct, so Greyline need not waste time guessing where someone has gone.')},
      {id:'local',name:B('葉棠','Ye Tang'),role:B('林區技師・後方地名核對','Forest technician · rear location checks'),detail:B('曾巡查整片林帶，現在以技師身分維護後方的通訊紀錄。她知道舊地名不會因為新版地圖印出來就消失，願意多問幾次，避免讓仍拿舊地圖的人被當成失聯。','Once a ranger across the belt, she now maintains communications records at the rear. She knows old place names do not vanish when new maps are printed, and asks again rather than counting people with outdated maps as missing.')},
    ],
    stakes:[
      B('通訊站守不住時，林外的人會失去可靠的道路與補給回報，即使看得見出口也可能不知道該走哪一條。','If the relay is lost, people beyond the forest lose reliable road and supply reports. They may see a way out without knowing which route to take.'),
      B('戰壕、碉堡與通訊陣地共同支撐前沿消息；三處確認連在一起，才足以讓後方繼續安排等待的人。','The trench, bunker and relay position support front-line reporting together. Their three confirmations let the rear continue organizing those who wait.'),
      B('森林會遮住人的輪廓，紀錄不能也把人遮住。小隊存活、傷勢與未確認消息都需要被如實帶回。','The forest hides people’s outlines; the record must not hide them too. Survivors, injuries and unresolved reports all need to be returned honestly.'),
    ],
    defend:{
      brief:[B('守衛命令要求灰線以林間通訊站的撤離線為後方，抵擋四波敵軍。松林與倒木讓兩翼變得難以看清，但仍有能通行的道路與火線。林岳會照應隊形，陳隼維持定位與回報；沈禾要求每次有人轉向林側，都得讓另一個人知道自己在哪裡。','The defense order uses the woodland relay’s evacuation line as Greyline’s rear position through four waves. Pines and fallen timber obscure the flanks, but passable routes and firing lanes remain. Lin Yue watches formation, Chen Sun maintains tracking and reports, and Shen He asks that anyone turning into the trees make their position known to someone else.'),B('葉棠與後方通訊組會整理撤離人員的消息，依據你們守住的時間安排去向與補給。灰線要做的是守線、清除每波進場敵軍，並保留小隊互相掩護的能力。陳隼會把已確認的位置送回，讓林外的等待有可靠依據。森林的回聲可以很大，真正需要的回報卻必須短而準確。','Ye Tang and the rear signals team organize reports from evacuees, using the window you preserve to arrange destinations and supplies. Greyline must hold, clear each deployed wave and retain mutual cover. Chen Sun returns confirmed positions so the waiting beyond the trees have something reliable to use. Echoes may be loud; the reports that matter must remain short and accurate.'),
      ],
      deploy:[R('command','灰線，林間通訊站的撤離線由你們接替。四波攻勢結束前，後方仍需要這條消息通道。','Greyline, take over the relay’s evacuation line. The rear needs this reporting route until all four waves are cleared.'),R('lin','林子會把人遮住，別把回報也省掉。先確認小隊位置，再確認前方的動靜。','The trees will hide us; do not hide our reports as well. Confirm squad positions before the movement ahead.')],
      stages:[
        [R('chen','第一波進入林帶，兩翼都有接近回報。不要用槍聲的回聲猜位置，我會更新確認資訊。','The first wave is entering the belt, with approaches on both flanks. Do not locate them by echoes; I will update confirmed information.'),R('lin','正面廊道留住火線，側邊有人就報實際位置。看不到彼此時，更要知道彼此在哪裡。','Keep a firing lane in the forward corridor and report real flank positions. Out of sight must not mean unaccounted for.'),R('shen','葉棠已接上後方，等待的人還在核對地名。我們先讓這一段回報保持完整。','Ye Tang is on the rear net; the waiting groups are still checking place names. Keep our stretch of reporting intact.')],
        [R('lin','第二波可能從另一條林徑靠近。上一波走過的方向，不是這一波唯一的方向。','The second wave may approach by another trail. The last wave’s direction is not the only direction available now.'),R('chen','後方仍有待確認的回報，但這不是放掉前線的理由。先把真正朝撤離線來的人擋住。','The rear still has unresolved reports. That is no reason to leave the front. Stop the hostiles actually approaching the evacuation line.'),R('local','舊木橋的地名已核對，撤離隊伍的位置重新確認了。這條頻道還有人需要繼續聽。','The old bridge name is checked and the evacuation group located again. People still need to hear this channel.')],
        [R('shen','第三波到了，疲勞會讓你把空白當成安全。檢查隊友的位置，也檢查自己的傷勢。','The third wave is here. Fatigue can make blank space look safe. Check your teammates’ positions and your own injuries.'),R('lin','兩翼和正面分開照看，別跟著同一聲槍響全轉過去。通往撤離線的路還要留人守。','Cover the flanks and front separately. Do not all turn toward one shot. Keep someone watching the evacuation approaches.'),R('chen','後方確認了下一組補給去向，消息仍在傳。再守住這一波，他們就多一段可靠時間。','The rear has confirmed the next supply group’s destination. Reports are still flowing. Holding this wave buys another reliable window.')],
        [R('command','第四波是本次林區守衛最後攻勢。已進場敵軍全部清除後，再送出結束確認。','The fourth wave is the final forest attack. Send the ending confirmation after all its deployed hostiles are cleared.'),R('chen','最後幾份待確認消息還在核對，我不會先填完成。你們也別讓最後的敵人溜過防線。','The last unresolved reports are still being checked; I will not mark them complete early. Keep the final hostiles from crossing the line.'),R('lin','最後一波仍要清點小隊。誰都不用獨自跑進林子，定位和隊友都是我們能用的東西。','Count the squad during the final wave too. Nobody needs to run into the trees alone; we have tracking and one another.')],
      ],
      regroup:[
        [R('chen','第一波清除，後方回報仍保持連續。趁這段空間整理裝備，下一波還沒有結束名冊。','First wave cleared; rear reports remain continuous. Use the pause to service gear. The next wave is still on the list.'),R('shen','小隊位置再確認一次，傷勢也一起報。我不想等到有人跟不上才知道他早就受傷。','Confirm squad positions and injuries together. I do not want to discover an old wound only when someone can no longer keep up.')],
        [R('local','第二波的消息已收到，舊地名也補進紀錄。下一班不會再只拿著一張錯過時間的地圖。','Second-wave report received; old place names are in the notes. The next watch will not have only a map that missed its time.'),R('lin','輪流整備，林徑仍要有人照看。現在安靜，是我們爭來的間隔，不是森林替我們保證。','Regroup in turns and keep the trails covered. This quiet is a pause we earned, not a guarantee from the forest.')],
        [R('chen','第三波清了，最後一波還在名冊上。定位會繼續更新，確認也要繼續做完。','Third wave cleared; the final one remains listed. Tracking will keep updating, and confirmations still need to be completed.'),R('shen','喝水、看傷勢，也看看身邊那個人。最後一段需要的不是逞強，是都還能互相照應。','Drink, check injuries and look at the person beside you. The final stretch needs mutual support, not bravado.')],
      ],
      win:[B('第四波被清除後，陳隼收到最後一份位置確認。葉棠把舊木橋和新路標寫在同一段說明裡，讓使用不同地圖的人都能理解。通訊站沒有替誰走完森林，卻讓等待的人重新有了可信的方向；林外的接收人員讀回每個名稱，也將需要交給下一班的時間標記一同保存。','After the fourth wave was cleared, Chen Sun received the final location confirmation. Ye Tang put the old bridge and new trail markers in the same description so people using different maps could understand. The relay had not walked the forest for anyone, but it had restored a direction the waiting could trust. Receiving staff beyond the woods read back every name and preserved the timestamps that the next watch would need.'),B('林岳最後一次清點小隊，沈禾把每個人的狀況補進回報，陳隼確認四個呼號都得到了回覆。風吹過松針時，聲音還是難以分辨，人的名字卻已經分得清楚。灰線守住了那條不會因為看不見就忘記人的線，接班資料裡的舊橋也終於被註明，讓過時的地名不再替下一班製造迷路。','Lin Yue counted the squad once more. Shen He entered everyone’s condition, and Chen Sun checked that all four callsigns had received replies. Wind through the needles was still hard to interpret, but the names were clear. Greyline had held a line that would not forget people merely because they were out of sight. The old bridge was finally annotated in the handover, so its outdated name would not misdirect the next watch.')],
      costly:[B('消息通道沒有斷，後方卻不能只用正常運作四字帶過這一班守衛。交戰中留下的狀態紀錄與重問過的位置都要逐項核對，受損工事和耗用物資也另有接收清單。森林外的人得到可信的方向，支撐方向的守軍現況仍須仔細確認，不能因為頻道恢復就假定每個人已經平安回到後方。','The reporting route stayed open, but the rear could not summarize this watch as normal service. Status records made during combat and positions that had required repeated questions needed individual checks. Damaged defenses and expended supplies had their own reception lists. People outside the forest had gained a trustworthy direction, while the defenders who sustained it still required careful confirmation. Restored communications could not establish that everyone had returned safely.'),B('葉棠在戰前資料裡寫過，林帶下一季會長回新的枝條；後方現在把這頁保留下來，卻沒有拿它當成人員狀態的安慰。任務完成了，接收、醫療與重新點名仍各有需要處理的時間。灰線的回報既有保住的通道，也有不能省略的等待，下一班必須把兩部分都讀完才能真正接下守衛。','Ye Tang’s prebattle notes had said that the woodland would grow new branches next season. The rear preserved the page without turning it into reassurance about personnel. The mission was complete, while reception, medical work, and another roll call each still required time. Greyline’s report carried both the preserved route and the waiting that could not be omitted. The next watch had to read both before truly taking over the defense.')],
      loss:[B('林間通訊站沒能完成預定守衛，後方只能把需要延續確認的消息重新標為待確認。交戰紀錄中最後可靠的位置被保留下來，舊木橋與新路標的差異也沒有被刪去。森林裡的道路仍在，人們對道路的把握卻再次變得薄弱，接班人需要重新查明當下的狀況，不能靠先前的安靜猜測安全。','The woodland relay did not complete its planned defense, and the rear had to mark information requiring continued checks as unconfirmed again. The last reliable positions in the combat log were retained, along with the distinction between the old bridge and the new trail markers. The paths remained, but confidence in them thinned. The next watch would need to establish current conditions again, rather than infer safety from an earlier silence.'),B('林岳戰前要求接班時先清點的註記，和沈禾在交戰中記下的醫療狀況，一起存進後方的接收資料。這些紀錄不能代替如今的人員確認，未完成的項目仍須繼續追查。灰線沒能做完這次守衛，留下的證據仍提醒下一班：失聯不是不存在，安靜也不是安全，每個未確認的名字都還有責任要接住。','Lin Yue’s prebattle instruction to begin handover with a count and the medical conditions Shen He recorded during combat entered the rear’s reception file together. Those records could not establish anyone’s present condition; unfinished entries still required tracing. Greyline had not completed this defense, but the evidence told whoever followed that missing did not mean absent and quiet did not mean safe. Every unconfirmed name still carried a responsibility to be taken up.')],
    },
    assault:{
      brief:[B('推進命令沿前沿戰壕、林間碉堡與通訊陣地建立三段可靠位置。小隊沿目標與可通行路線前進，每次靠近都要看側翼，不能讓樹冠遮住了敵人，就誤以為附近已無威脅。到場後仍須完成佔領確認，後方才有可用消息。林岳會在每段停留時，重新點清小隊的人數與方向。','The advance order establishes three reliable positions at the forward trench, woodland bunker and relay. Follow the objectives and passable routes, checking the flanks on every approach rather than treating enemies hidden beneath the canopy as gone. Complete capture at each position so the rear has usable information. At every halt, Lin Yue checks the squad’s count and directions again.'),B('葉棠從後方協助核對林區回報，陳隼維持小隊定位，沈禾則要求每次轉換掩體都確認彼此仍能跟上。戰壕、碉堡與陣地像三段需要接續的句子；灰線逐一拿下，後方才能把原本零碎的消息讀成完整通道，讓等待的人知道下一步該往哪裡走。','Ye Tang checks woodland reports from the rear, Chen Sun maintains the squad’s tracking, and Shen He asks for a count whenever cover changes. The trench, bunker and relay are three parts of a sentence that needs joining. As Greyline secures them, the rear can read its fragments as a complete route and tell the waiting people where to go next.'),
      ],
      deploy:[R('command','灰線，林區推進線已確認。依序奪取前沿戰壕、林間碉堡與通訊陣地。','Greyline, the woodland advance is authorized. Secure the forward trench, woodland bunker and relay in sequence.'),R('local','我會從後方核對地名與回報。你們走眼前能走的路，別讓舊記號替現在作決定。','I will check place names and reports from the rear. Use the routes actually open ahead, not old marks making present decisions.')],
      stages:[
        [R('lin','第一目標是前沿戰壕，先看兩側的接近路。留住一段互相能照看的隊形再進場。','First objective: the forward trench. Check both approaches and enter with a formation that can cover itself.'),R('chen','戰壕已標在目標位置，附近敵軍仍要實際確認。樹幹後看不見，不代表那裡沒有人。','The trench is marked, but nearby hostiles still need confirmation. An unseen space behind a trunk is not an empty one.'),R('shen','我們從這一處開始把路連起來。別為了第一段的速度，把傷勢留給後面兩段。','We begin joining the route here. Do not buy speed in the first stretch with injuries carried through the next two.')],
        [R('chen','第二目標轉向林間碉堡，側翼變得更近。前一段的安全，不能替這一段作確認。','Second objective: the woodland bunker, where the flanks draw closer. Safety behind us cannot confirm the stretch ahead.'),R('lin','倒木可以提供掩護，也能遮住腳步。轉換位置前先報方向，不要讓隊友猜你的路。','Fallen timber offers cover and hides movement. Call your direction before shifting; do not make teammates guess your route.'),R('local','後方正在依你們的確認更新路況。碉堡還沒拿下前，那一段仍會留在待確認欄。','The rear is updating the route from your confirmations. Until the bunker is secured, its stretch remains unconfirmed.')],
        [R('lin','最後目標是通訊陣地。還缺這一段，前面兩處就不能替後方提供完整的通道。','Final objective: the relay. Without this stretch, the first two positions still cannot provide a complete route to the rear.'),R('chen','最後的定位與確認都會持續更新。收到訊號不是結束，附近威脅清掉才算完成。','Final positions and confirmations will keep updating. Receiving a signal is not the end; clear the nearby threats.'),R('shen','把小隊一起帶到最後。後方等的是完整回報，我也要交得出你們每個人的狀態。','Bring the whole squad through. The rear needs a complete report, and I need to account for every one of you.')],
      ],
      regroup:[
        [R('chen','前沿戰壕已確認，第一段消息送回後方。下一處是林間碉堡，側翼回報會繼續更新。','Forward trench confirmed; the first report is back at the rear. Woodland bunker next. Flank reports will keep updating.'),R('lin','先清點再移動，確認彼此還能照應。林子裡最不划算的速度，是只有一個人跑快。','Count before moving and confirm mutual cover. The least useful speed in this forest is one person running ahead.')],
        [R('local','林間碉堡的確認收到，舊地名也一併註明。剩下通訊陣地，後方還在等完整通道。','Bunker confirmation received, with the old place names noted too. The relay remains; the rear still needs a complete route.'),R('shen','兩段完成了，還有最後一段。檢查傷勢，也確認隊友的位置，不要只看自己的目標。','Two stretches complete, one remaining. Check injuries and teammate positions instead of watching only your own objective.')],
      ],
      win:[B('三處位置的確認完整送出，葉棠終於能把林區通道寫成一段連續的說明。使用舊橋地名的人與使用新路標的人，都能從同一份回報找到自己。陳隼在末尾標明時間，讓後來的人知道這份安全何時成立；林外逐句讀回路況，兩套曾經互相矛盾的方向終於能指向同一條可用的路。','All three confirmations were sent, and Ye Tang could finally describe the woodland route as one continuous passage. People using the old bridge name and those using new trail markers could find themselves in the same report. Chen Sun marked the time so those following would know when that safety had been established. Staff beyond the woods read back the conditions line by line. The two once-contradictory sets of directions could finally describe the same usable path.'),B('林岳停下來清點，沈禾把小隊狀況補齊，陳隼逐一等到四個呼號的回覆。森林並沒有因此變得能一眼看穿，但灰線已讓需要通道的人少猜了一段。那些留在樹上的機甲擦痕，現在也只是路邊的一種記號；真正能交給下一班的是確認過的路況、完整的名冊，以及願意承認看不清的部分。','Lin Yue halted for a count. Shen He completed the squad’s condition report, and Chen Sun waited for each of the four callsigns to answer. The forest had not become transparent, but Greyline had removed one stretch of guesswork for those who needed passage. Even the mech scars on the trees were now simply marks beside the road. What the next watch could actually use was verified conditions, a complete list, and an honest account of what still could not be seen.')],
      costly:[B('通道恢復了連續回報，小隊的狀況卻需要另一份完整說明。後方把交戰中收到的醫療紀錄與短暫中斷的回報時間放在一起核對，沒有因為三處據點都已確認就將資料收起。森林沒有說明的部分，仍要由接收人員仔細追查，人員、裝備與通道各有不同的狀態，不能用一個完成同時回答。','The route regained continuous reporting, while the squad’s condition required another full account. The rear checked medical notes received during combat against the times of interrupted reports, rather than putting the papers away because all three positions had been confirmed. What the forest did not explain still required careful tracing by the receiving staff. Personnel, equipment, and passage each had different statuses; a single complete could not answer for them all.'),B('葉棠戰前準備的路程表仍在後方桌上，接收單位現在另列點名、照護和補足裝備所需的時間。灰線打開通道，也留下必須由後方繼續承擔的工作，每個尚待確認的欄位都有接手人。下一班得到的不只是可以前行的方向，還有這次推進付出的物資與人員紀錄，讓代價不被捷報抹去。','Ye Tang’s prebattle journey sheet remained on the rear desk. The receiving unit now added the time needed for roll calls, care, and replacing equipment. Greyline had opened the route and left work that the rear still had to carry; every entry awaiting confirmation had someone assigned to it. The next watch received more than a direction forward. It also received the advance’s personnel and supply records, so a victory bulletin would not erase the cost.')],
      loss:[B('未完成的據點把林區回報截成幾段，後方重新把尚不可靠的通道標為待確認。接收人員沒有用舊紀錄填補空白，也沒有把未送達的消息當成已經收到。這一次林外的人還得繼續等方向，舊木橋和新路標的對照仍被留在資料最前面，免得下一班在重新查明危險以前就先走錯了路。','The unfinished positions broke the woodland reports into separate stretches, and the rear marked the unreliable passage unconfirmed again. Receiving staff did not fill the blanks with old records or treat undelivered messages as received. People beyond the forest still had to wait for directions. The comparison between the old bridge and new trail markers remained at the front of the file, so the next watch would not take a wrong path before even checking its dangers.'),B('交戰中留下的醫療註記和小隊位置，被後方分別標上當時的確認時間，沒有被冒充成現在的平安回報。灰線沒能完成三段通道，紀錄卻仍保留每次推進的有限成果與空白。接班的人會知道從哪一段開始重新確認，接收人員也會繼續核對所有名字，讓失敗不至於把曾經在這裡的人一起抹去。','The medical notes and squad positions recorded during combat received their original confirmation times at the rear; they were not presented as assurances of safety now. Greyline had not completed the three stretches, but the record preserved the limited gains and blanks of each advance. The next watch would know where to begin checking again. Receiving staff would also continue verifying every name, so failure would not erase the people who had been here.')],
    },
    cleanup:[R('chen','最後敵軍的即時定位已確認，紅色標記會持續更新。沿可走路線接近，不用再追森林的回聲。','Live positions for the last hostiles are confirmed; red markers will keep updating. Follow passable routes instead of chasing echoes.'),R('lin','定位會替我們找位置，隊友會替我們照應。不要單獨散進林子，清完再報結束。','Tracking gives us positions; teammates give us cover. Do not scatter into the trees alone. Report completion after the cleanup.')],
    operationNotes:[
      B('林間滲透讓兩側消息反覆改變。葉棠提醒，回報頻繁不代表誰判斷錯了，而是灰線需要更勤快確認彼此的位置。','Forest Infiltration changes the flank reports repeatedly. Ye Tang warns that frequent updates need not mean earlier judgment was wrong; Greyline must check positions more often.'),
      B('觀測哨獵殺的攻勢較慢，遠處壓制卻更明顯。陳隼不讓等待變成猜測，據點確認仍得用完整時間做完。','Watchpost Hunt advances more slowly but emphasizes distant suppression. Chen Sun refuses to turn waiting into guesswork; sector confirmation still needs its full time.'),
      B('戰壕突擊讓近處腳步與火線變密。林岳要求先留住小隊互相掩護，再利用較快整備守住下一段時間。','Trench Storm crowds the nearby approaches and firing lanes. Lin Yue asks the squad to keep mutual cover first, then use faster regrouping to preserve the next window.'),
    ],
    afterword:[
      B('葉棠後來在林區說明裡加入兩套地名，旁邊寫著「有人仍會用舊稱」。那不是地圖過時的辯解，而是一份給接班者的提醒：資訊更新比人走得快，不能因此讓走得慢的人消失。陳隼把這句話抄在自己的通訊簿首頁，每次翻開都先看見。','Ye Tang later added both sets of place names to the forest notes, writing beside them, “Some people still use the old names.” It was not an excuse for outdated maps, but a reminder to the next watch: information changes faster than people walk, and the slower people must not disappear because of it. Chen Sun copied the sentence onto the first page of his signals book.'),
      B('灰線離開林帶後，風仍會把聲音折回來，樹冠仍會讓遠處看不清。小隊沒有改變森林的本性，只在一段需要人的時間裡拒絕用猜測取代確認。鋼鐵巨人留下高高的擦痕，步兵留下較小的紀錄；後者也能讓下一個人找到自己應該走的路。','After Greyline left the belt, wind would still turn sounds back and the canopy would still obscure the distance. The squad had not changed the forest’s nature. During one watch that needed people, they had refused to substitute guesses for confirmation. The steel giants left high scars; infantry left smaller records. Those, too, could help the next person find a route.'),
    ],
  },
};
