import{foods,stalls,recipes,steps,fresh,restore,current,missing,add,selectRecipe,loadFood,canCook,cook,serve,nextGuest}from'./model.js';
const $=id=>document.getElementById(id);let state;try{state=restore(localStorage.getItem('little-bloom-v1'));}catch{state=fresh();}let started=false,feedbackTimer,audio,gesture=null,lastTap=0;
const icons={market:'🧺',kitchen:'🍳',shop:'🍽️'};const names={market:['大大的市場','THE MORNING MARKET'],kitchen:['香香的小廚房','A LITTLE MAGIC'],shop:['小花食堂','MADE WITH LOVE']};
function save(){try{localStorage.setItem('little-bloom-v1',JSON.stringify({...state,version:1}));}catch{}}
function speak(text){if(!started||!state.sound||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';u.rate=.88;u.pitch=1.12;const v=speechSynthesis.getVoices().find(v=>v.lang==='zh-TW')||speechSynthesis.getVoices().find(v=>v.lang.startsWith('zh'));if(v)u.voice=v;speechSynthesis.speak(u);}catch{}}
function chime(happy=false){if(!state.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();[0,...(happy?[.11,.23]:[])].forEach((t,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=[523,659,784][i];g.gain.setValueAtTime(.0001,audio.currentTime+t);g.gain.exponentialRampToValueAtTime(.045,audio.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+t+.22);o.connect(g);g.connect(audio.destination);o.start(audio.currentTime+t);o.stop(audio.currentTime+t+.24);});}catch{}}
function btn(icon,label,action,cls='',extra=''){return`<button class="${cls}" data-action="${action}" aria-label="${label}" ${extra}>${icon}</button>`;}
function foodBtn(id,action,cls=''){return btn(`${foods[id][0]}<small>${'<i></i>'.repeat(state.pantry[id]||0)}</small>`,foods[id][1],`${action}:${id}`,`food-btn ${cls}`);}
function flash(emoji,text){$('feedback').textContent=emoji;$('feedback').classList.add('show');clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>$('feedback').classList.remove('show'),1300);if(text)speak(text);}
function particles(symbol='✨',x=50,y=65){for(let i=0;i<6;i++){const el=document.createElement('span');el.className='particle';el.textContent=symbol;el.style.left=`${x+(Math.random()-.5)*25}%`;el.style.top=`${y+(Math.random()-.5)*15}%`;$('particles').append(el);setTimeout(()=>el.remove(),1150);}}
function recommended(){if(state.paid||state.ready)return'shop';if(missing(state).length||state.free&&!Object.values(state.pantry).some(n=>n>0))return'market';return'kitchen';}
function navigate(scene){state.scene=scene;render();hint();save();}
function ticket(){const r=current(state);$('ticket').innerHTML=`<span class="ticket-dish">${r.icon}</span><span class="ticket-items">${(state.free?state.loaded:r.items).map(id=>`<span class="need ${state.loaded.includes(id)||state.pantry[id]?'have':''}">${foods[id][0]}</span>`).join('')}${state.free&&state.loaded.length<2?'<span class="need">?</span>'.repeat(2-state.loaded.length):''}</span>`;}
function render(){const s=state,r=current(s);$('world').className=s.scene;$('sceneTitle').innerHTML=`<i>${icons[s.scene]}</i><span>${names[s.scene][0]}<small>${names[s.scene][1]}</small></span>`;$('voice').textContent=s.sound?'🔊':'🔇';$('voice').setAttribute('aria-pressed',String(s.sound));ticket();$('nav').innerHTML=Object.entries(icons).map(([key,ic])=>btn(`<span class="nav-icon">${ic}</span><span>${{market:'去買菜',kitchen:'做料理',shop:'招待朋友'}[key]}</span>`,names[key][0],`nav:${key}`,`nav-btn ${s.scene===key?'active':''} ${recommended()===key&&s.scene!==key?'recommended':''}`,`aria-current="${s.scene===key?'page':'false'}"`)).join('');
if(s.scene==='market')renderMarket();else if(s.scene==='kitchen')renderKitchen();else renderShop();}
function renderMarket(){const s=state,stall=stalls[s.stall],need=missing(s);$('scene').innerHTML=`<div class="coins" aria-label="遊戲代幣">${'🪙'.repeat(Math.min(s.coins,3))||'🤝'}</div><div class="market-stall buy" style="--stall:${stall.color}">${stall.items.map(id=>foodBtn(id,'buy',need.includes(id)?'hint-ring':'')).join('')}</div><div class="shopping-basket" aria-label="購物籃"><span>🧺</span>${Object.entries(s.pantry).filter(([id,n])=>n>0).slice(-5).map(([id])=>`<span>${foods[id][0]}</span>`).join('')}</div>`;$('tray').innerHTML=`<div class="tray-content"><div class="tray-label">六個攤位，慢慢逛</div><div class="row">${stalls.map((x,i)=>btn(x.icon,x.name,`stall:${i}`,`tab-stall ${i===s.stall?'selected':''} ${x.items.some(id=>need.includes(id))?'hint-ring':''}`)).join('')}${btn('🍳 →','回小廚房','nav:kitchen','next', 'id="toKitchen"')}</div></div>`;}
function renderKitchen(){const s=state,r=current(s),enough=canCook(s),step=r.steps[Math.min(s.step,2)],list=s.free?Object.keys(foods).filter(id=>s.pantry[id]||s.loaded.includes(id)):r.items;
let inside=s.ready?r.icon:s.loaded.length?s.loaded.map(id=>`<span class="food">${foods[id][0]}</span>`).join(''):'＋';
$('scene').innerHTML=`<button class="big-action ${s.step>0?step:''} ${enough&&!s.ready?'hint-ring':''}" data-action="cook" aria-label="${s.ready?'料理完成':enough?steps[step][1]:'把食材放進來'}" id="cookingArea"><span class="inside">${inside}</span>${enough&&!s.ready?`<span class="tool">${steps[step][0]}</span><span class="hint-hand">👆</span><span class="step-dots">${[0,1,2].map(i=>`<i class="${s.taps>i?'done':''}"></i>`).join('')}</span>`:''}${s.ready?'<span class="hint-hand">✨</span>':''}</button><span class="owner-pin">${['🌸','🎀','🌼'][s.apron]}</span>`;
let controls=s.ready?btn(`${r.icon} → 🍽️`,'端給客人','nav:shop','next pink'):enough?`<div class="row">${r.steps.map((id,i)=>btn(`${steps[id][0]}${i<s.step?'<span style="font-size:14px">✓</span>':''}`,steps[id][1],i===s.step?'cook':'stepHint',`step-button ${i===s.step?'active':'completed'}`)).join('')}</div>`:`<div class="row">${list.map(id=>foodBtn(id,s.loaded.includes(id)?'loaded':s.pantry[id]?'load':'find',s.loaded.includes(id)?'picked':'')).join('')}${!s.free&&missing(s).length||s.free&&list.length<2?btn('🧺 →','到市場買食材','nav:market','next'):''}</div>`;
$('tray').innerHTML=`<div class="tray-content"><div class="tray-label">${s.ready?'香香的料理，送給朋友':enough?'洗一洗，動動小手做料理':'點食材，放進料理盤'}</div>${controls}${s.free&&!enough?`<div class="row free-method">${btn('🥣','創意湯','method:mix',`step-button ${s.method==='mix'?'active':''}`)}${btn('🥤','創意飲料','method:blend',`step-button ${s.method==='blend'?'active':''}`)}</div>`:''}</div>`;}
function renderShop(){const s=state,r=current(s);$('scene').innerHTML=`<div class="customer ${s.paid?'happy':''}" style="background-position:${s.customer*100/3}% center" aria-label="${['兔兔','小熊','小米','小海'][s.customer]}"></div><div class="bubble">${s.paid?'💕':r.icon}</div><div class="flowers">${['🌷','🌻','🌸','🌼'][s.decor]}</div><div class="decor">${btn('🌷','換店裡的花','decor')}${btn('🌸','換老闆娘的小胸花','apron')}</div>${s.ready?btn(r.icon,'把料理送給朋友','serve','big-action serving hint-ring'):s.paid?btn('🪙 🌼','收下謝謝，招待下一位朋友','next','big-action serving hint-ring'):btn('🧺 →','幫客人買菜做料理','begin','big-action serving')}<span class="owner-pin">${['🌸','🎀','🌼'][s.apron]}</span>`;
$('tray').innerHTML=`<div class="tray-content"><div class="tray-label">${s.paid?'謝謝招待！再請一位朋友來坐坐':s.ready?'做好囉！點料理，請朋友吃':'今天想做什麼？也可以自己搭配'}</div><div class="row">${s.paid?btn('👋 →','招待下一位朋友','next','next'):s.ready?btn('🍽️ → 💕','端出料理','serve','next pink'):recipes.map((x,i)=>btn(x.icon,x.name,`recipe:${i}`,`food-btn recipe-btn ${!s.free&&s.recipe===i?'selected':''}`)).join('')+btn('🎨','自由搭配料理','recipe:-1',`food-btn recipe-btn ${s.free?'selected':''}`)}</div></div>`;}
function hint(){const s=state,r=current(s);if(s.paid){speak('謝謝你，好好吃！點金幣，請下一位朋友。');return;}if(s.scene==='shop'){speak(s.ready?'料理做好了！點餐盤，請朋友吃。':`朋友想吃${r.name}。點籃子，我們去買菜。`);}else if(s.scene==='market'){const need=missing(s);if(need.length){const id=need[0];speak(`我們需要${foods[id][1]}。找找${stalls.find(x=>x.items.includes(id)).name}的圖案。`);}else speak('買好了！點平底鍋，回廚房。也可以繼續逛。');}else if(s.ready)speak('完成了！點餐盤，招待朋友。');else if(canCook(s))speak(`${steps[r.steps[s.step]][1]}。點三下，或在盤子上來回摸一摸。`);else speak(s.free?'選兩樣喜歡的食材，放進盤子。':`點食材，把${r.items.filter(id=>!s.loaded.includes(id)).map(id=>foods[id][1]).join('和')}放進盤子。`);}
function cooking(){const before=state.step;if(state.ready){navigate('shop');return;}if(!cook(state)){hint();return;}chime();particles(state.step===0?'💧':state.ready?'✨':before===1?'💫':'🌸');render();if(state.ready){flash('✨ '+current(state).icon,'完成了！好香呀。點餐盤，請朋友吃。');chime(true);}else if(state.step!==before)hint();save();}
function act(action){const [type,v]=action.split(':');switch(type){case'nav':navigate(v);break;case'stall':state.stall=Number(v);render();speak(stalls[state.stall].name);break;case'buy':if(add(state,v)){render();chime();particles(foods[v][0],50,70);flash(`${foods[v][0]} → 🧺`,`${foods[v][1]}放進籃子了。`);}else flash('🧺 💕','籃子裡已經有好多了，回廚房做料理吧。');break;case'find':state.stall=stalls.findIndex(s=>s.items.includes(v));navigate('market');break;case'load':if(loadFood(state,v)){render();chime();if(canCook(state))hint();}break;case'loaded':flash('✓','已經放好了。');break;case'recipe':selectRecipe(state,Number(v));render();speak(`來做${current(state).name}。點籃子去買菜。`);break;case'method':if(state.step===0&&!state.ready){state.method=v;render();}break;case'begin':{const need=missing(state);if(need.length)state.stall=stalls.findIndex(s=>s.items.includes(need[0]));navigate(recommended());break;}case'cook':cooking();break;case'stepHint':hint();break;case'serve':if(serve(state)){render();flash('💕 🌼','謝謝你，好好吃！這是送你的金幣和小花。');particles('💕',65,45);chime(true);}break;case'next':nextGuest(state);render();hint();break;case'decor':state.decor=(state.decor+1)%4;render();chime();break;case'apron':state.apron=(state.apron+1)%3;render();flash(['🌸','🎀','🌼'][state.apron],'換一個漂亮的小胸花。');break;}save();}
$('game').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&started){if(b.dataset.action==='cook'&&Date.now()-lastTap<220)return;act(b.dataset.action);}});
$('game').addEventListener('pointerdown',e=>{if(e.target.closest('#cookingArea')&&started){gesture={id:e.pointerId,x:e.clientX,y:e.clientY,distance:0};try{e.target.closest('#cookingArea').setPointerCapture(e.pointerId);}catch{}}});
$('game').addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId||!e.buttons)return;gesture.distance+=Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y);gesture.x=e.clientX;gesture.y=e.clientY;if(gesture.distance>65&&Date.now()-lastTap>250){gesture.distance=0;lastTap=Date.now();cooking();}});
window.addEventListener('pointerup',()=>gesture=null);window.addEventListener('pointercancel',()=>gesture=null);
$('start').onclick=()=>{started=true;$('welcome').classList.add('hidden');render();hint();chime();};$('voice').onclick=()=>{state.sound=!state.sound;if(!state.sound&&'speechSynthesis'in window)speechSynthesis.cancel();render();save();if(state.sound)hint();};$('help').onclick=()=>{hint();const b=document.querySelector('#scene .hint-ring')||document.querySelector('#scene .big-action')||document.querySelector('#tray .hint-ring');if(b){b.classList.add('hint-ring');particles('👆',50,65);}};$('parents').onclick=()=>$('guide').showModal();$('closeGuide').onclick=()=>$('guide').close();
document.addEventListener('visibilitychange',()=>{if(document.hidden){if('speechSynthesis'in window)speechSynthesis.cancel();audio?.suspend();}else if(state.sound)audio?.resume();});
render();
