import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import * as sim from '../simulation.js';
import * as model from '../model.js';
import * as art from '../art.js';
// Geometry must preserve the same ingredient and its texture through real cuts.
for(const id of sim.foodIds){
  for(const angle of [0,.3,1.2]){
    const s=sim.createWorkshop(),p=sim.addFood(s,id);p.angle=angle;const original=sim.area(p.poly);
    assert.equal(sim.cutFood(s,{x:15,y:10},{x:130,y:10}),0,'empty space is not a chop');
    const cut=sim.cutFood(s,{x:120,y:270},{x:610,y:270});
    if(['milk','flour','rice'].includes(id))assert.equal(cut,0);else assert.equal(cut,1);
    const total=s.board.reduce((n,p)=>n+sim.area(p.poly),0);assert(Math.abs(total-original)<1e-6,`${id} must retain its area`);
    assert(s.board.every(piece=>piece.id===id));
  }
}
const square=[{x:-100,y:-100},{x:100,y:-100},{x:100,y:100},{x:-100,y:100}];
for(const x of [-70,0,70]){const pieces=sim.splitPolygon(square,{x,y:-150},{x,y:150});assert(pieces);assert(Math.abs(pieces.reduce((n,p)=>n+sim.area(p),0)-40000)<1e-6);if(x)assert.notEqual(sim.area(pieces[0]),sim.area(pieces[1]),'cut position changes portion size');}
for(const method of ['pan','pot','blender'])for(const id of sim.foodIds){const work=sim.createWorkshop();work.method=method;sim.addFood(work,id);assert.equal(sim.transferToCooker(work),1);assert.equal(work.vessels[method][0].id,id);assert(sim.plateFood(work));assert.equal(work.plate[0].id,id);}
const physical=sim.createWorkshop();sim.addFood(physical,'carrot');sim.cutFood(physical,{x:150,y:270},{x:610,y:270});const uid=physical.board[0].uid;assert.equal(sim.transferToCooker(physical,uid),1);assert.equal(physical.board.length,1);assert.equal(physical.vessels.pan.length,1);assert.equal(sim.transferToCooker(physical,uid),0,'the same piece cannot duplicate');
sim.transferToCooker(physical);assert.equal(physical.vessels.pan.length,2);for(let i=0;i<200;i++)sim.stepWorkshop(physical,.05);assert.equal(physical.vessels.pan[0].cooked,0,'stirring/time without fire cannot cook');physical.heat.pan=1;for(let i=0;i<220;i++)sim.stepWorkshop(physical,.05);assert(physical.vessels.pan.every(p=>p.cooked===1));assert.equal(physical.station,'board','cooking never advances the workspace automatically');physical.heat.pan=0;const p=physical.vessels.pan[0],before={x:p.x,y:p.y};sim.pushFood(physical,{x:p.x-12,y:p.y},{x:p.x,y:p.y});sim.stepWorkshop(physical,.05);assert(p.x!==before.x||p.y!==before.y,'the spoon moves the actual piece');
assert(sim.plateFood(physical));assert.equal(physical.plate.length,2);assert.equal(physical.vessels.pan.length,0);assert(!sim.plateFood(physical),'empty cookware cannot duplicate a plate');
const soup=sim.createWorkshop();soup.method='pot';sim.addFood(soup,'tomato');sim.transferToCooker(soup);sim.addLiquid(soup,'water',1);assert(sim.plateFood(soup));assert.equal(soup.plateLiquid,1);assert.equal(soup.liquid.pot,0,'water pours out with soup');
const mixer=sim.createWorkshop();mixer.method='blender';sim.addFood(mixer,'strawberry');sim.transferToCooker(mixer);for(let i=0;i<100;i++)sim.stepWorkshop(mixer,.05);assert.equal(mixer.blend,0);mixer.blending=true;for(let i=0;i<60;i++)sim.stepWorkshop(mixer,.05);assert(mixer.blend>.95);mixer.blending=false;const saved=mixer.blend;for(let i=0;i<100;i++)sim.stepWorkshop(mixer,.05);assert.equal(mixer.blend,saved);sim.addFood(mixer,'milk');sim.transferToCooker(mixer);sim.stepWorkshop(mixer,.05);assert.equal(mixer.vessels.blender[1].blended,0,'new food needs to be blended');assert(mixer.blend<saved);assert(mixer.vessels.blender[1].poured,'the milk carton does not go into the jar');
const batter=sim.createWorkshop();sim.addFood(batter,'flour');sim.addFood(batter,'milk');sim.transferToCooker(batter);assert(batter.vessels.pan.every(p=>p.pancake));const pancake=batter.vessels.pan[0];const oldX=pancake.x;sim.pushFood(batter,{x:pancake.x-15,y:pancake.y},{x:pancake.x,y:pancake.y});sim.stepWorkshop(batter,.05);assert.notEqual(pancake.x,oldX,'batter also responds to the spatula');batter.vessels.pan.forEach(p=>{p.x=350;p.y=245;p.vx=0;p.vy=0;});for(let i=0;i<30;i++)sim.stepWorkshop(batter,.05);assert(Math.hypot(batter.vessels.pan[0].x-batter.vessels.pan[1].x,batter.vessels.pan[0].y-batter.vessels.pan[1].y)>40,'food contact prevents an unreadable pile');
function setup(search='?muted=1'){
  const elements=new Map(),timers=new Map(),frames=[],storage=new Map();let tid=0,loops=0,hardware=0;
  function element(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',hidden:false,disabled:false,open:false,dataset:{},listeners:{},style:{},classList:{add(){},remove(){}},setAttribute(){},addEventListener(type,fn){this.listeners[type]=fn;},querySelector(){return null;},setPointerCapture(){},hasPointerCapture(){return true;},releasePointerCapture(){},showModal(){this.open=true;},close(){this.open=false;},getBoundingClientRect(){return id==='dropCooker'?{left:550,top:400,right:700,bottom:540,width:150,height:140}:id==='friend'?{left:550,top:200,right:700,bottom:500,width:150,height:300}:{left:0,top:0,right:720,bottom:540,width:720,height:540};}});return elements.get(id);}
  const parameter=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}});
  function node(){let running=false;return {gain:parameter(),frequency:parameter(),connect(){},disconnect(){},start(){if(this.loop||this.type==='sawtooth'){running=true;loops++;}},stop(){if(running){loops--;running=false;}this.onended?.();}};}
  class AudioContext{constructor(){hardware++;this.state='running';this.currentTime=0;this.sampleRate=128;this.destination={};}resume(){}suspend(){}createOscillator(){return node();}createGain(){return node();}createBufferSource(){return node();}createBiquadFilter(){return node();}createBuffer(){return {getChannelData:()=>new Float32Array(128)};}}
  const context={...sim,...model,...art,console,URLSearchParams,location:{search},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{hidden:false,getElementById:element,addEventListener(type,fn){this[type]=fn;}},window:{AudioContext},createNarrator:()=>({speak(){},stop(){}}),createRenderer:()=>Promise.resolve({draw(){}}),requestAnimationFrame:fn=>frames.push(fn),setTimeout:(fn,ms)=>{timers.set(++tid,{fn,ms});return tid;},clearTimeout:id=>timers.delete(id)};
  const source=readFileSync(new URL('../game.js',import.meta.url),'utf8').replace(/^import .*?;\n/gm,'')+'\n;globalThis.api={act,read:()=>({s,prefs,gesture,celebrating}),active:()=>activeTool};';vm.runInNewContext(source,context);
  const pointer=(type,x,y,extras={})=>element('worktop').listeners[type]({pointerId:1,isPrimary:true,button:0,clientX:x,clientY:y,...extras});
  const flush=ms=>{const entry=[...timers].find(([,t])=>t.ms===ms);assert(entry,`missing ${ms}ms timer`);timers.delete(entry[0]);entry[1].fn();};
  return {api:context.api,element,pointer,flush,context,storage,loops:()=>loops,hardware:()=>hardware,frames};
}
const q=setup();q.element('start').onclick();q.api.act('food:tomato');q.pointer('pointerdown',360,270,{isPrimary:false});q.pointer('pointerup',360,270,{pointerId:2});assert.equal(q.api.read().s.board.length,1,'secondary pointers cannot cut');q.pointer('pointerdown',30,30);q.pointer('pointerup',90,30);assert.equal(q.api.read().s.board.length,1);
q.pointer('pointerdown',190,270);q.pointer('pointermove',530,270);q.pointer('pointerup',530,270);assert.equal(q.api.read().s.board.length,2,'one stroke cuts once');
q.pointer('pointerdown',160,310);q.pointer('pointercancel',540,310);assert.equal(q.api.read().s.board.length,2,'cancel does not chop');
q.api.act('tool:hand');let piece=q.api.read().s.board[0],original={x:piece.x,y:piece.y};q.pointer('pointerdown',piece.x,piece.y);q.pointer('pointermove',piece.x+60,piece.y);q.pointer('pointercancel',piece.x+60,piece.y);assert.equal(piece.x,original.x);assert.equal(piece.y,original.y);
q.pointer('pointerdown',piece.x,piece.y);q.pointer('pointermove',620,470);q.pointer('pointerup',620,470);assert.equal(q.api.read().s.board.length,1);assert.equal(q.api.read().s.vessels.pan.length,1);
q.api.act('station:fridge');q.api.act('food:broccoli');assert.equal(q.api.read().s.board.length,2);assert.equal(q.api.read().s.vessels.pan.length,1,'adding food keeps cooking contents');q.api.act('transfer');q.flush(480);assert.equal(q.api.read().s.station,'stove');assert.equal(q.api.read().s.vessels.pan.length,3);
q.api.act('heat');q.api.act('liquid:oil');q.api.act('salt');assert(q.api.read().s.heat.pan>0);assert(q.api.read().s.liquid.pan>0);assert(q.api.read().s.seasoning>0);q.api.act('plate');assert.equal(q.api.read().s.station,'serve');q.api.act('feed');q.api.act('feed');assert.equal(q.api.read().prefs.served,1);q.flush(1800);assert.equal(q.api.read().s.station,'fridge');assert.equal(q.api.read().s.plate.length,0);assert.equal(q.hardware(),0);
const motor=setup('');motor.element('start').onclick();motor.api.act('food:strawberry');motor.api.act('station:stove');motor.api.act('method:blender');motor.api.act('station:board');motor.api.act('transfer');motor.flush(480);
const event={pointerId:1,isPrimary:true,target:{closest:()=>({})}};motor.element('tray').listeners.pointerdown(event);assert(motor.api.read().s.blending);assert.equal(motor.loops(),1);motor.element('tray').listeners.pointerup(event);assert(!motor.api.read().s.blending);assert.equal(motor.loops(),0);motor.element('tray').listeners.pointerdown(event);motor.context.document.hidden=true;motor.context.document.visibilitychange();assert(!motor.api.read().s.blending);assert.equal(motor.loops(),0);motor.context.document.hidden=false;motor.context.document.visibilitychange();assert.equal(motor.loops(),0);
const sound=setup('');sound.element('start').onclick();sound.api.act('food:carrot');sound.api.act('transfer');sound.flush(480);sound.api.act('heat');assert.equal(sound.loops(),1);sound.element('voice').onclick();assert.equal(sound.loops(),0);sound.element('voice').onclick();assert.equal(sound.loops(),1);sound.element('parents').onclick();assert.equal(sound.loops(),0);sound.element('closeGuide').onclick();sound.element('guide').listeners.close();assert.equal(sound.loops(),1);sound.api.act('station:fridge');assert.equal(sound.loops(),0,'moving away quiets the worktop');sound.api.act('station:stove');assert.equal(sound.loops(),1);sound.api.act('plate');assert.equal(sound.loops(),0);
console.log('PASS: real cut geometry and area conservation, independent pieces and transfers, continuous heat, physical stirring/batter, blender hold/release, free workspaces, cancelled/secondary gestures, serving and audio lifecycle. Audio mocked.');
