// 鋼鐵黃昏：全部關卡的資料（劇情＋路線＋任務），一關一個物件，順序＝第幾關
//   combat.js 讀這裡組出 STAGES；route（沿街推進的遭遇戰）由 encounter.js 的 parse() 解析
//
// ---- 一關的欄位
//   name／en：關名；tip：開場橫幅的小字；music：配樂 1～6（6＝最終曲）；tier：難度 1～6（combat.js 的 TIER，同時出手台數、傷害…）
//   brief：出擊前的簡報卡（幾行字）；start：開機完成後的無線電對白；end：過關後、結算前的對白
//   對白一行＝[說話的人, 內容, NOW?]：NOW＝戰鬥喊話，插隊馬上播（沒寫就排隊）
//   route：遭遇戰（沿街推進，見下面）；沒有 route 的關用 groups（舊式：在你周圍一批批空降）
//
// ---- route 的欄位（沿著固定路線推進，每到一個路口就有伏兵）
// 伏兵寫法：'種類@出現方式*數量'，用空白隔開
//   far＝一開始就停在遠處（狙擊目標）、out＝從前方街上開過來、side＝從封死的支路衝出來、drop＝從天而降到前方街上、
//   roof＝降落在前方樓頂、rise＝直升機從樓後面升起、ring＝（終點區）從四周的街上包過來
//   at＝這一區的錨點（路線第幾個頂點）；pre＝走過來就看得到的遠處目標；amb＝伏擊；amb2、amb3＝打到剩一兩台時的增援（第二、三波）
//   cp＝打到第幾區記一個檢查點；arena＝終點周圍多少公尺不封路；fin＝終點區提早多少公尺觸發；par＝評價用標準時間（秒）；over＝上一波還剩幾台就叫下一波
//   cp 可以是一個數字或陣列（例如 [3, 6]）：清完第幾區記檢查點
//
// ---- 每一區（secs）另外可以加：
//   go：這一區變成下一個目標時講的話；lines：開打（伏兵出現）時講的話；clear：這一區清完時講的話
//   hold：守住幾秒（期間 amb、amb2、amb3 輪流來，gap 秒或剩 over 台就叫下一波；時間到、敵人清光才算過）
//   beats：[{t: 開戰秒數, lines: 插播對白, spawn: 額外增援字串}]；boss.halfWave／lowWave 在血量轉折時叫增援，沿用在場上限與出場預警
//   boss：{ kind: 'ace'|'heavy'|'grunt', name: '黑犬', ap: 血量倍率, where: 'drop'|'roof'|…, flee: 0.3（剩三成就撤退，不會被打死）,
//           half: [...]（剩一半時的對白）, low: [...]（剩兩成半）, fled: [...]（撤退時）, down: [...]（被打倒的那一刻） }
//           ——跟第一波一起出現，畫面上方有血條；頭目倒下或撤退後，還沒出來的後續波次取消；low 在 max(兩成半, flee＋一成) 時講
//   每一區一定要有 amb（第一波）；clear 的對白是排隊播的，下一區很快開打時，下一區的 lines（插隊）會先講
//   同一棟大樓不要在兩關都當目標（玩家會發現打過了）
//   targets：[{ x, z, name: '砲兵指揮所' }] 要打爛的城市大樓（找 (x,z) 附近 40 m 內最近的一棟）；這一區要樓都倒了、敵人清光才算過
//
// ---- 城市：路口在 120 m 格線上（x、z＝0、±120、±240…，戰車能開到 ±600），市中心 |x|,|z|<120 是廣場／公園／廢墟

export const OP = '白鷺（指揮所）', ME = '零號', EN = '獵犬軍團通訊', DOG = '黑犬（獵犬軍團）', WOLF = '灰狼（獵犬軍團司令）', ALLY = '第三裝甲連', NOW = true;

export const STAGE_DATA = [
  // ================================================================ 第 1 關
  //   沿大街往東推進（教學關：射擊、Tab、懸浮、閃避、飛彈、光劍、光波砲、覺醒一區教一樣），拆掉獵犬的中繼站，到東區公園和第三裝甲連會合
  { name: '初陣', en: 'FIRST SORTIE', tip: '跟著藍色光柱沿街推進——左鍵射擊，Tab 換目標，戰車一發就爆', music: 1, tier: 1,
    brief: ['昨晚，零號在第七機庫啟動了試驗機「蒼焰」，把獵犬軍團趕出了基地。',
      '首都東區，第三裝甲連困在大街盡頭的公園，彈藥只剩兩成。',
      '獵犬在沿路的大樓架了中繼站，替砲兵報他們的位置。',
      '沿大街往東推進，拆掉中繼站，和裝甲連會合。'],
    start: [[ALLY, '三號車中彈！路口封死了，誰能聽見就回答！', NOW], [OP, '零號，裝甲連只剩兩成彈藥。跟著光柱，打開東區的路。'], [ME, '位置收到。我來了。']],
    end: [[ALLY, '原來蒼焰是一台機體……我們得救了。'], [ALLY, '第三裝甲連連長。駕駛員，報上名字。'], [ME, '零號。'], [OP, '裝甲連，跟著蒼焰撤出東區。']],
    route:
    { cp: [4, 8], arena: 130, fin: 60, par: 520, over: 1,
      pts: [[-600, -660], [-600, -480], [-360, -480], [-360, -360], [-240, -360], [-120, -360], [-120, -240], [0, -240], [120, -240], [240, -240], [360, -240], [480, -240], [480, -360], [480, -480], [540, -480]],
      secs: [
        { at: 1, pre: 'tank@far*2', amb: 'tank@out*2 tank@side', amb2: 'tank@out*2', tip: '轉角後面有戰車——左鍵射擊，先開火的贏',
          lines: [[OP, '前方路口，獵犬的戰車。先開火。']] },
        { at: 2, amb: 'tank@side grunt@drop*2 tank@out', amb2: 'tank@out*2 grunt@drop', amb3: 'grunt@drop tank@side', tip: '敵機從天而降——Tab 換目標，落地前就打',
          go: [[ALLY, '……這裡是第三裝甲連……有人聽得到嗎……'], [OP, '聽得到。撐住，我們過去。']],
          lines: [[OP, '上空有機體降落，是獵犬的量產機。']] },
        { at: 3, amb: 'grunt@roof tank@out tank@side', amb2: 'grunt@roof tank@out*2', tip: '樓頂也會有敵機——往上看，空白鍵按住能懸浮',
          lines: [[OP, '樓頂有一台。抬頭。']], clear: [[OP, '這一帶清掉了。你學得很快。']] },
        { at: 4, amb: 'tank@side*2 tank@out grunt@drop', amb2: 'tank@out*2 grunt@side', tip: '看到砲彈飛過來，點一下 Shift 閃開',
          go: [[OP, '下個路口很窄，支路裡可能藏了戰車。']], lines: [[OP, '支路有戰車！']], clear: [[ME, '蒼焰還撐得住。']] },
        { at: 5, pre: 'tank@far*3', amb: 'tank@out*2 grunt@drop', amb2: 'tank@out*3', amb3: 'grunt@roof tank@out*2', tip: '遠處那排戰車——右鍵按住鎖定多台，放開一起射',
          go: [[OP, '前面停了一排戰車。用飛彈。']] },
        { at: 6, amb: 'heli@rise tank@side tank@out', amb2: 'heli@rise tank@out*2 grunt@drop', tip: '直升機從樓後面升起——飛彈追得上它',
          go: [[ALLY, '砲彈又落在我們頭上！他們看得見我們！'], [OP, '有人在替砲兵報位置。我在找。']],
          lines: [[OP, '直升機，從樓後面上來了。']] },
        { at: 7, amb: 'grunt@side*2 tank@out', amb2: 'grunt@drop tank@out*2', tip: '敵機貼近了——按 F 光劍突擊',
          lines: [[OP, '機體從支路貼過來了。']], clear: [[OP, '找到了。前面兩棟樓，中繼站和觀測所。']] },
        { at: 8, amb: 'tank@out grunt@roof tank@side', amb2: 'tank@out*2 grunt@drop', tip: '按 E 發射光波砲——一道光能打穿兩棟樓',
          targets: [{ x: 81, z: -163, name: '中繼站' }, { x: 161, z: -158, name: '觀測所' }],
          go: [[OP, '拆掉這兩棟樓，砲兵就看不見了。']], lines: [[EN, '中繼站遭到攻擊！附近的車過去支援！']],
          clear: [[ALLY, '……砲擊停了！是你們幹的？'], [OP, '是蒼焰。裝甲連，報位置。']] },
        { at: 10, amb: 'tank@side grunt@drop tank@side grunt@roof tank@out', amb2: 'tank@out*3 grunt@drop', amb3: 'heli@rise tank@side*2', tip: '支路衝出來的最近——先打牠',
          go: [[ALLY, '東區公園，還有四輛能動。快點來。']], lines: [[EN, '聯邦的新型機往公園去了。攔住它。']] },
        { at: 11, pre: 'tank@far*2', amb: 'grunt@drop tank@side*2', amb2: 'heli@rise tank@out*2 grunt@drop', tip: 'Shift 按住衝刺——拉近距離再打',
          lines: [[ALLY, '轉角那幾輛在朝公園開砲！先解決它們！']], clear: [[ALLY, '打得好！那幾輛一直在轟我們。']] },
        { at: 12, amb: 'heli@rise tank@out*2 grunt@drop tank@side', amb2: 'grunt@roof tank@out*2 heli@rise', amb3: 'grunt@drop tank@side*2', tip: 'OD 槽滿了按 Q 覺醒——十秒內全面變強',
          go: [[OP, '公園就在前面。獵犬的兵力全往那裡去了。']], lines: [[ALLY, '他們又衝上來了！撐不了多久！']], clear: [[ME, '快到了。再撐一下。']] },
        { at: 14, amb: 'tank@ring*4 grunt@drop*2', amb2: 'grunt@roof tank@ring*3 grunt@drop heli@rise', amb3: 'grunt@drop*2 tank@ring*3', tip: '最後一區：四面八方都有，清光就過關',
          beats: [{ t: 18, lines: [[ALLY, '他們繞到後面了！'], [OP, '側翼有降落訊號。別只盯著正面。']], spawn: 'grunt@side' }],
          lines: [[ALLY, '看到你了！全車開火，跟著那台機體打！']] },
      ] } },
  // ================================================================ 第 2 關
  //   帶著車隊往西突圍：拆干擾站讓撤離直升機進得來、打倒包圍網的指揮機（小頭目），最後守住中央廣場到直升機載完市民
  { name: '包圍網', en: 'ENCIRCLED', tip: '打穿包圍網，守住中央廣場——右鍵按住一次鎖多台', music: 2, tier: 2,
    brief: ['會合之後不到一小時，獵犬軍團封住了東區所有出口。',
      '兩千多名市民跟著裝甲連的車隊，困在包圍圈裡。',
      '聯邦派出撤離直升機，降落點是中央廣場。',
      '打穿包圍網，守住廣場，直到最後一架直升機起飛。'],
    start: [[OP, '包圍網在收緊。零號，你打頭陣。'], [ALLY, '裝甲連殿後，市民的車夾在中間。走吧。']],
    end: [[OP, '最後一架起飛了。市民全部撤出。'], [ALLY, '小子，開得不錯。這條命算你救的。'], [ME, '城裡還有人沒撤出來。'], [OP, '我知道。明天繼續。']],
    route:
    { cp: [4, 7, 11], arena: 175, fin: 70, par: 620, over: 2,
      pts: [[660, 600], [480, 600], [360, 600], [360, 480], [240, 480], [120, 480], [120, 360], [0, 360], [-120, 360], [-240, 360], [-240, 240], [-360, 240], [-360, 120], [-240, 120], [-240, 0], [-120, 0], [0, 0]],
      secs: [
        { at: 1, pre: 'tank@far*3', amb: 'heli@rise tank@side tank@out', amb2: 'tank@out*3', tip: '前面三台排成一列——右鍵按住一次鎖光',
          lines: [[ALLY, '前面路口有戰車擋路！']], clear: [[OP, '路開了。車隊，跟上。']] },
        { at: 2, amb: 'tank@out*2 tank@side grunt@drop', amb2: 'grunt@drop tank@side tank@out*2',
          lines: [[EN, '聯邦車隊往西走了。各隊跟上去。']] },
        { at: 3, amb: 'grunt@side heli@rise tank@out*2', amb2: 'heli@rise tank@out*2 grunt@roof', tip: '直升機從樓後面升起來',
          lines: [[OP, '直升機。先打掉，別讓它盯上車隊。']], clear: [[ALLY, '車隊沒事。繼續走。']] },
        { at: 4, amb: 'tank@side*2 grunt@drop grunt@roof', amb2: 'heli@rise tank@out*2', amb3: 'grunt@drop*2 tank@side',
          lines: [[ALLY, '後面也有！他們從兩邊夾過來了！']] },
        { at: 6, pre: 'tank@far*2', amb: 'grunt@side grunt@roof tank@out*2', amb2: 'tank@out*3 heli@rise', tip: '遠處有戰車守著轉角',
          go: [[OP, '撤離直升機的頻道一直有雜訊。']], clear: [[OP, '找到了。有人在干擾，訊號從前面兩棟樓出來。']] },
        { at: 7, amb: 'grunt@roof tank@side tank@out', amb2: 'heli@rise grunt@drop tank@out*2', tip: '樓頂架著干擾站——光波砲（E）一次拆一棟',
          targets: [{ x: -36, z: 420, name: '干擾站' }, { x: -40, z: 324, name: '干擾站' }],
          go: [[OP, '拆掉干擾站，直升機才進得來。']], lines: [[EN, '干擾站遭到攻擊！快派人過去！']],
          clear: [[OP, '頻道通了。撤離直升機，降落點中央廣場。']] },
        { at: 8, pre: 'tank@far', amb: 'heli@rise*2 tank@side*2 grunt@drop', amb2: 'grunt@roof tank@out*3',
          lines: [[EN, '聯邦要從廣場撤人。把路堵死。']] },
        { at: 10, amb: 'tank@side*2 grunt@drop tank@out', amb2: 'tank@out*2 grunt@roof', tip: '頭上有血條的是指揮機——集中打它',
          boss: { kind: 'grunt', name: '包圍網指揮機', ap: 2.5, where: 'drop',
            half: [[EN, '指揮機受損！各車靠過來掩護！']], low: [[OP, '它快倒了。別讓它跑回去。']] },
          go: [[OP, '前面路口有一台指揮機，包圍網聽它調度。']], lines: [[EN, '聯邦的新型機？全隊，把它圍住。']],
          clear: [[ALLY, '指揮機倒了！包圍網開了個缺口！']] },
        { at: 12, amb: 'tank@out*3 grunt@roof grunt@drop', amb2: 'tank@side*2 grunt@drop heli@rise',
          go: [[OP, '趁他們亂，從缺口穿出去。']], lines: [[EN, '指揮機失聯！各隊自行攔截！']] },
        { at: 14, amb: 'tank@out*4 grunt@drop', amb2: 'tank@side*2 heli@rise grunt@roof', amb3: 'heli@rise*2 tank@out*2', tip: '車隊從前面衝過來——用飛彈',
          lines: [[ALLY, '戰車隊從正面衝過來了！']], clear: [[OP, '廣場就在前面。直升機兩分鐘後到。']] },
        { at: 15, amb: 'grunt@drop*2 heli@rise tank@out', amb2: 'tank@out*2 grunt@roof heli@rise',
          lines: [[EN, '全軍往中央廣場集合！']], clear: [[ALLY, '車隊進廣場了！市民在下車！']] },
        { at: 16, hold: 75, gap: 18, amb: 'tank@ring*4 grunt@drop*2 heli@rise', amb2: 'grunt@drop*2 heli@rise*2 tank@ring*2', amb3: 'grunt@roof grunt@drop*2 heli@rise tank@ring*3', tip: '守住廣場——直升機載完市民才會撤',
          beats: [{ t: 25, lines: [[OP, '第二架進場了。最後一批人還在跑向降落點。'], [EN, '從側街切進去，別跟蒼焰正面打！']], spawn: 'grunt@side' },
            { t: 58, lines: [[ALLY, '最後一架正在裝人！零號，別讓他們靠近！'], [ME, '我還在。繼續上人。']] }],
          go: [[OP, '直升機到了。守住廣場，直到最後一架起飛。']], lines: [[OP, '第一架降落。別讓獵犬靠近廣場。']] },
      ] } },
  // ================================================================ 第 3 關
  // 西區：從西邊切進來，繞河濱公園一圈拆掉三個砲兵觀測所，最後在公園中間守住臨時醫院
  { name: '救援', en: 'RESCUE', tip: '打掉樓頂的觀測所：琥珀色框的大樓，打到整棟倒下', music: 2, tier: 2,
    brief: ['包圍網打開了，可是西區的河濱公園還困著上千名難民。', '公園裡的臨時醫院一直挨砲擊，砲彈由高樓頂上的觀測所導引。', '先打掉觀測所，再守住醫院，讓難民車隊從西河大橋撤出。'],
    start: [[OP, '零號，這裡是白鷺。醫院每三分鐘挨一輪砲。'], [OP, '觀測所會用琥珀色框標出來，整棟打倒才算數。']],
    end: [[ALLY, '最後一輛車過橋了。蒼焰，這次欠你一次。'], [OP, '難民全數撤出。零號，回來補給。']],
    route:
    { cp: [4, 8], arena: 130, fin: 90, par: 600, over: 2,
      pts: [[-690, 240], [-600, 240], [-600, 120], [-600, 0], [-600, -120], [-480, -120], [-360, -120], [-240, -120], [-240, 0], [-240, 120], [-360, 120], [-360, 0], [-420, 0]],
      secs: [
        { at: 1, amb: 'tank@out*2 tank@side heli@rise', amb2: 'tank@out*2 grunt@drop', tip: '直升機低空繞圈：鎖定它，用飛彈打',
          lines: [[OP, '路口有戰車守著，清掉再往前。']] },
        { at: 2, pre: 'tank@far*2', amb: 'grunt@drop tank@side*2', amb2: 'grunt@roof tank@out*2',
          go: [[OP, '前面街上停著兩台戰車，先從遠處打掉。']] },
        { at: 3, targets: [{ x: -661, z: -61, name: '砲兵觀測所' }], amb: 'grunt@roof tank@out*2 heli@rise', amb2: 'tank@side*2 grunt@drop', tip: '打倒琥珀色框的大樓：樓倒了、敵人清光才算過',
          go: [[OP, '第一個觀測所就在前方路口，框起來那棟。']], lines: [[EN, '觀測所遭到攻擊！附近部隊回防！']],
          clear: [[OP, '觀測所倒了。醫院回報，砲彈打偏了。']] },
        { at: 4, amb: 'tank@side tank@out*2 grunt@drop', amb2: 'heli@rise*2 tank@out' },
        { at: 5, targets: [{ x: -522, z: -157, name: '砲兵觀測所' }], amb: 'grunt@roof grunt@drop tank@out', amb2: 'heli@rise tank@side*2',
          go: [[OP, '路旁那片樹林就是河濱公園，醫院在裡面。'], [OP, '第二個觀測所在下一個路口。']],
          clear: [[OP, '第二個觀測所摧毀，剩最後一個。']] },
        { at: 6, pre: 'tank@far*2', amb: 'tank@side*2 grunt@drop heli@rise', amb2: 'grunt@roof tank@out*2',
          lines: [[ALLY, '這裡是醫院，砲彈又落下來了！']] },
        { at: 7, targets: [{ x: -320, z: -60, name: '砲兵觀測塔' }], amb: 'grunt@side tank@out*2 grunt@roof', amb2: 'heli@rise tank@side*2', amb3: 'grunt@drop*2 tank@out', tip: '高樓比較耐打：對準同一棟連續射擊',
          go: [[OP, '最後一個在前方的高樓頂上，比較耐打。']], lines: [[EN, '觀測塔告急！把那台藍色的擋下來！']],
          clear: [[OP, '觀測所全毀，砲擊停了。'], [ALLY, '醫院安靜了。車隊開始上人。']] },
        { at: 8, amb: 'tank@out*2 tank@side grunt@drop', amb2: 'grunt@roof heli@rise tank@out*2',
          lines: [[EN, '砲兵失去觀測。地面部隊，直接攻進醫院。'], [OP, '他們改派地面部隊了。擋在醫院前面。']] },
        { at: 9, amb: 'heli@rise*2 grunt@side tank@out', amb2: 'tank@out*2 grunt@drop grunt@roof',
          go: [[OP, '掉頭繞回公園，沿路清掉追兵。']] },
        { at: 10, amb: 'grunt@drop*2 tank@side*2', amb2: 'heli@rise tank@out*2 grunt@roof',
          go: [[ALLY, '車隊裝好了。蒼焰，公園交給你守。']],
          clear: [[OP, '車隊一出發，敵人就會圍過來。']] },
        { at: 12, hold: 75, gap: 15, amb: 'tank@ring*3 grunt@drop*2', amb2: 'heli@rise*2 tank@ring*2 grunt@drop', amb3: 'grunt@drop*2 tank@ring*2 heli@rise', tip: '守住醫院：計時結束前，敵人會從四面八方來',
          beats: [{ t: 24, lines: [[ALLY, '救護車還沒出醫院！有傷員不能自己走！'], [EN, '重裝機上前。把藍色的逼離橋口。']], spawn: 'heavy@drop' },
            { t: 57, lines: [[ALLY, '最後一輛救護車上橋了。再給我們十八秒！']] }],
          lines: [[ALLY, '車隊出發！一分多鐘才過得了橋。'], [EN, '難民車隊在移動。全部隊，追！']] },
      ] } },
  // ================================================================ 第 4 關
  // 西南角切進來往北：長直路上的遠程自走砲、重裝機首次登場，打掉射控雷達、彈藥庫，最後在北邊打倒砲兵指揮所
  { battlefield: 'valley', fieldLabel: '山谷砲兵陣地', name: '重砲', en: 'HEAVY GUNS', tip: '新敵人：重裝機——響飛彈警報就點 SHIFT 閃', music: 3, tier: 3,
    brief: ['難民撤出去了。獵犬軍團的重砲群轉向北部山谷，開始砲擊聯邦防線。', '重砲群由新型重裝機護衛。重裝機停在遠處，一次射出整排飛彈。', '沿山谷運輸道路找出重砲群，利用岩壁遮斷飛彈，打掉它的彈藥庫和指揮所。'],
    start: [[OP, '重砲群一直在換陣地，我們只抓到大概位置。'], [OP, '聽到飛彈警報就點 SHIFT 側閃。']],
    end: [[OP, '指揮所倒了，重砲群散了。北區的砲擊全停。'], [EN, '……黑犬隊長，重砲群被那台藍色機體打掉了。'], [DOG, '蒼焰嗎。下一次，我親自上。']],
    route:
    { cp: [4, 8], arena: 110, fin: 90, par: 680, over: 2,
      pts: [[-690, -240], [-600, -240], [-480, -240], [-480, -120], [-480, 0], [-480, 120], [-480, 240], [-480, 360], [-360, 360], [-240, 360], [-240, 480], [-120, 480], [0, 480]],
      secs: [
        { at: 1, amb: 'tank@out*2 tank@side grunt@drop', amb2: 'heli@rise tank@out*2', amb3: 'grunt@drop tank@out',
          lines: [[OP, '接觸。這一帶是重砲群的外圍警戒。']] },
        { at: 2, pre: 'tank@far*2', amb: 'grunt@drop tank@side*2', amb2: 'tank@out*2 grunt@roof', amb3: 'heli@rise*2',
          go: [[OP, '轉角停著兩台戰車，先從遠處打掉。']] },
        { at: 3, pre: 'tank@far*2', amb: 'grunt@roof tank@side*2 grunt@drop', amb2: 'tank@out*2 heli@rise', amb3: 'heli@rise grunt@drop',
          go: [[ALLY, '北邊的砲擊一直沒停，我們動不了。']] },
        { at: 4, amb: 'heavy@drop tank@out*2', amb2: 'grunt@drop tank@side*2', amb3: 'tank@out*2 heli@rise', tip: '重裝機：飛彈警報一響就點 SHIFT 閃開',
          lines: [[OP, '重裝機降落！警報一響就點 SHIFT。']],
          clear: [[OP, '重裝機動作慢。繞著它打，別站著對射。']] },
        { at: 5, amb: 'heavy@roof tank@side*2 heli@rise', amb2: 'grunt@drop tank@out*2', amb3: 'grunt@roof tank@out',
          lines: [[EN, '前哨遭遇蒼焰。重裝機就位，拖住它。']] },
        { at: 6, targets: [{ x: -541, z: 299, name: '射控雷達站' }], amb: 'grunt@roof heavy@drop tank@out', amb2: 'tank@side*2 heli@rise*2', amb3: 'grunt@drop tank@out', tip: '打倒射控雷達站，重砲就打不準',
          go: [[OP, '找到了。重砲群的射控雷達站就在前方路口。']],
          clear: [[OP, '雷達站倒了。重砲的彈著點開始散掉。']] },
        { at: 7, amb: 'tank@side*2 grunt@drop heavy@drop', amb2: 'grunt@roof tank@out*2', amb3: 'heli@rise tank@side',
          go: [[EN, '射控雷達失聯！自走砲改用直接瞄準！']] },
        { at: 8, pre: 'tank@far*3', amb: 'heavy@roof tank@side grunt@drop', amb2: 'tank@out*2 heli@rise grunt@drop', amb3: 'heavy@drop grunt@roof', tip: '街尾的自走砲會先開火：拉開距離，一台一台打',
          go: [[OP, '街尾那一排就是自走砲，從遠處先打掉。']],
          clear: [[ALLY, '砲擊少了一半！小子，繼續。']] },
        { at: 9, amb: 'grunt@side heavy@drop tank@out*2', amb2: 'heli@rise*2 tank@side grunt@roof', amb3: 'grunt@drop*2',
          lines: [[EN, '自走砲隊全滅！指揮所，請求增援！']] },
        { at: 10, targets: [{ x: -180, z: 419, name: '彈藥庫' }], amb: 'heavy@drop grunt@roof tank@side*2', amb2: 'tank@out*2 grunt@drop heli@rise', amb3: 'grunt@roof heli@rise', tip: '彈藥庫很耐打：按 E 用光波砲一次打穿',
          go: [[OP, '前面那棟大樓是重砲群的彈藥庫，整棟打倒。']],
          clear: [[OP, '彈藥庫倒了。重砲群只剩指揮所。']] },
        { at: 11, pre: 'tank@far*2', amb: 'heavy@roof grunt@drop tank@side', amb2: 'heavy@drop tank@out*2', amb3: 'grunt@drop*2 tank@out',
          go: [[EN, '指揮所前方佈防！重裝機全部上前！']] },
        { at: 12, targets: [{ x: -37, z: 539, name: '砲兵指揮所' }, { x: 39, z: 421, name: '通訊塔' }], amb: 'tank@ring*3 heavy@drop grunt@drop', amb2: 'heavy@drop tank@ring*2 heli@rise', amb3: 'grunt@drop*2 tank@ring*2 heli@rise', tip: '最後一區：打倒指揮所和通訊塔，敵人清光就過關',
          beats: [{ t: 24, lines: [[EN, '指揮所準備撤離，重裝隊掩護！'], [OP, '他們在拖時間。抓住重裝機換射角的空檔，打指揮所。']], spawn: 'grunt@side' }],
          go: [[OP, '指揮所就在前面。連通訊塔一起打倒。']], lines: [[EN, '指揮所遭到攻擊！全員回防！']] },
      ] } },
  // ================================================================ 第 5 關
  // 北邊繞一大圈到北郊山麓林地：黑犬隊的王牌機首次登場；中途黑犬試探（剩三成撤退），公園裡再打一次（又撤退，活到第 9 關）
  { battlefield: 'forest', fieldLabel: '山麓林地', name: '黑犬', en: 'BLACK DOG', tip: '新敵人：王牌機——槍口發光就閃，靠近會拔劍', music: 4, tier: 4,
    brief: ['重砲群散了以後，獵犬軍團的通訊裡一直出現同一個代號：黑犬。', '他在第七機庫被你打到彈射逃生，這次開著新的王牌機回來。', '黑犬把第三裝甲連圍在北郊山麓林地，公開呼叫蒼焰過去。', '王牌機的槍口一發光就要閃。貼得太近，他會拔劍。'],
    start: [[DOG, '蒼焰的駕駛，聽得到吧？'], [DOG, '第三裝甲連被我圍在北郊山麓林地。想救就過來。'], [OP, '是陷阱。……可是我們沒有別人能派。']],
    end: [[ALLY, '蒼焰……第三裝甲連全員都還在。謝了。'], [OP, '黑犬撤回巢穴了。下一次，他會拼上全力。']],
    route:
    { cp: [4, 8], arena: 100, fin: 110, par: 700, over: 2,
      pts: [[-120, 700], [-120, 600], [-240, 600], [-360, 600], [-360, 480], [-360, 360], [-360, 240], [-480, 240], [-600, 240], [-600, 360], [-600, 480], [-480, 480], [-540, 420]],
      secs: [
        { at: 1, amb: 'tank@out*2 tank@side heli@rise', amb2: 'grunt@drop tank@out*2', amb3: 'heli@rise tank@side',
          go: [[ME, '我去。沿路打過去。']], lines: [[OP, '黑犬的外圍部隊。別在這裡耗太久。']] },
        { at: 2, pre: 'tank@far*2', amb: 'grunt@roof tank@side*2 heli@rise', amb2: 'heavy@drop tank@out*2', amb3: 'grunt@drop tank@out' },
        { at: 3, amb: 'ace@drop tank@out*2', amb2: 'grunt@drop tank@side*2', amb3: 'tank@out*2 grunt@roof', tip: '王牌機：槍口發光就閃，貼近時他會拔劍',
          lines: [[EN, '黑犬隊二號機接敵。蒼焰，陪我玩玩。'], [OP, '王牌機！槍口一亮就閃。']],
          clear: [[OP, '二號機擊毀。黑犬本人還沒露面。']] },
        { at: 4, amb: 'heavy@roof grunt@drop tank@side*2', amb2: 'tank@out*2 heli@rise*2', amb3: 'grunt@drop*2' },
        { at: 5, amb: 'grunt@drop*2', amb2: 'tank@out*2 heli@rise', tip: '黑犬會貼近拔劍：看到近戰警告就點 SHIFT 閃',
          boss: { kind: 'ace', name: '黑犬', ap: 1.5, where: 'roof', flee: 0.3,
            halfWave: 'grunt@side', half: [[DOG, '你換彈的時候就是破綻。小隊，從側面進。']],
            fled: [[DOG, '……嘖，新機還沒調好。公園見，蒼焰。'], [OP, '黑犬脫離了。別追，先去公園。']] },
          lines: [[DOG, '又見面了。讓我看看你長進了多少。'], [OP, '是黑犬！他比二號機快得多。']] },
        { at: 6, amb: 'tank@side*2 grunt@drop heavy@drop', amb2: 'grunt@roof tank@out*2 heli@rise', amb3: 'tank@out*2 grunt@drop',
          go: [[ALLY, '彈藥剩兩成，我們撐不了多久。']] },
        { at: 7, pre: 'tank@far*2', amb: 'ace@drop grunt@roof tank@side', amb2: 'tank@out*2 heli@rise grunt@drop',
          lines: [[EN, '三號機接敵。隊長，這台交給我。']] },
        { at: 8, amb: 'heavy@drop grunt@side tank@out*2', amb2: 'heli@rise*2 tank@side grunt@drop', amb3: 'grunt@drop*2 tank@out',
          clear: [[OP, '公園就在前面，第三裝甲連在裡面。']] },
        { at: 9, amb: 'grunt@roof ace@drop tank@out*2', amb2: 'tank@out*2 heavy@drop', amb3: 'heli@rise*2 grunt@drop',
          go: [[ALLY, '看到你了，蒼焰！公園四周都是他們的人。']] },
        { at: 10, amb: 'heli@rise*2 grunt@drop tank@out*2', amb2: 'grunt@roof tank@out*2 heavy@drop', amb3: 'grunt@drop*2 tank@out' },
        { at: 11, amb: 'grunt@drop*2 heavy@drop heli@rise', amb2: 'ace@drop grunt@roof', tip: '公園入口：清掉守衛就能進去',
          lines: [[OP, '零號，黑犬就在公園裡。專心閃。']] },
        { at: 12, amb: 'tank@ring*2', amb2: 'grunt@drop*2 heli@rise', amb3: 'ace@drop tank@ring*2', tip: '黑犬全力出擊：保持移動，覺醒（Q）留給他',
          boss: { kind: 'ace', name: '黑犬', ap: 2.4, where: 'drop', flee: 0.2,
            half: [[DOG, '這才像話！再來！']], low: [[DOG, '可惡……機體跟不上我的反應。']],
            fled: [[DOG, '蒼焰，勝負留到巢穴再分。'], [EN, '黑犬隊長脫離！全軍後撤！']] },
          lines: [[EN, '全部隊退開。黑犬隊長親自出擊。'], [DOG, '來吧，蒼焰。這次我不會留手。']] },
      ] } },
  // ================================================================ 第 6 關
  { battlefield: 'depot', fieldLabel: '工業補給基地', name: '補給線', en: 'SUPPLY LINE', tip: '琥珀色框的大樓是目標——整棟打垮才算數', music: 3, tier: 4,
    brief: ['黑犬撤走了，但獵犬軍團的油料和彈藥還源源不絕。', '補給從東南郊外進城，沿著南郊工業區的運輸道設了油庫和倉庫。', '零號單機深入，把標示的油庫、倉庫全部打垮。', '偵察報告：敵方戰鬥機已經進駐補給站。'],
    start: [[OP, '這次是單機深入，沒有援軍。'], [OP, '目標我會標在畫面上，打到整棟倒下為止。'], [ME, '收到，出發。']],
    end: [[OP, '補給總站瓦解。牠們的油撐不了幾天。'], [EN, '全軍注意：司令部下令，拂曉發動總攻。'], [OP, '聽到了嗎？牠們要孤注一擲了。']],
    route:
    // 南郊公路（z＝-600）一路往東 → 北上 x＝480 → 東 → 南下 x＝600 → 東南角公園的補給總站
    { cp: [4, 8], arena: 175, fin: 60, par: 520, over: 2,
      pts: [[-120, -660], [-120, -600], [0, -600], [120, -600], [240, -600], [360, -600], [480, -600], [480, -480], [480, -360], [480, -240], [600, -240], [600, -360], [600, -480], [540, -540]],
      secs: [
        { at: 2, pre: 'tank@far*2', amb: 'tank@out*2 tank@side grunt@drop', amb2: 'tank@out*2 heli@rise', tip: '路口停著的戰車先打——牠們還沒發現你',
          lines: [[EN, '南路哨站遭到攻擊！是那台藍色機體！']], clear: [[OP, '哨站清除。牠們應該已經發出警報了。']] },
        { at: 3, amb: 'grunt@side grunt@drop tank@out*2', amb2: 'grunt@roof tank@side*2 heli@rise',
          lines: [[EN, '守備隊出動！在公路上攔住牠！']] },
        { at: 4, amb: 'tank@side*2 grunt@drop tank@out', amb2: 'grunt@roof tank@out*2 heli@rise', amb3: 'tank@side*2 grunt@drop', tip: '打垮兩座油庫——大樓倒了才算',
          targets: [{ x: 155, z: -661, name: '油庫' }, { x: 197, z: -660, name: '油庫' }],
          go: [[OP, '公路旁那兩棟低矮建築是油庫。']], lines: [[EN, '牠衝著油庫來了！全力攔截！']], clear: [[OP, '兩座油庫都燒起來了。前線的戰車要斷油了。']] },
        { at: 5, amb: 'jet@out tank@out*2 tank@side', amb2: 'jet@out*2 grunt@drop', amb3: 'tank@out*2 heli@rise', tip: '新敵人：戰鬥機——掠過後會繞回來，用飛彈鎖定',
          lines: [[OP, '雷達上有高速目標！是戰鬥機，小心掃射！']] },
        { at: 6, amb: 'grunt@side tank@side heli@rise tank@out*2', amb2: 'grunt@drop*2 tank@out*2', tip: '打垮兩座彈藥倉庫',
          targets: [{ x: 395, z: -660, name: '彈藥倉庫' }, { x: 438, z: -660, name: '彈藥倉庫' }],
          go: [[OP, '下一個路口旁是彈藥倉庫。兩棟都要倒。']], lines: [[EN, '別讓牠靠近彈藥庫！']], clear: [[OP, '彈藥倉庫炸掉了。牠們的砲彈至少少一半。']] },
        { at: 7, pre: 'tank@far*2', amb: 'heavy@drop tank@side*2 grunt@roof', amb2: 'grunt@drop tank@out*3', amb3: 'heli@rise*2 tank@side', tip: '重裝機的飛彈會追人——響警報就點 SHIFT 閃',
          lines: [[EN, '重裝隊，把牠壓在路口！']] },
        { at: 8, amb: 'heli@rise*2 tank@out*2 grunt@drop', amb2: 'jet@out*2 tank@side*2', amb3: 'grunt@roof tank@out*2',
          lines: [[EN, '空中支援到了，前後夾擊！']] },
        { at: 9, pre: 'tank@far*3', amb: 'tank@out*3 tank@side grunt@drop', amb2: 'tank@side*2 heli@rise tank@out*2', tip: '車隊排成一列——按住鎖定，一次清光',
          go: [[OP, '前面有一支補給車隊。一台都別放過。']], lines: [[EN, '車隊被盯上了！護衛隊，迎擊！']] },
        { at: 10, amb: 'tank@side*2 grunt@drop heli@rise', amb2: 'heavy@drop tank@out*2', amb3: 'grunt@roof jet@out tank@side', tip: '三棟補給倉庫全部打垮',
          targets: [{ x: 640, z: -279, name: '補給倉庫' }, { x: 683, z: -280, name: '補給倉庫' }, { x: 641, z: -321, name: '補給倉庫' }],
          go: [[OP, '路口東側那排矮房是補給倉庫，共三棟。']], lines: [[EN, '倉庫區告急！補給總站，請求增援！']], clear: [[OP, '倉庫全毀。補給總站在南邊的公園。']] },
        { at: 11, amb: 'grunt@side*2 tank@out*2 heli@rise', amb2: 'jet@out tank@side*2 grunt@drop',
          lines: [[EN, '所有部隊，回防總站！']] },
        { at: 12, amb: 'grunt@drop*2 tank@out*2 jet@out', amb2: 'grunt@roof heli@rise tank@out*2',
          lines: [[EN, '頂住！總站不能丟！']], clear: [[OP, '總站就在前面。最後一段。']] },
        { at: 13, amb: 'tank@ring*4 grunt@drop*2 heli@rise', amb2: 'heavy@drop grunt@drop tank@ring*3 jet@out', amb3: 'grunt@drop*2 heli@rise*2 tank@ring*2', tip: '補給總站：守軍全部擊毀就過關',
          lines: [[EN, '總站所有單位，出擊！']] },
      ] } },
  // ================================================================ 第 7 關
  { battlefield: 'badlands', fieldLabel: '荒野防線', name: '鋼鐵洪流', en: 'IRON TIDE', tip: '邊打邊退，到防線再守——守點區要撐到倒數結束', music: 5, tier: 5,
    brief: ['補給被切斷後，獵犬軍團把剩下的戰車全部押上。', '裝甲大軍從東郊荒原沿大道壓向市中心，帶頭的是重裝大隊長「鐵獒」。', '零號和第三裝甲連守在東郊前哨。先邊打邊退，退到大道防線。', '守住防線，再反攻奪回前哨。'],
    start: [[ALLY, '地平線上全是戰車，數不完。'], [OP, '零號，別硬拚。掩護裝甲連撤到防線。']],
    end: [[ALLY, '前哨拿回來了。開戰以來頭一次。'], [OP, '敵方裝甲兵力折損過半。辛苦了，零號。'], [WOLF, '……有意思。']],
    route:
    // 東郊前哨（東緣空地）→ 沿北側的街往西撤（z＝120）→ 第一道防線 → 大道防線（240,0）→ 沿大道反攻、繞南側 → 奪回前哨
    { cp: [3, 5, 8], arena: 175, fin: 60, par: 560, over: 2,
      pts: [[660, 60], [600, 120], [480, 120], [360, 120], [240, 120], [240, 0], [360, 0], [480, 0], [480, -120], [600, -120], [600, 0], [660, 60]],
      secs: [
        { at: 1, amb: 'tank@out*3 heli@rise grunt@drop', amb2: 'tank@out*3 grunt@drop', tip: '邊打邊退——別停在同一個地方',
          clear: [[OP, '大道已經被截斷。走北側的運輸道撤。']] },
        { at: 2, amb: 'tank@side*2 grunt@side heavy@drop', amb2: 'tank@out*3 grunt@roof',
          lines: [[ALLY, '該死，前面也有！牠們繞過來了！']] },
        { at: 3, hold: 45, gap: 15, amb: 'tank@side*3 grunt@drop heli@rise', amb2: 'heavy@drop tank@side*2 tank@out', amb3: 'tank@side*3 grunt@drop jet@out', tip: '守住 45 秒——敵人會一波接一波從支路湧出',
          go: [[OP, '裝甲連在前面路口架好了砲。守住四十五秒。']], lines: [[ALLY, '砲口朝外！撐到大道那邊準備好！']], clear: [[ALLY, '時間夠了！全連撤到大道防線！']] },
        { at: 4, amb: 'grunt@drop*2 tank@side*2 heli@rise', amb2: 'tank@out*3 grunt@roof',
          lines: [[EN, '聯邦部隊在撤退。咬住牠們！']] },
        { at: 5, hold: 60, gap: 15, amb: 'tank@out*4 grunt@drop', amb2: 'tank@out*3 heavy@drop heli@rise', amb3: 'tank@side*2 tank@out*2 grunt@drop jet@out', tip: '守住 60 秒——大道上的戰車會一直衝過來',
          beats: [{ t: 22, lines: [[ALLY, '北側防線破了！他們繞到我們背後！'], [OP, '零號，接住側翼。大道交給裝甲連。']], spawn: 'grunt@side' },
            { t: 46, lines: [[WOLF, '讓鐵獒上去。我要那台機體的殘骸。']] }],
          go: [[OP, '大道路口是最後一道防線。再退就是市中心。']], lines: [[ALLY, '全連就位。一步都不准退！'], [WOLF, '推平它。']], clear: [[OP, '防線守住了……等等，有大型重裝機接近。']] },
        { at: 6, amb: 'tank@out*2 grunt@drop', amb2: 'grunt@drop tank@out*2 heli@rise', tip: '敵方指揮官：重裝機火力很強——拿大樓擋飛彈',
          boss: { kind: 'heavy', name: '鐵獒', ap: 3, where: 'drop',
            halfWave: 'grunt@side',
            half: [['鐵獒（獵犬軍團）', '有兩下子。全隊，火力集中！']], low: [[OP, '牠的裝甲快撐不住了，壓上去！']] },
          lines: [['鐵獒（獵犬軍團）', '就是你趕跑了黑犬？讓我看看。']], clear: [[ALLY, '鐵獒倒了！全連，反攻！']] },
        { at: 7, pre: 'tank@far*3', amb: 'tank@out*2 grunt@side heli@rise', amb2: 'grunt@roof tank@out*3',
          lines: [[EN, '指揮官陣亡！前鋒，誰來接手指揮？']], clear: [[OP, '大道被殘骸堵住了。從南側繞過去。']] },
        { at: 8, amb: 'tank@side*2 grunt@drop jet@out', amb2: 'heavy@drop tank@out*2' },
        { at: 9, amb: 'grunt@side*2 tank@out*2 heli@rise', amb2: 'tank@side*2 grunt@drop jet@out',
          lines: [[ALLY, '前哨就在前面。推回去！']] },
        { at: 10, amb: 'grunt@drop*2 tank@out*2 heli@rise', amb2: 'tank@out*3 jet@out',
          clear: [[OP, '前哨還有殘敵。清乾淨，就拿回來了。']] },
        { at: 11, amb: 'tank@ring*4 heavy@drop grunt@drop', amb2: 'grunt@drop*2 heli@rise tank@ring*3', amb3: 'heavy@drop jet@out tank@ring*3 grunt@drop', tip: '奪回前哨——清光殘敵就過關',
          lines: [[EN, '後路被切斷了！死守前哨！']] },
      ] } },
  // ================================================================ 第 8 關
  { battlefield: 'airfield', fieldLabel: '高原航空基地', name: '制空權', en: 'AIR SUPREMACY', tip: '直升機從樓後升起、戰機低空掠過——飛彈一次鎖多台', music: 4, tier: 5,
    brief: ['聯邦空軍整備完成，但城南高原航空基地的防空網讓飛機一架也進不來。', '防空砲架在機場掩體上，由雷達站統一指揮。', '沿路打垮防空陣地和雷達，替最後的總攻打開空中走廊。', '牠們會把能飛的全部派上來。'],
    start: [[OP, '防空網不倒，空軍就飛不進來。'], [OP, '砲架在掩體頂上。整座打垮，砲就一起倒。']],
    end: [[OP, '防空網瓦解。空軍，路開了。'], ['聯邦空軍', '鷹群進入首都空域。謝了，蒼焰。'], [DOG, '藍色的，我在巢穴等你。']],
    route:
    // 中央廣場南緣出發 → 沿 x＝0 往南 → 蛇行穿過城南的塔樓區 → 塔樓區中間的空地（防空指揮所）
    { cp: [4, 8], arena: 175, fin: 60, par: 550, over: 2,
      pts: [[60, -60], [0, -120], [0, -240], [0, -360], [0, -480], [120, -480], [240, -480], [240, -360], [120, -360], [120, -240], [120, -120], [240, -120], [300, -180]],
      secs: [
        { at: 1, amb: 'heli@rise*2 tank@out*2', amb2: 'heli@rise tank@side*2 grunt@drop', tip: '直升機從樓後面升起——一露頭就打' },
        { at: 2, amb: 'heli@rise*2 tank@side grunt@roof', amb2: 'jet@out tank@out*2 heli@rise', amb3: 'grunt@drop heli@rise*2', tip: '打垮兩座防空陣地',
          targets: [{ x: 37, z: -205, name: '防空陣地' }, { x: -41, z: -300, name: '防空陣地' }],
          go: [[OP, '前面路口兩側的樓頂有防空砲。']], lines: [[EN, '防空陣地遭到攻擊！']], clear: [[OP, '兩座防空砲沉默了。']] },
        { at: 3, amb: 'jet@out*2 tank@out*2', amb2: 'jet@out heli@rise*2 grunt@drop', tip: '戰機掠過後會繞一大圈——等牠回頭時鎖定',
          lines: [[EN, '戰鬥機隊，攔截那台機體！']] },
        { at: 4, amb: 'heavy@drop heli@rise tank@side*2', amb2: 'grunt@roof*2 tank@out*2', amb3: 'heli@rise*2 tank@side',
          lines: [[EN, '重裝隊到位。把牠壓在地面上！']] },
        { at: 5, amb: 'heli@rise*2 grunt@side tank@out', amb2: 'jet@out*2 tank@side*2', amb3: 'heli@rise*2 grunt@roof', tip: '再兩座防空陣地',
          targets: [{ x: 162, z: -420, name: '防空陣地' }, { x: 62, z: -541, name: '防空陣地' }],
          go: [[OP, '再兩座防空砲。空軍已經在跑道上待命。']], lines: [[EN, '南區砲陣地被盯上了！直升機掩護！']], clear: [[OP, '南區的防空砲清空了。']] },
        { at: 6, amb: 'heli@rise*3 tank@out*2', amb2: 'heli@rise*2 jet@out grunt@drop', amb3: 'heli@rise*2 tank@side*2', tip: '直升機群——按住鎖定多台，一次清掉',
          lines: [[EN, '所有直升機，圍住牠！']] },
        { at: 7, amb: 'grunt@side*2 tank@out*2 heli@rise', amb2: 'heavy@drop tank@out*2 jet@out', amb3: 'heli@rise*2 tank@side*2' },
        { at: 8, amb: 'heli@rise*3 grunt@drop', amb2: 'jet@out*2 heli@rise tank@out*2', amb3: 'heli@rise*2 grunt@roof tank@side', tip: '雷達站又高又硬——用光波砲一口氣打垮',
          targets: [{ x: 82, z: -324, name: '雷達站' }],
          beats: [{ t: 20, lines: [['聯邦空軍', '鷹群被雷達鎖住了，進不去！'], [OP, '蒼焰，先拆雷達。別被直升機帶離目標。']], spawn: 'grunt@side' }],
          go: [[OP, '那棟最高的塔樓是雷達站，防空網靠它指揮。']], lines: [[EN, '雷達站告急！所有單位回防！']], clear: [[OP, '雷達站倒了。防空網瞎了一半。']] },
        { at: 9, amb: 'jet@out*2 heli@rise*2', amb2: 'heli@rise*2 tank@side*2 grunt@drop', amb3: 'jet@out*2 grunt@roof',
          lines: [[EN, '剩下的戰機全部起飛！擊落那台藍色的！']] },
        { at: 10, amb: 'grunt@side*2 tank@side heli@rise*2', amb2: 'heavy@drop tank@out*2', amb3: 'jet@out*2 grunt@roof',
          lines: [[EN, '指揮所外圍的部隊，頂住！']] },
        { at: 11, amb: 'heavy@drop tank@out*2 heli@rise', amb2: 'grunt@drop*2 tank@out*2 jet@out',
          clear: [[OP, '最後是主雷達和防空指揮所。']] },
        { at: 12, amb: 'heli@rise*2 tank@ring*3 grunt@drop', amb2: 'jet@out*2 heli@rise*2 tank@ring*2', amb3: 'heavy@drop heli@rise*2 tank@ring*2 jet@out', tip: '最後一區：打垮主雷達和防空指揮所，清光守軍',
          targets: [{ x: 277, z: -280, name: '主雷達' }, { x: 204, z: -200, name: '防空指揮所' }],
          lines: [[EN, '防空指揮所死守！一架都不准放進來！']] },
      ] } },
  // ================================================================ 第 9 關
  // 城北官署區（獵犬軍團司令部）：從東邊沿 z=360、z=480 往西打，倒通訊塔、守點接線、拆碉堡，最後在司令部後面的閱兵場（空地）跟黑犬單挑
  { battlefield: 'fortress', fieldLabel: '山隘要塞', name: '獵犬巢穴', en: 'THE DEN', tip: '琥珀色框的大樓是目標——打倒它、清光敵人，這一區才算過', music: 5, tier: 6,
    brief: ['防空陣地拆掉了，聯邦的飛機終於能飛進首都。', '獵犬軍團的司令部設在城北山隘要塞，外圍有碉堡，中間有一座通訊塔。', '先打倒通訊塔，切斷司令部和各部隊的聯絡，再攻進去。', '黑犬撤回了司令部。這一次，他後面沒有路了。'],
    start: [[OP, '零號，這裡是白鷺。今天的目標是獵犬的司令部。'], [ALLY, '第三裝甲連跟在後面。機體歸你，戰車歸我們。']],
    end: [[ME, '……我記住了。'], [OP, '黑犬確認擊墜。司令部拿下了。'], [WOLF, '（公開頻道）這裡是灰狼。全軍撤回國會廣場。'], [OP, '最後一仗在廣場。零號，先回來補給。']],
    route:
    { cp: [4, 8, 11], arena: 175, fin: 60, par: 660, over: 2,
      pts: [[600, 230], [600, 360], [480, 360], [360, 360], [240, 360], [240, 480], [120, 480], [0, 480], [-120, 480], [-240, 480], [-240, 600], [-120, 600], [-60, 660]],
      secs: [
        { at: 1, pre: 'tank@far*2', amb: 'tank@side*2 tank@out grunt@drop', amb2: 'tank@out*2 heli@rise', tip: '北區第一道防線——轉角的戰車先打',
          lines: [[EN, '聯邦機體進入北區！第一防線，開火！', NOW]] },
        { at: 2, amb: 'grunt@side tank@side tank@out*2 grunt@roof', amb2: 'tank@out*2 heli@rise grunt@drop', amb3: 'grunt@drop tank@out*2',
          go: [[OP, '官署區就在西邊。沿著大街往裡打。']] },
        { at: 3, amb: 'heli@rise jet@rise*2 grunt@side tank@out', amb2: 'grunt@drop tank@out*2 heli@rise', tip: '戰機掠過頭頂——右鍵鎖定，飛彈追得上',
          go: [[OP, '他們把剩下的戰機都派出來了。']], lines: [[EN, '航空隊起飛！別讓它靠近司令部！', NOW]] },
        { at: 4, pre: 'tank@far', amb: 'heavy@roof grunt@side tank@side tank@out', amb2: 'grunt@drop*2 tank@out', tip: '樓頂的重裝機射程最遠——先把它打下來',
          go: [[OP, '往北轉。通訊塔在官署區中間。']] },
        { at: 5, amb: 'ace@drop grunt@side tank@out*2', amb2: 'grunt@roof heli@rise tank@side', tip: '王牌機靠近會拔劍——看到警告就閃',
          lines: [[EN, '司令部親衛隊出動！擋住它！', NOW]], clear: [[ALLY, '親衛隊也不過如此！小子，繼續走！']] },
        { at: 6, targets: [{ x: 83, z: 420, name: '通訊塔' }], amb: 'grunt@roof tank@side*2 heavy@drop', amb2: 'grunt@drop tank@out*2 heli@rise', amb3: 'grunt@drop heli@rise*2', tip: '通訊塔很硬——邊閃邊集中火力',
          go: [[OP, '那座高塔就是司令部的通訊塔。'], [OP, '打倒它，獵犬的部隊就收不到命令。']],
          clear: [[EN, '（雜訊）……司令部……請回答……'], [OP, '通訊塔倒了。現在他們各打各的。']] },
        { at: 7, amb: 'tank@side*2 tank@out*2 grunt@drop heli@rise', amb2: 'tank@out*2 grunt@roof grunt@drop', amb3: 'tank@out*2 heli@rise', tip: '敵軍斷了聯絡——一台一台點掉',
          go: [[ALLY, '他們亂了！第三裝甲連，跟著蒼焰推進！']] },
        { at: 8, pre: 'tank@far*2', amb: 'heavy@roof ace@side grunt@drop tank@out', amb2: 'grunt@drop*2 heli@rise*2',
          go: [[OP, '南邊那棟大樓就是司令部。']], lines: [[EN, '守住司令部！一步都不准退！', NOW]] },
        { at: 9, hold: 40, gap: 16, amb: 'heavy@drop grunt@drop tank@side*2', amb2: 'grunt@roof tank@out*2 heli@rise', amb3: 'heavy@roof grunt@drop tank@side', tip: '守住 40 秒——第三裝甲連在接司令部的線路',
          go: [[OP, '塔倒了以後，司令部只剩地下電纜能用。'], [OP, '第三裝甲連要接上去。守住這個路口。']],
          lines: [[EN, '有人在碰司令部的線路！阻止他們！', NOW]],
          clear: [[ALLY, '接上了！他們講什麼我們都聽得到。'], [OP, '黑犬在司令部後面的閱兵場。']] },
        { at: 10, targets: [{ x: -204, z: 562, name: '一號碉堡' }, { x: -278, z: 556, name: '二號碉堡' }], amb: 'grunt@roof grunt@side tank@side tank@out', amb2: 'heli@rise*2 grunt@drop tank@out', amb3: 'grunt@roof heli@rise tank@out',
          go: [[OP, '閱兵場入口有兩座碉堡，都打掉。']], clear: [[ME, '碉堡清掉了。']] },
        { at: 11, amb: 'ace@drop*2 grunt@roof', amb2: 'grunt@drop tank@ring*2', tip: '黑犬小隊：兩台王牌——別讓它們同時貼上來',
          go: [[DOG, '（公開頻道）蒼焰，我在閱兵場等你。'], [DOG, '先過我小隊這一關。']], lines: [[EN, '黑犬小隊，迎擊！', NOW]],
          clear: [[OP, '他在等你。……機體撐得住嗎？'], [ME, '撐得住。']] },
        { at: 12, amb: 'grunt@drop*2', tip: '最後一戰：槍口發光就閃，靠近會拔劍',
          boss: { kind: 'ace', name: '黑犬', ap: 3, where: 'drop',
            halfWave: 'grunt@side',
            half: [[DOG, '小隊，從側面進！我壓住他。'], [OP, '他在配合護衛包抄。先切斷他們的射線。']], low: [[DOG, '護衛別管我。蒼焰……這一下你躲得開嗎？']],
            down: [[DOG, '……隼選對人了。'], [DOG, '零號。上次我說記住你了……這次換你記住我。']] },
          lines: [[DOG, '這次我不走了。你也別想走。', NOW], [ME, '我沒打算走。', NOW]] },
      ] } },
  // ================================================================ 第 10 關
  // 黃昏：從東北角沿 x=600、480、360、240 一路往西南打，從東邊進國會廣場（市中心空地）；中途兩次守點，最後跟灰狼的超重型機決戰
  { name: '黃昏決戰', en: 'LAST LIGHT', tip: '最終關：王牌、重裝、戰車、直升機、戰機全部出動', music: 6, tier: 6,
    brief: ['司令部失守，灰狼帶著剩下的部隊退進首都中心的國會廣場。', '他本人坐進一台超重型機體，親自守在廣場上。', '聯邦主力正從東邊渡河。在他們趕到之前，蒼焰要先打開通往廣場的路。', '黃昏出擊。這是最後一仗。'],
    start: [[ALLY, '渡河部隊遭到砲擊，先頭車堵在橋上！', NOW], [OP, '灰狼把最後的兵力全壓過來了。零號，先替他們打開橋口。'], [ME, '收到。這次一起回去。']],
    end: [[OP, '各地回報，獵犬軍團放下武器了。'], [ALLY, '聽到了嗎！首都拿回來了！'], [OP, '（隔天清晨）零號，醒了嗎？看東邊。'], [ME, '……天亮了。'],
      [ME, '隼，你說得對。蒼焰很聽話。'], [OP, '蒼焰的駕駛員，今天的任務只有一個：好好睡一覺。']],
    route:
    { cp: [4, 8, 10], arena: 175, fin: 60, par: 720, over: 2,
      pts: [[600, 700], [600, 600], [600, 480], [480, 480], [480, 360], [480, 240], [360, 240], [360, 120], [240, 120], [240, 0], [120, 0], [0, 0]],
      secs: [
        { at: 1, pre: 'tank@far*2', amb: 'tank@side*2 grunt@drop heli@rise', amb2: 'tank@out*2 grunt@roof', tip: '往國會廣場推進——沿路都是灰狼的部隊',
          lines: [[EN, '蒼焰出現在東北！全員迎擊！', NOW]] },
        { at: 2, amb: 'grunt@side heli@rise*2 tank@out*2', amb2: 'jet@rise*2 grunt@drop tank@side',
          go: [[OP, '廣場在西南，大約一公里。']] },
        { at: 3, pre: 'tank@far', amb: 'ace@drop grunt@side tank@out tank@side', amb2: 'grunt@roof heli@rise tank@out*2', tip: '灰狼的親衛隊——槍口發光就閃',
          go: [[OP, '前面是灰狼的親衛隊，全是王牌機。']], lines: [[EN, '親衛隊，攔下蒼焰！', NOW]] },
        { at: 4, amb: 'heavy@roof grunt@drop tank@side*2 heli@rise', amb2: 'ace@drop tank@out*2', tip: '樓頂的重裝機——先打高處',
          clear: [[OP, '第三裝甲連被擋在河邊了。']] },
        { at: 5, hold: 45, gap: 16, amb: 'grunt@drop tank@side*2 heli@rise', amb2: 'tank@out*2 grunt@roof jet@rise', amb3: 'heavy@drop tank@side tank@out', tip: '守住 45 秒——第三裝甲連正在過河',
          go: [[OP, '他們要四十五秒才過得來。'], [OP, '守住這個路口，別讓敵人繞到河邊。']],
          lines: [[EN, '聯邦的戰車要過河了！全力阻止！', NOW]],
          clear: [[ALLY, '久等了！第三裝甲連，到！'], [ALLY, '小子，剩下的路一起打。']] },
        { at: 6, amb: 'grunt@side grunt@roof tank@out*2 heli@rise', amb2: 'ace@drop jet@rise tank@side',
          go: [[ALLY, '戰車交給我們，你專心打機體！']] },
        { at: 7, pre: 'tank@far*2', amb: 'heavy@drop heavy@roof tank@side grunt@side', amb2: 'grunt@drop*2 heli@rise*2', tip: '兩台重裝機——躲到樓後面再換位置',
          go: [[OP, '天快黑了。廣場就在西邊。']] },
        { at: 8, amb: 'jet@rise*2 heli@rise*2 tank@out*2 grunt@drop', amb2: 'ace@drop grunt@roof tank@side', tip: '戰機低空掃射——右鍵按住一次鎖光',
          lines: [[EN, '航空隊最後一次出擊！全機升空！', NOW]] },
        { at: 9, amb: 'ace@drop*2 grunt@side tank@out', amb2: 'heavy@roof grunt@drop tank@out*2',
          go: [[WOLF, '（公開頻道）蒼焰。黑犬是我帶出來的。'], [WOLF, '他輸給了你。我不會。']] },
        { at: 10, hold: 50, gap: 16, amb: 'grunt@drop*2 tank@ring*2 heli@rise', amb2: 'ace@drop tank@ring*2 jet@rise', amb3: 'heavy@drop grunt@drop tank@ring*2', tip: '守住 50 秒——聯邦主力正在進城',
          beats: [{ t: 18, lines: [[OP, '側街有高速機體！他們想截斷主力的入口！']], spawn: 'ace@side' },
            { t: 39, lines: [[ALLY, '先頭車進城！零號，還有十一秒！'], [WOLF, '全員留在廣場。誰都不許退。']] }],
          go: [[OP, '聯邦主力還要五十秒才到廣場。'], [OP, '零號，撐住。這是最後一次守點。']],
          lines: [[EN, '全軍反擊！別讓它進廣場！', NOW]],
          clear: [[OP, '主力部隊進城了！廣場四周都是我們的人。']] },
        { at: 11, amb: 'tank@ring*3', amb2: 'ace@drop grunt@drop heli@rise', amb3: 'grunt@drop jet@rise*2', tip: '灰狼：超重型機——閃開砲擊，貼近再打',
          boss: { kind: 'heavy', name: '灰狼', ap: 4.5, where: 'drop',
            halfWave: 'ace@side', lowWave: 'grunt@side',
            half: [[WOLF, '親衛隊，從左側切入。我來封他的退路。'], [OP, '王牌機進場！別讓兩種火力把你夾住！']], low: [[WOLF, '最後一隊，掩護我。廣場一步都不能讓。']],
            down: [[WOLF, '……獵犬軍團全軍，停止抵抗。'], [WOLF, '這是我最後一道命令。']] },
          lines: [[WOLF, '這座廣場是獵犬軍團最後的陣地。', NOW], [WOLF, '到此為止，蒼焰。', NOW]] },
      ] } },
];
