import {palette} from './data.js?v=17';
import {checkWish,wishNames,colorNames} from './goals.js?v=17';
import {iconMarkup as svg} from './icons.js?v=17';
import {wishIcon} from './replay-ui.js?v=17';
import {ornament} from './ornaments.js?v=17';
const toolLabels={cut:'剪頭髮',grow:'長頭髮',color:'染髮',comb:'梳頭髮',decorate:'髮飾'};
const hints={wash:'按住或拖過頭髮搓出泡泡',rinse:'拖過泡泡，把頭髮沖乾淨',curl:'點一下或拖過髮尾，做出柔軟捲髮',straight:'點一下或拖過髮尾，拉成直髮',tie:'拖髮圈到頭髮上，拖動調整，點一下鬆開',cut:'點一下剪短，拖過髮絲剪出形狀',grow:'按住髮尾，讓頭髮慢慢長回來',color:'選顏色，再塗在想染的髮絲上',comb:'順著髮絲拖動，梳出喜歡的形狀',decorate:'點一下放髮飾，拖曳移動或轉動'};
export class StudioUI{
 constructor(api){this.api=api;this.free=false;this.last=0;this.panelKey='';this.completed=new Set();
  this.root=document.createElement('div');this.root.className='studio';this.root.innerHTML=`<header class="brand"><div class="brand-mark">✿</div><div><span class="eyebrow">LITTLE SALON</span><h1>小小美髮師</h1></div><button class="help quiet" aria-label="玩法說明">${svg('help')}</button></header><nav class="top-actions" aria-label="作品與造型"></nav><section class="order" aria-label="客人的造型願望"><canvas class="wish-picture" width="128" height="128" aria-hidden="true"></canvas><div class="order-copy"><span class="eyebrow">TODAY’S LITTLE WISH</span><strong class="wish-name"></strong></div><div class="goals"></div><button class="free-toggle" aria-label="切換自由創作">${svg('wishes')}</button></section><div class="tie-toolbar" role="group" aria-label="自由綁髮"><button class="tie-source" aria-label="拖髮圈到頭髮上">${svg('tie')}</button><svg class="tie-gesture" viewBox="0 0 70 40" aria-hidden="true"><path d="M5 10q38-12 51 17m-11-2 11 3-2-11" fill="none" stroke="#bf95bb" stroke-width="3" stroke-linecap="round" stroke-dasharray="3 5"/><path d="M24 37v-7l-5-7q-2-4 2-4l5 4V10q0-5 5-2v13l5-1 7 5v9l-3 4" fill="#ffdbb5" stroke="#b28b7e" stroke-width="1.7"/></svg><button class="tie-presets" aria-label="選現成髮型">${svg('ties')}</button><button class="untie-all" aria-label="放下全部頭髮">${svg('untie')}</button></div><div class="tie-handles"></div><div class="tray"></div><div class="tools" role="group" aria-label="美髮工具"></div><div class="swatches" role="group" aria-label="髮色"></div><div class="stage-footer"><button class="undo small" aria-label="撤銷">${svg('undo')}</button><div class="tool-hint" role="status"></div><button class="reset small" aria-label="重新開始">${svg('reset')}</button></div><button class="dye-all">整頭染色</button><div class="panel-controls"></div><div class="toast" role="status"></div><dialog class="help-dialog"><span class="eyebrow">WELCOME TO YOUR SALON</span><h2>今天，換個新造型！</h2><p>先選客人和靈感，在頭髮上點一下或拖曳，就能剪、染、梳出自己的作品。</p><ol><li>✂ 剪短了？用生髮水長回來，或按撤銷。</li><li>🎨 選色塊局部染色，也能一鍵整頭染。</li><li>🎀 拖髮圈到頭髮上自由綁；拖動換位置，點一下鬆開。旁邊的小頭像可選現成髮型。</li><li>🫧 點梳子打開工具選單，洗頭搓泡泡、沖水，也能捲髮或拉直；都可撤銷。</li><li>🎲 在靈感選單點骰子，抽新的造型挑戰。</li><li>📷 完成願望拍照，收集角色貼紙；點右箭頭接下一個驚喜。貼紙簿可從靈感或作品集打開。</li></ol><p class="help-note">沒有倒數，也沒有失敗。願望只是靈感，喜歡就可以拍照！作品存在這台裝置。</p><button class="help-close primary">開始造型</button></dialog>`;
  document.getElementById('game').append(this.root);
  const nav=this.root.querySelector('nav');for(const [kind,label] of [['guests','客人'],['wishes','靈感'],['ties','綁髮'],['decorate','髮飾'],['album','作品集'],['camera','拍照']]){const b=document.createElement('button');b.innerHTML=svg(kind)+`<span>${label}</span>`;b.dataset.action=kind;b.onclick=()=>{api.stop();kind==='ties'?api.select('tie'):kind==='camera'?api.replay.snap():api.replay.open(kind==='decorate'?'accessories':kind)};nav.append(b)}
  for(const kind of Object.keys(toolLabels)){const b=document.createElement('button');b.className='tool';b.dataset.tool=kind;b.setAttribute('aria-label',kind==='comb'?'梳理與洗頭工具':toolLabels[kind]);b.innerHTML=svg(kind)+`<span>${toolLabels[kind]}</span>`;b.onclick=()=>kind==='comb'?api.replay.open('care'):api.select(kind);this.root.querySelector('.tools').append(b)}
  palette.forEach((color,i)=>{const b=document.createElement('button');b.className='swatch';b.style.setProperty('--color',`rgb(${color.join(',')})`);b.setAttribute('aria-label',colorNames[i]);b.onclick=()=>api.color(i);this.root.querySelector('.swatches').append(b)});
  api.bindTieControl(this.root.querySelector('.tie-source'));this.root.querySelector('.tie-presets').onclick=()=>{api.stop();api.replay.open('ties')};this.root.querySelector('.untie-all').onclick=()=>api.untieAll();this.handles=new Map();
  this.root.querySelector('.undo').onclick=()=>api.undo();this.root.querySelector('.reset').onclick=()=>api.replay.open('reset');
  this.root.querySelector('.free-toggle').onclick=()=>{this.free=!this.free;this.last=0};this.root.querySelector('.dye-all').onclick=()=>api.dyeAll();
  const dialog=this.root.querySelector('dialog');this.root.querySelector('.help').onclick=()=>{api.stop();dialog.showModal()};this.root.querySelector('.help-close').onclick=()=>dialog.close();
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){api.stop();api.replay.mode=null}else if((e.ctrlKey||e.metaKey)&&e.key==='z'&&!dialog.open){e.preventDefault();api.undo()}});
 }
 resize(l){this.layout=l;this.root.classList.toggle('narrow',l.stage.w<560);const s=this.root.style;s.setProperty('--stage-width',l.stage.w+'px');
  const dock=this.root.querySelector('.tray');Object.assign(dock.style,{left:l.dock.x+'px',top:l.dock.y+'px',width:l.dock.w+'px',height:l.dock.h+'px'});
  [...this.root.querySelectorAll('.tool')].forEach((b,i)=>{const p=l.buttons[i];Object.assign(b.style,{left:p.x-p.r+'px',top:p.y-p.r+'px',width:p.r*2+'px',height:p.r*2+'px'})});
  [...this.root.querySelectorAll('.swatch')].forEach((b,i)=>{const p=l.colors[i];Object.assign(b.style,{left:p.x-p.r+'px',top:p.y-p.r+'px',width:p.r*2+'px',height:p.r*2+'px'})});
  this.root.querySelector('.stage-footer').style.top=(l.stage.h-44)+'px';
  const dye=this.root.querySelector('.dye-all');Object.assign(dye.style,{top:(l.stage.h-76)+'px',left:(l.stage.w/2-52)+'px'});
 }
 notify(message){const t=this.root.querySelector('.toast');t.textContent=message;t.classList.add('show');clearTimeout(this.timer);this.timer=setTimeout(()=>t.classList.remove('show'),2800)}
 draw(now){const a=this.api,mode=a.replay.mode;if(now-this.last<180&&mode===this.lastMode)return;this.last=now;this.lastMode=mode;
  this.root.classList.toggle('modal-open',!!mode);const selected=a.selected();this.root.classList.toggle('tying',selected==='tie');this.root.querySelector('[data-action="ties"]').setAttribute('aria-pressed',selected==='tie');
  this.root.querySelector('.tie-source').style.setProperty('--tie-color',`rgb(${palette[a.colorIndex()].join(',')})`);
  const bands=selected==='tie'&&!mode?a.hair().tieHandles():[],alive=new Set(bands.map(b=>b.index));for(const [index,button] of this.handles)if(!alive.has(index)){button.remove();this.handles.delete(index)}
  for(const band of bands){let button=this.handles.get(band.index);if(!button){button=document.createElement('button');button.className='tie-handle';button.innerHTML=svg('tie');button.setAttribute('aria-label','髮圈，拖動換位置，點一下鬆開');a.bindTieControl(button,band.index);this.handles.set(band.index,button);this.root.querySelector('.tie-handles').append(button)}const world=this.layout.world;Object.assign(button.style,{left:(world.x+band.x*world.scale-32)+'px',top:(world.y+band.y*world.scale-32)+'px'});button.style.setProperty('--tie-color',`rgb(${palette[band.color??0].join(',')})`);}
  this.root.querySelector('.untie-all').disabled=!a.hair().activeTies().length;
  for(const b of this.root.querySelectorAll('[data-tool]')){const active=b.dataset.tool===selected||b.dataset.tool==='comb'&&['wash','rinse','curl','straight'].includes(selected);b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active);if(b.dataset.tool==='comb'&&this.careKind!==selected){this.careKind=selected;b.innerHTML=svg(['wash','rinse','curl','straight'].includes(selected)?selected:'comb')+'<span>梳理與洗頭</span>'}}
  [...this.root.querySelectorAll('.swatch')].forEach((b,i)=>{const active=a.colorIndex()===i;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active)});
  this.root.querySelector('.undo').disabled=!a.canUndo();const hint=this.root.querySelector('.tool-hint');hint.setAttribute('aria-label',hints[selected]);if(this.hintKind!==selected){this.hintKind=selected;hint.innerHTML=svg(selected)+`<svg viewBox="0 0 70 36" aria-hidden="true"><path d="M8 16h49m-8-7 8 7-8 7" fill="none" stroke="#bf95bb" stroke-width="3" stroke-linecap="round" stroke-dasharray="3 5"/><path d="M25 32v-7l-5-7q-2-4 2-4l5 4V5q0-5 5-2v13l5-1 7 5v9l-3 4" fill="#ffdbb5" stroke="#b28b7e" stroke-width="1.7" stroke-linejoin="round"/><path d="M8 4q-3 2-2 6m31-7q3 2 2 6" fill="none" stroke="#e9bd69" stroke-width="2"/></svg>`}this.root.querySelector('.dye-all').hidden=selected!=='color'||!!mode;
  const w=a.currentWish(),g=checkWish(a.hair(),a.items(),w),n=Object.values(g).filter(Boolean).length;
  this.root.querySelector('.wish-name').textContent=this.free?'自由創作時間':`${w.id.startsWith('surprise-')?'驚喜造型':wishNames[a.wish()]} ${n===3?'✦ 完成！':''}`;
  this.root.querySelector('.free-toggle').setAttribute('aria-label',this.free?'接造型願望':'自由創作');this.root.querySelector('.order').classList.toggle('free',this.free);
  const completion=a.guest()+':'+w.id;if(!this.free&&n===3&&!this.completed.has(completion)){this.completed.add(completion);a.celebrate();this.notify('小願望完成！拍照收藏角色貼紙。')}
  const accessoryNames={bow:'蝴蝶結',pearls:'珍珠項鍊',flower:'花朵',star:'星星',moon:'月亮',butterfly:'蝴蝶',heart:'愛心',crown:'皇冠'};
  const entries=[['colors',w.colors.length>2?'彩虹色':w.colors.map(i=>colorNames[i].replace(/玫瑰|蜜桃|陽光|薄荷|天空|薰衣草/g,'')).join('＋')],['length',w.length<.6?'短髮':w.length<.85?'中長髮':'長髮'],['accessory',accessoryNames[w.accessory]]];
  const goalKey=JSON.stringify([this.free,entries,g]);if(goalKey!==this.goalKey){this.goalKey=goalKey;const picture=this.root.querySelector('.wish-picture').getContext('2d');picture.clearRect(0,0,128,128);wishIcon(picture,w,64,64,126);
   const goals=this.root.querySelector('.goals');goals.replaceChildren();for(const [key,label] of entries){const item=document.createElement('div');item.className='goal '+(!this.free&&g[key]?'done':'');item.setAttribute('aria-label',label+(!this.free&&g[key]?'，完成':''));item.title=label;const canvas=document.createElement('canvas');canvas.width=128;canvas.height=88;const c=canvas.getContext('2d');if(key==='colors'){w.colors.forEach((index,i)=>{const step=Math.min(38,100/w.colors.length),x=64+(i-(w.colors.length-1)/2)*step;c.fillStyle=`rgb(${palette[index].join(',')})`;c.beginPath();c.arc(x,44,w.colors.length>3?12:20,0,Math.PI*2);c.fill();c.strokeStyle='#fff9ee';c.lineWidth=3;c.stroke();c.fillStyle='#ffffffaa';c.beginPath();c.ellipse(x-6,36,6,3,-.6,0,Math.PI*2);c.fill()})}else if(key==='length'){wishIcon(c,{...w,colors:[1],accessory:'none'},64,44,78)}else ornament(c,w.accessory,64,44,52,w.colors[0]);item.append(canvas);const tick=document.createElement('span');tick.className='goal-tick';tick.textContent=g[key]&&!this.free?'✓':'';item.append(tick);goals.append(item)}}
  const key=JSON.stringify([mode,a.replay.hits.map(h=>[h.x,h.y,h.w,h.h,h.label,h.picture])]);if(key!==this.panelKey){this.panelKey=key;const controls=this.root.querySelector('.panel-controls');controls.replaceChildren();if(mode)for(const h of a.replay.hits){const b=document.createElement('button');b.className='panel-hit'+(h.picture?' care-picture':'');b.setAttribute('aria-label',h.label||'選擇');if(h.picture)b.innerHTML=svg(h.picture);Object.assign(b.style,{left:h.x+'px',top:h.y+'px',width:h.w+'px',height:h.h+'px'});b.onclick=()=>{if(!a.replay.busy)h.run()};controls.append(b)}}
  if(a.problem()&&!this.warned){this.warned=true;this.notify('這次無法保存到裝置。仍可玩，也可下載照片。')}
 }
}
