// 「資料來源」 page data for Skyglaze (天青航空). Machine-readable; SOURCES.md is the human-readable twin.
// status: 'verified'  = number or range read in a public source during this build (2026-10-05)
//         'secondary' = found only in a secondary/low-quality summary; treated as an indication
//         'design'    = no public source; a design value chosen for the game and flagged as such
// usedFor lists the CONST / data field the value feeds. url may be null for design values.

export const SOURCES = [
  { id: 'route-traffic-tw', status: 'verified', topicZh: '台灣航線實際客量與座位', topicEn: 'Taiwan route passengers and seats',
    valueZh: '民航局 2025 年統計表 53-1、53-2、53-4。桃園—洛杉磯雙向旅客 995,840 人次、座位 1,365,065 個，歷史載客率 73%。只取航線合計，不重複加上各航空公司明細。',
    valueEn: 'Taiwan CAA 2025 tables 53-1, 53-2 and 53-4. TPE–LAX: 995,840 passengers and 1,365,065 seats, both directions; historical load 73%. Route totals only; carrier subtotals are not added again.',
    sourceName: 'Taiwan Civil Aviation Administration, 2025 annual statistics', url: 'https://www.caa.gov.tw/article.aspx?a=1746&lang=1', usedFor: ['OBSERVED_MARKETS: 111 pairs'] },
  { id: 'route-traffic-us', status: 'verified', topicZh: '美國國際航線客量與座位', topicEn: 'US international route passengers and seats',
    valueZh: 'BTS T-100 International Segment，2025 年全年、所有航空公司、定期客運 F 類，合計雙向與 12 個月。航段客量包含轉機旅客，不是完整起訖需求。',
    valueEn: 'BTS T-100 International Segment, all carriers, 12 months of 2025, scheduled passenger class F. Directions and carriers aggregated. Flight-leg traffic includes connections, not true journey O-D.',
    sourceName: 'US DOT Bureau of Transportation Statistics', url: 'https://www.transtats.bts.gov/DL_SelectFields.aspx?gnoyr_VQ=FJE', usedFor: ['OBSERVED_MARKETS: 530 pairs'] },
  { id: 'route-traffic-uk', status: 'verified', topicZh: '英國國際航線客量', topicEn: 'UK international route passengers',
    valueZh: 'CAA 2025 年 Table 12.1，採定期航班雙向客量。此表沒有座位數，運力另外估算，並在航線面板標示。',
    valueEn: 'CAA annual 2025 Table 12.1, scheduled passengers in both directions. Seats are not provided; capacity is separately estimated and labelled in the route panel.',
    sourceName: 'UK Civil Aviation Authority', url: 'https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airports/uk-airport-data/uk-airport-data-2025/annual-2025/', usedFor: ['OBSERVED_MARKETS: 138 pairs'] },
  { id: 'route-traffic-eu', status: 'verified', topicZh: '歐洲航線客量與座位', topicEn: 'European route passengers and seats',
    valueZh: 'Eurostat avia_par_*，29 個報告國，2024 年 PAS_BRD 旅客與 ST_PAS 座位。雙向航段統計，含定期與非定期客運。兩端機場同時報告時，只選一份；不同年份與來源不加總。',
    valueEn: 'Eurostat avia_par_*, 29 reporting countries, annual 2024 PAS_BRD passengers and ST_PAS seats. Bidirectional flight stages, scheduled and non-scheduled passenger flights. Mirrored reporters, sources and years are never added together.',
    sourceName: 'Eurostat air transport statistics', url: 'https://ec.europa.eu/eurostat/cache/metadata/EN/avia_pa_esms.htm', usedFor: ['OBSERVED_MARKETS: 714 pairs'] },
  { id: 'airport-geography', status: 'verified',
    topicZh: '全球航點的機場代碼與座標', topicEn: 'Airport codes and coordinates',
    valueZh: '新增 148 個航點，共 180 個。新增航點的機場代碼與座標核對 OurAirports 2026-10-05 公開資料，並使用有定期航班的機場。每個城市只選一座機場，避免重複計算同一都會區需求。新增城市的有效航空集客規模取概略都會／島嶼人口的 65%（設計值），用以簡化搭機參與程度，並非人口統計。集客規模、商務與觀光權重、費用、季節與時段限制皆為簡化遊戲設定，不代表實測客量或現行航權。',
    valueEn: '148 added airports, 180 total. New codes and coordinates checked against the 2026-10-05 OurAirports public-domain data, selecting airports with scheduled service. One airport per city avoids duplicating metropolitan demand. New effective air-travel catchments use 65% of approximate metro/island populations as a design assumption for participation, not a census count. Catchments, business/leisure weights, fees, seasons and slot limits are simplified game assumptions, not measured traffic or current traffic rights.',
    sourceName: 'OurAirports open data (Public Domain)', url: 'https://ourairports.com/data/',
    usedFor: ['CITIES.*.id / lat / lon', 'CITY_REGIONS'] },
  { id: 'iata-outlook-2025', status: 'verified',
    topicZh: '全球航空業獲利與載客率', topicEn: 'Industry profit and load factor',
    valueZh: '2025 年淨利 395 億美元、淨利率 3.9%、每位旅客獲利 7.90 美元；2026 年預測淨利率 3.9%、載客率 83.8%、燃油占營運成本 25.7%、人事占 28%、投入資本報酬率 6.8%（資金成本 8.2%）。',
    valueEn: '2025 net profit US$39.5B, net margin 3.9%, US$7.90 per passenger; 2026 forecast net margin 3.9%, load factor 83.8%, fuel 25.7% of operating cost, labour 28%, ROIC 6.8% against an 8.2% cost of capital.',
    sourceName: 'IATA press release, 9 Dec 2025', url: 'https://www.iata.org/en/pressroom/2025-releases/2025-12-09-01/',
    usedFor: ['CONST.industryMargin', 'end-report benchmark', 'cost-share test ranges'] },
  { id: 'iata-wats-costs', status: 'verified',
    topicZh: '航空公司成本結構', topicEn: 'Airline cost structure',
    valueZh: 'IATA 世界航空運輸統計（2022 至 2023）：燃油 28.7%、折舊與攤銷 9.1%、飛行員 8.6%、機務維修 8.4%、一般行政 7.7%、場站 7.1%、航管費約 4.3%。燃油占比各區差異大：北美 25.5%，拉丁美洲 36.3%。',
    valueEn: 'IATA World Air Transport Statistics (2022-23): fuel 28.7%, depreciation and amortisation 9.1%, flight crew 8.6%, maintenance 8.4%, general and administrative 7.7%, station 7.1%, navigation about 4.3%. Fuel varies by region: 25.5% North America to 36.3% Latin America.',
    sourceName: 'IATA Knowledge Hub, "Unveiling the biggest airline costs"', url: 'https://www.iata.org/en/publications/newsletters/iata-knowledge-hub/unveiling-the-biggest-airline-costs/',
    usedFor: ['cost-share test ranges: fuel 17-36%, labour 20-32%, maintenance 6-11%', 'maintenance per block hour', 'overhead'] },
  { id: 'ownership-share', status: 'design',
    topicZh: '飛機持有成本占比', topicEn: 'Ownership cost share',
    valueZh: 'IATA 的折舊占 9.1%，是以自有、已折舊的機隊為主。遊戲的機隊全部租賃（或新購），租金按市場價，所以持有成本占 15% 到 21%，高於 IATA 的折舊比例。這是刻意保留的差異：它讓「飛機閒置也要付租金」這一課看得見。',
    valueEn: 'IATA shows depreciation at 9.1%, mostly on owned, partly depreciated fleets. The game leases at market rent (or buys new), so ownership is 15-21% of cost, above IATA’s depreciation share. Kept on purpose so that "an idle aircraft still costs its lease" is visible.',
    sourceName: 'Design value (see lease rates below)', url: null, usedFor: ['AIRCRAFT.leasePerMonth', 'CONST.deprYears'] },
  { id: 'breakeven-lf', status: 'secondary',
    topicZh: '損益平衡載客率', topicEn: 'Break-even load factor',
    valueZh: '常見說法是全球損益平衡載客率 80% 左右，但我們沒在 IATA 原始資料找到這個數字，所以遊戲不直接用它；有一則網路摘要稱傳統航空約 74% 到 80%、廉航 82% 到 86%（來源品質低）。遊戲不設定損益平衡載客率，而是由成本與票價算出：損益平衡載客率 = 載客率 × 成本 ÷ 營收。整體網路的結果約 65% 到 80%。',
    valueEn: 'A commonly quoted figure is an industry break-even load factor near 80%, but we could not find it in IATA primary data, so the game does not use it directly. One web summary gives 74-80% for full-service and 82-86% for low-cost carriers (low-quality source). The game does not set it; it is computed as load factor x cost / revenue. Network results land around 65-80%.',
    sourceName: 'Search summary; IATA release (load factor 83.5% in 2024, 83.8% forecast 2026)', url: 'https://www.iata.org/en/pressroom/2025-releases/2025-12-09-01/',
    usedFor: ['route and company breakEvenLF'] },
  { id: 'ryanair-ancillary', status: 'verified',
    topicZh: '廉航的輔助收入', topicEn: 'Low-cost ancillary revenue',
    valueZh: 'Ryanair 2025 財年輔助收入 47.19 億歐元，占營收 139.49 億歐元的 33.8%，每位旅客 23.63 歐元；easyJet 約 25%（較早年度）。遊戲中廉航輔助收入占營收約 19%，低於 Ryanair，因為 Ryanair 是極端案例。',
    valueEn: 'Ryanair FY2025 ancillary revenue EUR 4,719M = 33.8% of EUR 13,949M revenue, EUR 23.63 per passenger; easyJet about 25% (older year). The game’s low-cost ancillary share is about 19%, below Ryanair, which is the extreme case.',
    sourceName: 'Travel Extra summary of Ryanair FY25 results; Ryanair FY25 results presentation', url: 'https://www.travelextra.ie/74971-2/',
    usedFor: ['CONST.ancillary (lcc base US$20 + 4.5% of reference fare; fsc US$6 + 2%)'] },
  { id: 'ryanair-unit-cost', status: 'verified',
    topicZh: '廉航單位成本', topicEn: 'Low-cost unit cost',
    valueZh: 'Ryanair 2025 財年不含燃油的單位成本為每位旅客 36 歐元。搜尋未取得 Lufthansa 不含燃油的絕對每座位公里成本，也未取得可引用的「廉航比傳統航空低幾成」的數字；歐洲傳統航空是全球單位成本最高的區域（CAPA）。遊戲的廉航每座位公里成本比同一航網的傳統航空低約 23%，是設計值。',
    valueEn: 'Ryanair FY2025 unit cost ex-fuel was EUR 36 per passenger. No absolute ex-fuel CASK for Lufthansa and no citable "low-cost is x% cheaper" ratio could be found; European full-service carriers have the highest unit cost in the world (CAPA). The game’s low-cost CASK is about 23% below a full-service carrier on the same network: a design value.',
    sourceName: 'Ryanair FY25 presentation; CAPA CASK analysis', url: 'https://investor.ryanair.com/wp-content/uploads/2025/05/FY25-Ryanair-Presentation.pdf',
    usedFor: ['CONST.lcc.* (seat density, crew, ground, airport, overhead multipliers)'] },
  { id: 'lease-narrowbody', status: 'verified',
    topicZh: '窄體機租金', topicEn: 'Narrowbody lease rates',
    valueZh: '新的 A320neo、737 MAX 8 月租約 40 萬美元，A321neo 約 46 萬美元；2025 年海南航空一筆租約約 34.5 萬到 36 萬美元。Airbus A320neo 取 40 萬、Airbus A321LR 取 46 萬。',
    valueEn: 'New A320neo / 737 MAX 8 about US$400k a month, A321neo about US$460k; a 2025 Hainan Airlines deal about US$345-360k. Airbus A320neo uses 400k, Airbus A321LR uses 460k.',
    sourceName: 'ch-aviation, 2025', url: 'https://www.ch-aviation.com/news/144317-chinas-hainan-airlines-holding-announces-new-a320neo-leases',
    usedFor: ['AIRCRAFT[MQ-320].leasePerMonth', 'AIRCRAFT[MQ-321].leasePerMonth'] },
  { id: 'lease-widebody', status: 'verified',
    topicZh: '寬體機租金', topicEn: 'Widebody lease rates',
    valueZh: 'A350-900 月租約 92.5 萬美元（2021 年 1 月）至 95.4 萬美元（2023 年 1 月）；777-300ER 機齡 12 年約 31.4 萬美元（2022 年 10 月）；A330 機齡 10 年約 20 萬出頭；新的 787-8 約 86.2 萬美元（2010 年資料）。Airbus A350-900 取 95 萬；Boeing 777-300ER 的遊戲租金沿用平衡設定，取 105 萬（設計值，不代表真實市場租金）。',
    valueEn: 'A350-900 about US$925k a month (Jan 2021) to US$954k (Jan 2023); 12-year-old 777-300ER about US$314k (Oct 2022); 10-year-old A330 in the low US$200ks; new 787-8 about US$862k (2010 data). Airbus A350-900 uses 950k; Boeing 777-300ER retains the game’s balancing rate of 1,050k (design value, not a real market quote).',
    sourceName: 'IBA / aviation press via search (iba.aero, aircraft interiors, AJOT)', url: 'https://www.iba.aero/insight/new-generation-widebody-lease-rates-are-rising/',
    usedFor: ['AIRCRAFT[MQ-350].leasePerMonth', 'AIRCRAFT[MQ-400].leasePerMonth'] },
  { id: 'fuel-burn', status: 'verified',
    topicZh: '每輪擋小時燃油消耗', topicEn: 'Fuel burn per block hour',
    valueZh: 'A320neo 巡航約 2,200 到 2,400 公斤每小時（Lufthansa 機隊平均 2,250）；777-300ER 約 7.35 公噸每小時（Aircraft Commerce）；Airbus 稱 A350-900 單座位燃油比 777-200ER 少約三成。Airbus A320neo 取 2,450（含滑行與爬升，輪擋平均），Boeing 777-300ER 取 7,300，Airbus A350-900 取 5,800（由 777 與 Airbus 說法推算，設計值）。支線機與渦槳為設計值。',
    valueEn: 'A320neo cruise about 2,200-2,400 kg/h (Lufthansa fleet average 2,250); 777-300ER about 7.35 t/h (Aircraft Commerce); Airbus says the A350-900 burns about 30% less per seat than the 777-200ER. Airbus A320neo uses 2,450 (block average incl. taxi and climb), Boeing 777-300ER 7,300, Airbus A350-900 5,800 (derived from the 777 figure and Airbus’s claim; design). Regional jet and turboprop are design values.',
    sourceName: 'The Flying Engineer / Wikipedia A320neo; Aircraft Commerce 777 fuel guide; Airbus', url: 'https://theflyingengineer.com/airbus-a320neo-vs-boeing-737-max-fuel-burn-comparison/',
    usedFor: ['AIRCRAFT.*.fuelPerBlockHour', 'CONST.fuelPriceUsdPerKg = 0.72 (jet about US$0.72/kg, i.e. roughly US$90-100/bbl crude plus crack spread; design)'] },
  { id: 'crew-cost', status: 'secondary',
    topicZh: '機組成本', topicEn: 'Crew cost',
    valueZh: 'A320 的機組成本約每飛行小時 1,000 到 1,200 美元，總直接營運成本每飛行小時 6,000 到 7,500 美元（低品質彙整）。MIT 航空資料顯示不同航空公司的同型機組與維修成本可差三到四倍（例如 737-500：United 機組 927、維修 1,048；Southwest 機組 388、維修 251 美元每輪擋小時，舊資料）。Airbus A320neo 的機組成本取 1,100 × 1.25，再加地勤人事，使人事占成本 24% 到 28%（IATA 人事 28%）。',
    valueEn: 'A320 crew cost is about US$1,000-1,200 per flight hour and total direct operating cost US$6,000-7,500 per flight hour (low-quality compilation). MIT airline data show crew and maintenance cost per block hour for the same type differing 3-4x between carriers (737-500: United crew 927, maintenance 1,048; Southwest 388 and 251; old data). Airbus A320neo crew is 1,100 x 1.25 plus ground staff, putting labour at 24-28% of cost (IATA 28%).',
    sourceName: 'Aviation Week operating-cost tables; MIT Airline Data Project; aircraft operating-cost compilations', url: 'https://web.mit.edu/airlinedata/www/2016%2012%20Month%20Documents/Aircraft%20and%20Related/Carrier%20Detail%20Block%20Hour/United%20Airlines%20Aircraft%20Operating%20Statistics%2D%20Cost%20Per%20Block%20Hour%20%28Unadjusted%29.htm',
    usedFor: ['AIRCRAFT.*.crewPerBlockHour', 'CONST.crewScale', 'CONST.groundLabourPerDep / PerPax'] },
  { id: 'airport-charges', status: 'verified',
    topicZh: '機場與航管費用', topicEn: 'Airport and navigation charges',
    valueZh: '新加坡樟宜：A320 級窄體每次降落的起降、停放與登機橋費約 1,200 新幣，2030 年 4 月前逐年升到約 1,725 新幣。蘇黎世：每位出發的本地旅客 30.40 瑞士法郎、轉機旅客 14.00 瑞士法郎。倫敦希斯洛：2025 年每位旅客收費上限約 23.73 英鎊。旅客費用多數轉嫁到機票稅費，所以遊戲只計入航空公司自行負擔的部分：每趟起降費（依機型）加按距離計的航管費，再加每位旅客 3 美元，全部乘以機場費率係數（0.6 到 1.8，設計值），再乘 1.3 的調整係數。',
    valueEn: 'Singapore Changi: landing, parking and aerobridge fees for an A320-class narrowbody about S$1,200 per landing, rising to about S$1,725 by April 2030. Zurich: CHF 30.40 per departing local passenger, CHF 14.00 per transfer passenger. London Heathrow: 2025 price cap about GBP 23.73 per passenger. Passenger charges mostly pass through to ticket taxes, so the game counts only the airline-borne part: a per-departure fee by aircraft type plus distance-based navigation, plus US$3 per passenger, all times a city fee level (0.6-1.8, design) and a 1.3 scaling factor.',
    sourceName: 'Changi Airport Group fee notices; CAPA (Zurich); UK CAA', url: 'https://changiairport.com/content/dam/cacorp/documents/changiairportgroup/list-of-fees-and-charges.pdf',
    usedFor: ['AIRCRAFT.*.airportPerDep / navPerKm', 'CITIES.*.feeLevel', 'CONST.airportScale, CONST.paxCharge'] },
  { id: 'fares', status: 'verified',
    topicZh: '參考票價', topicEn: 'Reference fares',
    valueZh: '2025 至 2026 年線上可見的單程經濟艙票價：台北到東京平均約 123 美元（最低約 168 起）、台北到曼谷 157 到 218 美元、蘇黎世到倫敦平均約 73 美元（最低 106 起）、蘇黎世到新加坡約 582 美元、倫敦到新加坡約 499 美元（525 起）、洛杉磯到台北 450 到 844 美元。參考票價公式：30 + 0.14 × 距離^0.9 美元，再乘機場費率（所得）係數與長程高艙等比重。遊戲的「平均票價」包含商務艙座位，長程高於經濟艙價格。',
    valueEn: 'One-way economy fares visible online in 2025-26: Taipei-Tokyo average about US$123 (from about 168), Taipei-Bangkok 157-218, Zurich-London average about 73 (from 106), Zurich-Singapore about 582, London-Singapore about 499 (from 525), Los Angeles-Taipei 450-844. Reference fare: 30 + 0.14 x distance^0.9 US$, times a local price level (from the city fee level) and a premium-cabin share on long routes. The game’s average fare includes premium-cabin seats, so it sits above economy fares on long routes.',
    sourceName: 'FareCompare, Kupi, Omio, airline route pages (lowest-fare aggregators; used as ranges, not averages of paid fares)', url: 'https://www.farecompare.com/flights/Zurich-ZRH/London-LON/market.html',
    usedFor: ['refFareMid()', 'CONST.premiumUplift', 'CONST.fareTier'] },
  { id: 'utilisation', status: 'secondary',
    topicZh: '飛機日利用率', topicEn: 'Daily utilisation',
    valueZh: '廉航通常每天超過 12 個輪擋小時（英國 CAA 摘要）；easyJet 11.9 小時（2012 年第三季，舊資料）；傳統航空短程約 8 到 9 小時（未附出處的常見說法）。遊戲的上限：窄體 11 小時，廉航 +1.5 小時；寬體 15 小時，廉航 +0.5 小時；渦槳 8 小時。上限不是平均值，因為每週班次由玩家決定。',
    valueEn: 'Low-cost carriers typically exceed 12 block hours a day (UK CAA snippet); easyJet 11.9 h (Q3 FY2012, old); legacy short-haul about 8-9 h (commonly cited, no source). Game caps: narrowbody 11 h, low-cost +1.5 h; widebody 15 h, low-cost +0.5 h; turboprop 8 h. A cap, not an average, because the player sets weekly flights.',
    sourceName: 'UK CAA; easyJet; Boeing ABS "Great Convergence" 2025', url: 'https://services.boeing.com/bgsmedias/sys_master/noindex/h5a/h07/8978938986526/ABS-Great-Convergence-Low-Cost%20Carriers-2025/ABS-Great-Convergence-Low-Cost-Carriers-2025.pdf',
    usedFor: ['AIRCRAFT.*.maxHoursPerDay', 'CONST.lcc.extraHours'] },
  { id: 'hedging', status: 'verified',
    topicZh: '燃油避險', topicEn: 'Fuel hedging',
    valueZh: 'Ryanair 約 80% 到 84% 已避險（每桶 67 到 77 美元）；Lufthansa 在 2024 年底已避險 2025 年需求的 76%；SAS 未來 12 個月 0%。遊戲的避險：鎖定當時油價，費用 2%，展期後以市價重新鎖定；範例玩家用 50%。',
    valueEn: 'Ryanair about 80-84% hedged at US$67-77/bbl; Lufthansa had hedged 76% of 2025 needs by end-2024; SAS 0% for the next 12 months. In the game a hedge locks the spot index at purchase for a 2% fee and rolls to the then-spot price at expiry; the sample operator hedges 50%.',
    sourceName: 'Reuters-style factbox, Hydrocarbon Processing, March 2026', url: 'https://www.hydrocarbonprocessing.com/news/2026/03/how-airlines-have-hedged-against-fuel-price-increases/',
    usedFor: ['CONST.hedge'] },
  { id: 'oil-2008', status: 'verified',
    topicZh: '2008 年油價衝擊', topicEn: 'The 2008 oil shock',
    valueZh: '2008 年 6 月油價 107 美元時，IATA 把全年預測從獲利 96 億美元改為虧損 23 億美元；燃油帳單 1,760 億美元，比 2007 年多 400 億；2008 至 2009 兩年合計虧損約 310 億美元。2020 年初的預測是虧損 840 億美元。事件「油價暴漲」的指數 1.8 與 1.9 是這個量級的虛構版本。',
    valueEn: 'At US$107 oil in June 2008 IATA swung its forecast from a US$9.6B profit to a US$2.3B loss; the fuel bill was US$176B, US$40B above 2007; 2008-09 combined loss about US$31B. Early 2020 forecast was a US$84B loss. The game’s oil-shock event (index 1.8 and 1.9) is a fictional version of that scale.',
    sourceName: 'IATA 2008 outlook and later summaries', url: 'https://www.iata.org/en/pressroom/2025-releases/2025-12-09-01/',
    usedFor: ['EVENTS b-oil, a-fuel'] },
  { id: 'slots', status: 'verified',
    topicZh: '機場時段', topicEn: 'Airport slots',
    valueZh: '希斯洛機場法定上限為每年 48 萬架次，時段極度稀缺。遊戲中擁擠機場每週最多 14 班（時段事件後降為 7 班）是設計值。',
    valueEn: 'Heathrow’s legal cap is 480,000 movements a year and slots are extremely scarce. The game’s 14 flights a week at congested airports (7 after the slot event) is a design value.',
    sourceName: 'UK CAA / Heathrow', url: 'https://www.caa.co.uk/media/mhpbazy1/46-frontier-slot-scarcity-and-ticket-prices-at-heathrow.pdf',
    usedFor: ['MODES.decade.slotCap', 'EVENTS b-slot'] },
  { id: 'elasticity', status: 'design',
    topicZh: '價格彈性', topicEn: 'Price elasticity',
    valueZh: '商務客比觀光客不敏感。遊戲取觀光 -1.6、商務 -0.7，長程乘 0.8，皆為設計值。新航空在整體市場的占比通常很小，份額指數直接使用彈性參數，不再乘 2；占比越大，有效價格彈性越低。',
    valueEn: 'Leisure elasticity -1.6, business -0.7 and long-haul x0.8 are design assumptions. For a small entrant the share exponent uses elasticity directly, without the old x2. Effective elasticity falls as market share grows.',
    sourceName: 'InterVISTAS for IATA, "Estimating air travel demand elasticities"', url: 'https://www.iata.org/en/iata-repository/publications/economic-reports/estimating-air-travel-demand-elasticities---by-intervistas',
    usedFor: ['CONST.elasticity', 'CONST.shareElasticityMult'] },
  { id: 'gravity', status: 'design',
    topicZh: '需求模型', topicEn: 'Demand model',
    valueZh: '180 個航點共有 16,110 組配對，1,493 組採官方航段客量；其餘由已觀測航線校準人口、距離、機場與區域影響後估算。留出 288 組航線驗證，估算偏差中位數 1.52 倍、九成約在 2.81 倍內；這不是未開航市場的可信區間。沒有資料不等於沒有需求，也不代表有直飛航班。季節曲線與需求事件為設計值。',
    valueEn: '180 airports yield 16,110 pairs; 1,493 use official flight-leg traffic. Others are fitted estimates using population, distance, airport and region effects. On 288 held-out operating routes, median multiplicative error is 1.52x, P90 is 2.81x; not a confidence interval for unserved markets. Missing data means neither zero demand nor an existing nonstop service. Seasonality and events are design assumptions.',
    sourceName: 'Academic air-demand literature (Mainz, NASA, EUR papers); general knowledge', url: null,
    usedFor: ['pairBase()', 'CITIES.*.pop / season'] }
];

// Design values with no external source. Listed so the 「資料來源」 page can show them as design choices.
export const DESIGN_VALUES = [
  { id: 'hub-yield', zhName: '各樞紐的票價指數', enName: 'Hub yield index',
    value: 'TPE 1.1659/1.1450, NRT 1.1171/1.0763, SIN 1.0985/1.0855, DXB 1.0843/1.0537, ZRH 1.1461/1.0800 (year/decade); crew scale 1.25',
    zh: '新客量模型重新校準票價與機組成本，使示範玩家的整體淨利率維持 3% 到 8%，成本占比維持既有測試範圍。這些是設計值，不是實收票價或薪資；官方客量與座位沒有為獲利而修改。',
    en: 'Yield and crew cost are recalibrated for the new route mix to keep sample margins at 3–8% and costs inside the existing test bands. These are design values, not paid fares or wages; official passengers and seats are unchanged.' },
  { id: 'share', zhName: '航班份額與對手', enName: 'Frequency share and rivals',
    value: 'seat-proportional share; frequency premium 0.12 business / 0.05 leisure; spill p=8; missing capacity: traffic/0.82',
    zh: '以座位數分配旅客，再由票價、班次與服務調整。其他航空運力採官方座位數；缺少座位資料時，以 82% 參考載客率估算。82% 不是玩家載客率下限，也不是各航線的實測值。',
    en: 'Share follows seat capacity, fares, frequency and service. Incumbent seats use official data; missing seats use traffic/82%. This design assumption is neither a player load floor nor measured route occupancy.' },
  { id: 'lcc', zhName: '廉航參數', enName: 'Low-cost parameters',
    value: 'fare 0.8 short / 0.95 long of full-service economy; business appeal 0.55, leisure 1.15; crew x0.86, ground x0.8, airport x0.88, overhead x0.72, distribution 1.5%; denser seats; transfers x0.1',
    zh: '短程參考票價低二成，長程低 5%；長程傳統航空另含高艙等溢價。廉航對商務客吸引力較弱，對價格敏感觀光客較強；成本優勢在寬體上減半。這些都是設計值。',
    en: 'Reference fares are 20% lower short-haul and 5% lower long-haul; full-service long-haul adds a premium-cabin uplift. Low-cost appeal is lower for business and higher for price-sensitive leisure. Widebody cost advantages are halved. These are design assumptions.' },
  { id: 'ramp', zhName: '新航線爬升期', enName: 'Route ramp-up',
    value: 'year: 70%, 90%, 100% of potential; decade: 90%, 100%', zh: '新航線前幾個回合只拿到部分客人。', en: 'New routes win only part of their potential in the first turns.' },
  { id: 'supply-response', zhName: '運力的動態調整', enName: 'Dynamic capacity response',
    value: '15% monthly convergence; ±4% baseline capacity/month; index 0.4–2.5; half of player seats displaces incumbent target',
    zh: '需求依季節、成長與事件變化，玩家增班立即增加座位。其他航空於結算後逐步調整運力；需求衝擊不會當期撤掉所有航班。反應速度與調整幅度為設計值，存檔保留調整結果。',
    en: 'Demand follows seasons, growth and events; player frequency adds seats immediately. Incumbents adjust gradually after settlement, so shocks do not instantly remove schedules. Response speed and bounds are design assumptions, preserved in saves.' },
  { id: 'transfer', zhName: '轉機旅客', enName: 'Transfer traffic',
    value: 'K=0.012 year / 0.03 decade; detour<=1.8; reserve 15% of leg traffic; at most 60% of spare seats; through fare 92%',
    zh: '官方航段客量含轉機，沒有完整起訖資料。先保留 15% 市場給獨立轉機模型，避免在全部歷史客量上再加轉機客；比例為設計值，不是實測比率。每條線轉機增量不超過保留客量與 60% 空位。',
    en: 'Official leg traffic includes connections without true O-D. A design 15% reserve is excluded from local demand and caps the separate transfer model, avoiding adding connections to the entire observed market. It is not measured. Transfers are also capped at 60% of spare seats.' },
  { id: 'finance', zhName: '貸款與買機', enName: 'Loans and purchases',
    value: '20% down, 80% loan, 12-year amortisation, floating base rate 5.5%, 25-year depreciation to 10% residual, resale at 92% of book (70% in the pandemic), lease return fee 2 months, government relief loan 3%',
    zh: '買機自付兩成，其餘貸款；浮動利率；疫情期間二手機價下跌。', en: '20% down, floating-rate loan, resale value drops in the pandemic.' },
  { id: 'overhead', zhName: '管理費用與起降費係數', enName: 'Overhead and scaling',
    value: 'overhead US$330k + 70k per aircraft a month; route launch US$120k; airport scale 1.3; ground labour US$1,300 per departure + 11 per passenger',
    zh: '固定成本隨機隊擴大；新航線有開辦費。', en: 'Fixed costs grow with the fleet; new routes carry a launch cost.' },
  { id: 'expansion', zhName: '機隊與航網擴張限制', enName: 'Fleet and network expansion',
    value: 'lease deposit = 2 months; delivery = next turn; orders/turn = 2 year / 3 decade; fleet cap = 6 / 10 (depot 10 / 16); destinations = 8 / 12 (depot 12 / 20)',
    zh: '訂機先付可退押金或購機頭期款；交付前不能排航線。待交機也占機隊容量。取消退款但不返還本回合訂機額度；退租另收兩個月租金的解約費。數量、押金與交機等待都是遊戲設計值，並非真實航空市場慣例。',
    en: 'Orders require a refundable lease deposit or a purchase down payment. Pending deliveries cannot fly and consume fleet capacity. Cancellation refunds cash but does not restore the turn quota; lease returns incur a two-month termination fee. Quotas, deposits and delivery times are gameplay assumptions, not real airline market practices.' },
  { id: 'start', zhName: '起始資金與機隊', enName: 'Starting cash and fleet',
    value: 'year: US$45M and 2 x Airbus A320neo leased; decade: US$150M, 2 x Airbus A320neo and 1 x Embraer E190 leased', zh: '設計值。', en: 'Design values.' }
];

// Honest summary of what the verification pass did and did not find (shown at the bottom of the page).
export const VERIFICATION = {
  zh: [
    '查到：IATA 2025/2026 展望（淨利率、載客率、燃油與人事占比）、IATA 成本結構（燃油 28.7%、折舊 9.1%、機組 8.6%、維修 8.4%、行政 7.7%、場站 7.1%、航管 4.3%）、窄體與寬體租金、A320neo 與 777-300ER 油耗、Ryanair 輔助收入與單位成本、樟宜與蘇黎世費用、線上票價範例、避險比例。',
    '沒查到原始來源（以設計值處理）：損益平衡載客率 80%、廉航與傳統航空的每座位公里成本比、彈性數值、支線機與渦槳的成本、A350 油耗的實測值、各機場的完整收費表。',
    '各家資料對長程彈性的說法互相矛盾，遊戲依設計規格取「長程較不敏感」，並標為設計值。'
  ],
  en: [
    'Found: IATA 2025/2026 outlook (margin, load factor, fuel and labour shares), IATA cost structure (fuel 28.7%, depreciation 9.1%, crew 8.6%, maintenance 8.4%, G&A 7.7%, station 7.1%, navigation 4.3%), narrowbody and widebody lease rates, A320neo and 777-300ER fuel burn, Ryanair ancillary revenue and unit cost, Changi and Zurich charges, online fare examples, hedge ratios.',
    'Not found in a primary source (treated as design values): the 80% industry break-even load factor, the low-cost vs full-service CASK ratio, numeric elasticities, regional-jet and turboprop costs, a measured A350 burn, full airport tariff tables.',
    'Sources contradict each other on whether long-haul is more or less elastic; the game follows the design spec (less sensitive) and flags it as a design value.'
  ]
};

export const AIRCRAFT_REFERENCES = [
  { name: 'ATR 72-600', url: 'https://www.atr-aircraft.com/regional-mobility/regional-aircraft/atr-72-600/' },
  { name: 'Embraer E190', url: 'https://www.embraer.com/e-jets/e190/en/' },
  { name: 'Airbus A320neo / A321LR', url: 'https://www.airbus.com/en/products-services/commercial-aircraft/passenger-aircraft/a320-family' },
  { name: 'Airbus A350-900', url: 'https://www.airbus.com/en/products-services/commercial-aircraft/passenger-aircraft/a350-family' },
  { name: 'Boeing 777-300ER', url: 'https://www.boeing.com/commercial/777' },
];
